import type { Prisma } from '@prisma/client'

type AchievementInput = { playerId:string; playerRowId:string; playerName:string; clubId:string|null; clubName:string; leagueId:string; leagueName:string; season:string; grade:string; previousGoals:number; goals:number; weeklyGoals:number; previousMatches:number|null; matches:number|null }
type Achievement = { type:string; title:string; body:string; label:string; value:string; qualifier:string }
const norm=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-')
const rankFor=(rows:Array<{playerId:string;goals:number}>,playerId:string,goals:number)=>1+rows.filter(row=>row.playerId!==playerId&&row.goals>goals).length
const settingKey=(type:string)=>`goalKickerAchievement:${type}:enabled`

export async function publishGoalKickerAchievements(tx:Prisma.TransactionClient,input:AchievementInput){
  if(input.weeklyGoals<=0)return{achievementsCreated:0,feedEventsCreated:0}
  const [seasonRows,leagueRows,clubRows,careerRows,updateEvents,settings]=await Promise.all([
    tx.footballGoalKicker.findMany({where:{season:input.season,grade:input.grade},select:{playerId:true,goals:true,matches:true}}),
    tx.footballGoalKicker.findMany({where:{season:input.season,grade:input.grade,leagueId:input.leagueId},select:{playerId:true,goals:true,matches:true}}),
    input.clubId?tx.footballGoalKicker.findMany({where:{season:input.season,grade:input.grade,clubId:input.clubId},select:{playerId:true,goals:true,matches:true}}):Promise.resolve([]),
    tx.footballGoalKicker.findMany({where:{playerId:input.playerId,NOT:{id:input.playerRowId}},select:{goals:true,season:true}}),
    tx.notification.findMany({where:{type:'GOAL_KICKER_UPDATED'},orderBy:{createdAt:'desc'},take:5000,select:{data:true}}),
    tx.setting.findMany({where:{key:{startsWith:'goalKickerAchievement:'}},select:{key:true,value:true}}),
  ])
  const enabled=new Map(settings.map(row=>[row.key,row.value!=='false']))
  const achievements:Achievement[]=[]
  const add=(a:Achievement)=>{if(enabled.get(settingKey(a.type))!==false)achievements.push(a)}
  for(const milestone of [50,100] as const){if(input.previousGoals<milestone&&input.goals>=milestone){add({type:`SEASON_${milestone}_GOALS`,title:`${input.playerName} reaches ${milestone} goals`,body:`${input.playerName} has reached ${milestone} season goals for ${input.clubName}.`,label:`${milestone}-goal milestone`,value:`${input.goals} goals`,qualifier:String(milestone)});if(input.matches&&seasonRows.filter(r=>r.goals>=milestone&&r.matches&&r.matches>0).every(r=>r.playerId===input.playerId||input.matches!<=r.matches!))add({type:`FASTEST_TO_${milestone}`,title:`${input.playerName} is fastest to ${milestone}`,body:`${input.playerName} reached ${milestone} goals in ${input.matches} matches.`,label:`Fastest to ${milestone}`,value:`${input.matches} matches`,qualifier:`${milestone}-${input.matches}`})}}
  const cn=rankFor(seasonRows,input.playerId,input.goals),pn=rankFor(seasonRows,input.playerId,input.previousGoals)
  if(cn===1&&pn>1)add({type:'NATIONAL_GOAL_LEADER',title:`${input.playerName} takes the national lead`,body:`${input.playerName} now leads PlayFooty with ${input.goals} goals.`,label:'National goal leader',value:`${input.goals} goals`,qualifier:String(input.goals)})
  if(cn<=10&&pn>10)add({type:'NATIONAL_TOP_10',title:`${input.playerName} enters the national top 10`,body:`${input.playerName} has moved to #${cn} nationally with ${input.goals} goals.`,label:'National top 10',value:`#${cn}`,qualifier:`${cn}-${input.goals}`})
  const cl=rankFor(leagueRows,input.playerId,input.goals),pl=rankFor(leagueRows,input.playerId,input.previousGoals)
  if(cl===1&&pl>1)add({type:'LEAGUE_GOAL_LEADER',title:`${input.playerName} takes the ${input.leagueName} lead`,body:`${input.playerName} now leads ${input.leagueName} with ${input.goals} goals.`,label:'League goal leader',value:`${input.goals} goals`,qualifier:`${input.leagueId}-${input.goals}`})
  if(input.clubId){const cc=rankFor(clubRows,input.playerId,input.goals),pc=rankFor(clubRows,input.playerId,input.previousGoals);if(cc===1&&pc>1)add({type:'CLUB_GOAL_LEADER',title:`${input.playerName} takes ${input.clubName}'s lead`,body:`${input.playerName} is now ${input.clubName}'s leading goal kicker with ${input.goals} goals.`,label:'Club goal leader',value:`${input.goals} goals`,qualifier:`${input.clubId}-${input.goals}`})}
  const career=careerRows.reduce((b,r)=>Math.max(b,r.goals),0);if(input.goals>career&&input.previousGoals<=career&&career>0)add({type:'CAREER_BEST_SEASON',title:`${input.playerName} sets a new career best`,body:`${input.playerName}'s ${input.goals} goals is their best imported season total on PlayFooty.`,label:'Career-best season',value:`${input.goals} goals`,qualifier:`${input.season}-${input.goals}`})
  let biggest=0;for(const event of updateEvents){try{const d=event.data?JSON.parse(event.data) as {weeklyGoals?:number;playerId?:string;goals?:number}:{};if(d.playerId!==input.playerId||d.goals!==input.goals)biggest=Math.max(biggest,Number(d.weeklyGoals)||0)}catch{}}
  if(input.weeklyGoals>biggest)add({type:'BIGGEST_WEEKLY_GOAL_INCREASE',title:`${input.playerName} records the biggest weekly increase`,body:`${input.playerName} added ${input.weeklyGoals} goals in the latest approved update.`,label:'Biggest weekly increase',value:`+${input.weeklyGoals}`,qualifier:`${input.goals}-${input.weeklyGoals}`})
  if(input.matches&&input.matches>0){const g=input.goals/input.matches,pg=input.previousMatches&&input.previousMatches>0?input.previousGoals/input.previousMatches:0,b=seasonRows.filter(r=>r.playerId!==input.playerId&&r.matches&&r.matches>0).reduce((m,r)=>Math.max(m,r.goals/r.matches!),0);if(g>b&&pg<=b)add({type:'GOALS_PER_GAME_LEADER',title:`${input.playerName} takes the goals-per-game lead`,body:`${input.playerName} now averages ${g.toFixed(2)} goals per match.`,label:'Goals-per-game leader',value:g.toFixed(2),qualifier:`${input.goals}-${input.matches}`})}
  const playerUrl=`/player/${encodeURIComponent(input.playerRowId)}`,clubUrl=input.clubId?`/team/${encodeURIComponent(input.clubId)}`:null,leagueUrl=`/league/${encodeURIComponent(input.leagueId)}`
  let achievementsCreated=0,feedEventsCreated=0
  for(const a of achievements){const baseKey=`goal-achievement:${a.type}:${input.season}:${norm(input.grade)}:${input.playerId}:${norm(a.qualifier)}`,payload={...input,achievementType:a.type,achievementLabel:a.label,achievementValue:a.value,playerUrl,clubUrl,leagueUrl,shareCardType:'GOAL_KICKER_ACHIEVEMENT'};if(!await tx.notification.findUnique({where:{dedupeKey:baseKey},select:{id:true}})){await tx.notification.create({data:{recipientScope:'PLATFORM',type:'GOAL_KICKER_ACHIEVEMENT',category:'PLAYER',severity:'SUCCESS',title:a.title,body:a.body,entityType:'PLAYER',entityId:input.playerId,data:JSON.stringify(payload),status:'DELIVERED',dedupeKey:baseKey}});achievementsCreated++}for(const t of [{suffix:'player-feed',entityType:'PLAYER',entityId:input.playerId,href:playerUrl},...(input.clubId?[{suffix:'club-feed',entityType:'CLUB',entityId:input.clubId,href:playerUrl}]:[]),{suffix:'league-feed',entityType:'LEAGUE',entityId:input.leagueId,href:playerUrl}]){const key=`${baseKey}:${t.suffix}`;if(await tx.notification.findUnique({where:{dedupeKey:key},select:{id:true}}))continue;await tx.notification.create({data:{recipientScope:'PLATFORM',type:'GOAL_KICKER_ACHIEVEMENT',category:'FEED',severity:'SUCCESS',title:a.title,body:a.body,entityType:t.entityType,entityId:t.entityId,data:JSON.stringify({...payload,href:t.href}),status:'DELIVERED',dedupeKey:key}});feedEventsCreated++}}
  return{achievementsCreated,feedEventsCreated}
}
