import { Router } from 'express'
import { prisma } from '../../db/client.js'
import { authenticateClubUser, membershipForClub, roleCan } from '../../auth/club-auth.js'

const router=Router()
const editable=['ground','address','googleMapsUrl','websiteUrl','facebookUrl','instagramUrl','tiktokUrl','youtubeUrl','email','phone','trainingNights','homeCourt','clubColours','history','foundedYear','committee','president','secretary','coach','assistantCoach','membershipLink','volunteerLink'] as const
const imageTypes=new Set(['image/png','image/jpeg','image/jpg','image/webp'])
const maxBytes=8*1024*1024
function clean(v:unknown,max=2000){return typeof v==='string'?v.trim().slice(0,max):''}
function parseList(v:string|null|undefined){try{const p=v?JSON.parse(v):[];return Array.isArray(p)?p.filter(x=>typeof x==='string'):[]}catch{return[]}}
async function requireProfileRole(req:any,res:any,next:any){await authenticateClubUser(req,res,async()=>{const m=await membershipForClub(req.clubUser.id,String(req.params.clubId));if(!m||m.status!=='ACTIVE'||!roleCan(m.role,'profile'))return res.status(403).json({error:'You do not have permission to manage this club profile'});res.locals.clubMembership=m;next()})}
router.use('/clubs/:clubId',requireProfileRole)
router.get('/clubs/:clubId',async(req,res)=>{const club=await prisma.club.findFirst({where:{id:req.params.clubId,archivedAt:null},select:{id:true,name:true,shortName:true,logoUrl:true,primaryColour:true,secondaryColour:true,description:true,websiteUrl:true,facebookUrl:true,instagramUrl:true,contactEmail:true,state:{select:{code:true,name:true}},clubSeasons:{where:{isActive:true},orderBy:{season:'desc'},take:1,select:{season:true,grade:true,leagueId:true,league:{select:{name:true}}}}}});if(!club)return res.status(404).json({error:'Club not found'});const profile=await prisma.clubProfile.upsert({where:{clubId:club.id},create:{clubId:club.id},update:{}});res.json({data:{club:{...club,season:club.clubSeasons[0]?.season??null,grade:club.clubSeasons[0]?.grade??null,leagueId:club.clubSeasons[0]?.leagueId??null,leagueName:club.clubSeasons[0]?.league.name??null},profile:{...profile,gallery:parseList(profile.gallery),uniformPhotos:parseList(profile.uniformPhotos)}}})})
router.patch('/clubs/:clubId',async(req,res)=>{const body=(req.body??{}) as Record<string,unknown>;const updates:Record<string,unknown>={};for(const field of editable)if(field in body)updates[field]=body[field]===''?null:body[field];if(!Object.keys(updates).length)return res.status(400).json({error:'No editable profile fields supplied'});const profile=await prisma.clubProfile.upsert({where:{clubId:req.params.clubId},create:{clubId:req.params.clubId,...updates},update:updates});const core:Record<string,unknown>={};if('history'in updates)core.description=updates.history;if('websiteUrl'in updates)core.websiteUrl=updates.websiteUrl;if('facebookUrl'in updates)core.facebookUrl=updates.facebookUrl;if('instagramUrl'in updates)core.instagramUrl=updates.instagramUrl;if('email'in updates)core.contactEmail=updates.email;if(Object.keys(core).length)await prisma.club.update({where:{id:req.params.clubId},data:core});res.json({data:profile,message:'Club profile saved'})})
router.post('/clubs/:clubId/photos',async(req,res)=>{try{const kind=String(req.body?.kind??'gallery')==='uniform'?'uniform':'gallery';const type=String(req.body?.contentType??'image/jpeg');if(!imageTypes.has(type))return res.status(400).json({error:'Use PNG, JPG or WEBP images'});const raw=String(req.body?.dataUrl??'');const base64=raw.includes(',')?raw.split(',').pop()!:raw;const buffer=Buffer.from(base64,'base64');if(!buffer.length||buffer.length>maxBytes)return res.status(400).json({error:'Image must be between 1 byte and 8 MB'});const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;const bucket=process.env.SUPABASE_NEWS_BUCKET||process.env.SUPABASE_LOGO_BUCKET||'playfooty-logos';if(!url||!key)return res.status(503).json({error:'Photo storage is not configured'});const ext=type.includes('png')?'png':type.includes('webp')?'webp':'jpg';const path=`club-photos/${req.params.clubId}/${kind}/${Date.now()}.${ext}`;const upload=await fetch(`${url}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{authorization:`Bearer ${key}`,apikey:key,'content-type':type,'x-upsert':'true'},body:buffer});if(!upload.ok)return res.status(400).json({error:`Photo upload failed: HTTP ${upload.status}`});const publicUrl=`${url}/storage/v1/object/public/${bucket}/${path}`;const profile=await prisma.clubProfile.upsert({where:{clubId:req.params.clubId},create:{clubId:req.params.clubId},update:{}});const field=kind==='uniform'?'uniformPhotos':'gallery';const list=[...parseList(profile[field]),publicUrl].slice(-30);await prisma.clubProfile.update({where:{clubId:req.params.clubId},data:{[field]:JSON.stringify(list)}});res.status(201).json({data:{url:publicUrl,kind,photos:list}})}catch(error){res.status(500).json({error:'Unable to upload club photo',detail:String(error)})}})
router.delete('/clubs/:clubId/photos',async(req,res)=>{const url=clean(req.body?.url,2000),kind=String(req.body?.kind??'gallery')==='uniform'?'uniform':'gallery';if(!url)return res.status(400).json({error:'Photo URL is required'});const profile=await prisma.clubProfile.upsert({where:{clubId:req.params.clubId},create:{clubId:req.params.clubId},update:{}});const field=kind==='uniform'?'uniformPhotos':'gallery';const list=parseList(profile[field]).filter(item=>item!==url);await prisma.clubProfile.update({where:{clubId:req.params.clubId},data:{[field]:JSON.stringify(list)}});res.json({data:{photos:list}})})
export {router as clubProfileManagementRouter}
