import { Router } from 'express'
import { randomUUID } from 'node:crypto'
import { prisma } from '../../db/client.js'
import { authenticateLeagueUser, membershipForLeague, requireActiveLeagueMembership } from '../../auth/league-auth.js'

const router=Router()
let schemaReady:Promise<void>|null=null
async function ensureReadSchema(){if(!schemaReady)schemaReady=(async()=>{await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS league_portal_notification_reads (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,league_id TEXT NOT NULL,notification_id TEXT NOT NULL,read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,notification_id))`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS league_portal_notification_reads_user_league_idx ON league_portal_notification_reads(user_id,league_id,read_at DESC)`)})().catch(error=>{schemaReady=null;throw error});return schemaReady}
const sensitiveActions=new Set(['INVITATION_CREATED','INVITATION_ACCEPTED','INVITATION_REVOKED','APPROVE','REJECT','SUSPEND','REACTIVATE','REVOKE','CHANGE_ROLE'])

router.get('/leagues/:leagueId/activity',authenticateLeagueUser,requireActiveLeagueMembership,async(req,res)=>{try{await ensureReadSchema();const leagueId=req.params.leagueId,userId=req.clubUser!.id;const membership=res.locals.leagueMembership as Awaited<ReturnType<typeof membershipForLeague>>;if(!membership)return res.status(403).json({error:'Active league access is required'});const privileged=['OWNER','ADMIN'].includes(membership.role)
 const [notificationsResult,auditResult,newsResult,sponsorResult]=await Promise.allSettled([
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT n.id,n.type,n.category,n.severity,n.status,n.title,n.body,n."entityType",n."entityId",n.data,n."createdAt",CASE WHEN r.notification_id IS NULL THEN false ELSE true END AS "isRead" FROM notifications n LEFT JOIN league_portal_notification_reads r ON r.notification_id=n.id::text AND r.user_id=$2 WHERE n."recipientScope"='LEAGUE' AND n."recipientId"=$1 ORDER BY n."createdAt" DESC LIMIT 100`,leagueId,userId),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT id,action,actor_id AS "actorId",detail,created_at AS "createdAt" FROM league_portal_membership_audit WHERE league_id=$1 ORDER BY created_at DESC LIMIT 80`,leagueId),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT a.id,a.title,a.status,a."updatedAt" AS "createdAt",a.slug FROM generated_articles a JOIN article_links l ON l."articleId"=a.id WHERE l."entityType"='LEAGUE' AND l."entityId"=$1 AND a.status<>'ARCHIVED' ORDER BY a."updatedAt" DESC LIMIT 50`,leagueId),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT e.id,e."toStatus" AS status,e.actor,e.note,e."createdAt",s.id AS "sponsorshipId",cs.name AS "sponsorName" FROM sponsorship_events e JOIN sponsorships s ON s.id=e."sponsorshipId" JOIN commercial_sponsors cs ON cs.id=s."sponsorId" WHERE s."leagueId"=$1 AND s."deletedAt" IS NULL ORDER BY e."createdAt" DESC LIMIT 60`,leagueId)
 ])
 const notifications=notificationsResult.status==='fulfilled'?notificationsResult.value:[]
 const audit=auditResult.status==='fulfilled'?auditResult.value.filter(item=>privileged||!sensitiveActions.has(String(item.action??''))):[]
 const activity=[...audit.map(item=>({...item,source:'ACCESS',title:String(item.action??'').replaceAll('_',' ')})),...(newsResult.status==='fulfilled'?newsResult.value.map(item=>({...item,source:'NEWS',title:item.title,detail:`Article ${String(item.status??'').toLowerCase()}`})):[]),...(sponsorResult.status==='fulfilled'?sponsorResult.value.map(item=>({...item,source:'SPONSOR',title:item.sponsorName,detail:`Sponsorship ${String(item.status??'').toLowerCase()}`})):[])].sort((a,b)=>new Date(String(b.createdAt??0)).getTime()-new Date(String(a.createdAt??0)).getTime()).slice(0,140)
 res.json({data:{membership:{role:membership.role},notifications,unread:notifications.filter(item=>!item.isRead).length,activity,generatedAt:new Date().toISOString()}})
}catch(error){res.status(500).json({error:'Unable to load league activity',detail:String(error)})}})

router.post('/leagues/:leagueId/notifications/:notificationId/read',authenticateLeagueUser,requireActiveLeagueMembership,async(req,res)=>{try{await ensureReadSchema();const leagueId=req.params.leagueId,userId=req.clubUser!.id,notificationId=req.params.notificationId;const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT id::text AS id FROM notifications WHERE id::text=$1 AND "recipientScope"='LEAGUE' AND "recipientId"=$2 LIMIT 1`,notificationId,leagueId);if(!rows[0])return res.status(404).json({error:'Notification not found for this league'});await prisma.$executeRawUnsafe(`INSERT INTO league_portal_notification_reads(id,user_id,league_id,notification_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,notification_id) DO UPDATE SET read_at=NOW()`,randomUUID(),userId,leagueId,notificationId);res.json({data:{notificationId,isRead:true}})}catch(error){res.status(500).json({error:'Unable to mark notification read',detail:String(error)})}})
router.post('/leagues/:leagueId/notifications/read-all',authenticateLeagueUser,requireActiveLeagueMembership,async(req,res)=>{try{await ensureReadSchema();const leagueId=req.params.leagueId,userId=req.clubUser!.id;await prisma.$executeRawUnsafe(`INSERT INTO league_portal_notification_reads(id,user_id,league_id,notification_id) SELECT gen_random_uuid()::text,$2,$1,n.id::text FROM notifications n WHERE n."recipientScope"='LEAGUE' AND n."recipientId"=$1 ON CONFLICT(user_id,notification_id) DO UPDATE SET read_at=NOW()`,leagueId,userId);res.json({data:{readAll:true}})}catch(error){res.status(500).json({error:'Unable to mark notifications read',detail:String(error)})}})
export {router as leaguePortalActivityRouter}
