import { Router } from 'express'
import { prisma } from '../../db/client.js'
import { authenticateLeagueUser, membershipForLeague, requireActiveLeagueMembership, roleCanManageLeagueAction } from '../../auth/league-auth.js'

const router=Router()
const clean=(value:unknown,max:number)=>typeof value==='string'?value.trim().slice(0,max):''
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,140)
const paragraphs=(value:string)=>JSON.stringify(value.split(/\n{2,}/).map(text=>text.trim()).filter(Boolean).map(text=>({type:'p',text})))
const bodyText=(value:string)=>{try{const rows=JSON.parse(value);return Array.isArray(rows)?rows.map(row=>String(row?.text??'')).filter(Boolean).join('\n\n'):''}catch{return''}}
async function requireMedia(req:any,res:any,next:any){const membership=res.locals.leagueMembership as Awaited<ReturnType<typeof membershipForLeague>>;if(!membership||!roleCanManageLeagueAction(membership.role,'media'))return res.status(403).json({error:'Your league role cannot manage news and media'});next()}
async function ownedArticle(leagueId:string,articleId:string){const link=await prisma.articleLink.findFirst({where:{articleId,entityType:'LEAGUE',entityId:leagueId},select:{id:true}});return link?prisma.generatedArticle.findUnique({where:{id:articleId}}):null}

router.use(authenticateLeagueUser)
router.get('/leagues/:leagueId/news',requireActiveLeagueMembership,requireMedia,async(req,res)=>{const links=await prisma.articleLink.findMany({where:{entityType:'LEAGUE',entityId:req.params.leagueId},select:{articleId:true}});const ids=[...new Set(links.map(item=>item.articleId))];const rows=ids.length?await prisma.generatedArticle.findMany({where:{id:{in:ids},status:{not:'ARCHIVED'}},orderBy:{updatedAt:'desc'}}):[];res.json({data:rows.map(row=>({...row,body:bodyText(row.body)}))})})
router.post('/leagues/:leagueId/news',requireActiveLeagueMembership,requireMedia,async(req,res)=>{const league=await prisma.league.findFirst({where:{id:req.params.leagueId,archivedAt:null},select:{id:true,name:true}});if(!league)return res.status(404).json({error:'League not found'});const title=clean(req.body?.title,220),summary=clean(req.body?.summary,1000),body=clean(req.body?.body,20000);if(!title||!summary||!body)return res.status(400).json({error:'Headline, summary and article body are required'});const base=slugify(title)||'league-news';let slug=base,suffix=2;while(await prisma.generatedArticle.findUnique({where:{slug},select:{id:true}}))slug=`${base}-${suffix++}`;const article=await prisma.$transaction(async tx=>{const created=await tx.generatedArticle.create({data:{slug,kind:'LEAGUE_UPDATE',category:'league-news',title,subtitle:clean(req.body?.subtitle,300)||null,summary,body:paragraphs(body),heroSeed:slug,tags:JSON.stringify({league:league.name,leagueId:league.id,source:'LEAGUE_PORTAL'}),status:'DRAFT',author:clean(req.body?.author,120)||league.name,sourceData:JSON.stringify({source:'LEAGUE_PORTAL',leagueId:league.id,userId:req.clubUser!.id}),confidence:1,reasoning:'Submitted by an approved league representative.',seoTitle:title,seoDescription:summary.slice(0,500)}});await tx.articleLink.create({data:{articleId:created.id,entityType:'LEAGUE',entityId:league.id,label:league.name}});return created});res.status(201).json({data:{...article,body}})})
router.patch('/leagues/:leagueId/news/:articleId',requireActiveLeagueMembership,requireMedia,async(req,res)=>{const article=await ownedArticle(req.params.leagueId,req.params.articleId);if(!article)return res.status(404).json({error:'League article not found'});if(article.status==='PUBLISHED')return res.status(409).json({error:'Published articles must be changed by PlayFooty Admin'});const status=String(req.body?.status??article.status).toUpperCase();if(!['DRAFT','APPROVED'].includes(status))return res.status(400).json({error:'League articles can only be draft or awaiting approval'});const title=clean(req.body?.title,220),summary=clean(req.body?.summary,1000),body=clean(req.body?.body,20000);if(!title||!summary||!body)return res.status(400).json({error:'Headline, summary and article body are required'});const updated=await prisma.generatedArticle.update({where:{id:article.id},data:{title,subtitle:clean(req.body?.subtitle,300)||null,summary,body:paragraphs(body),author:clean(req.body?.author,120)||article.author,status,seoTitle:title,seoDescription:summary.slice(0,500),publishedAt:null}});res.json({data:{...updated,body},message:status==='APPROVED'?'Article submitted for PlayFooty approval':'Draft saved'})})

export {router as leaguePortalNewsRouter}
