import { Router } from 'express'
import { randomUUID } from 'node:crypto'
import { prisma } from '../../db/client.js'
import { authenticateLeagueUser, membershipForLeague, requireActiveLeagueMembership, roleCanManageLeagueAction } from '../../auth/league-auth.js'

const router=Router()
const BUCKET=process.env.SUPABASE_MEDIA_BUCKET||process.env.SUPABASE_NEWS_BUCKET||process.env.SUPABASE_LOGO_BUCKET||'playfooty-logos'
const TYPES=new Set(['image/png','image/jpeg','image/jpg','image/webp'])
const EXT:Record<string,string>={'image/png':'png','image/jpeg':'jpg','image/jpg':'jpg','image/webp':'webp'}
let schemaReady:Promise<void>|null=null
async function ensureMediaSchema(){if(!schemaReady)schemaReady=(async()=>{
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS media_assets (
  id TEXT PRIMARY KEY, url TEXT NOT NULL, storage_path TEXT, media_type TEXT NOT NULL DEFAULT 'IMAGE',
  mime_type TEXT, caption TEXT, credit TEXT, alt_text TEXT, uploaded_by TEXT NOT NULL,
  archived_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
 )`)
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS media_entity_links (
  id TEXT PRIMARY KEY, media_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL,
  usage TEXT NOT NULL DEFAULT 'GALLERY', sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(media_id,entity_type,entity_id,usage)
 )`)
 await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS media_entity_links_entity_idx ON media_entity_links(entity_type,entity_id,usage,sort_order)`)
})().catch(error=>{schemaReady=null;throw error});return schemaReady}
async function requireMedia(req:any,res:any,next:any){const membership=res.locals.leagueMembership as Awaited<ReturnType<typeof membershipForLeague>>;if(!membership||!roleCanManageLeagueAction(membership.role,'media'))return res.status(403).json({error:'Your league role cannot manage league media'});next()}
async function linkedAsset(leagueId:string,id:string){await ensureMediaSchema();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m.*,l.usage,l.sort_order AS "sortOrder" FROM media_assets m JOIN media_entity_links l ON l.media_id=m.id WHERE m.id=$1 AND l.entity_type='LEAGUE' AND l.entity_id=$2 LIMIT 1`,id,leagueId);return rows[0]??null}

router.get('/leagues/:leagueId/media',authenticateLeagueUser,requireActiveLeagueMembership,async(req,res)=>{await ensureMediaSchema();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m.id,m.url,m.media_type AS "mediaType",m.mime_type AS "mimeType",m.caption,m.credit,m.alt_text AS "altText",m.archived_at AS "archivedAt",m.created_at AS "createdAt",m.updated_at AS "updatedAt",l.usage,l.sort_order AS "sortOrder" FROM media_assets m JOIN media_entity_links l ON l.media_id=m.id WHERE l.entity_type='LEAGUE' AND l.entity_id=$1 ORDER BY CASE WHEN m.archived_at IS NULL THEN 0 ELSE 1 END,l.sort_order,m.created_at DESC`,req.params.leagueId);res.json({data:{items:rows,membership:res.locals.leagueMembership}})})
router.post('/leagues/:leagueId/media',authenticateLeagueUser,requireActiveLeagueMembership,requireMedia,async(req,res)=>{await ensureMediaSchema();const contentType=String(req.body?.contentType??'image/jpeg');if(!TYPES.has(contentType))return res.status(400).json({error:'Use PNG, JPG or WEBP'});const raw=String(req.body?.dataUrl??''),base64=raw.includes(',')?raw.split(',').pop()!:raw,buffer=Buffer.from(base64,'base64');if(!buffer.length||buffer.length>10*1024*1024)return res.status(400).json({error:'Image must be 10 MB or smaller'});const url=(process.env.SUPABASE_URL??'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY||'';if(!url||!key)return res.status(503).json({error:'Media storage is not configured'});const id=randomUUID(),path=`league-media/${req.params.leagueId}/${id}.${EXT[contentType]??'jpg'}`;const upload=await fetch(`${url}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{authorization:`Bearer ${key}`,apikey:key,'content-type':contentType,'x-upsert':'true'},body:buffer});if(!upload.ok)return res.status(400).json({error:`Media upload failed: HTTP ${upload.status}`});const publicUrl=`${url}/storage/v1/object/public/${BUCKET}/${path}`;const caption=String(req.body?.caption??'').trim().slice(0,500)||null,credit=String(req.body?.credit??'').trim().slice(0,240)||null,altText=String(req.body?.altText??'').trim().slice(0,500)||null,usage=String(req.body?.usage??'GALLERY').toUpperCase();if(!['GALLERY','PROFILE','HEADER'].includes(usage))return res.status(400).json({error:'Invalid media usage'});await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`INSERT INTO media_assets(id,url,storage_path,mime_type,caption,credit,alt_text,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,publicUrl,path,contentType,caption,credit,altText,req.clubUser!.id);if(usage!=='GALLERY')await tx.$executeRawUnsafe(`DELETE FROM media_entity_links WHERE entity_type='LEAGUE' AND entity_id=$1 AND usage=$2`,req.params.leagueId,usage);await tx.$executeRawUnsafe(`INSERT INTO media_entity_links(id,media_id,entity_type,entity_id,usage,sort_order) VALUES($1,$2,'LEAGUE',$3,$4,COALESCE((SELECT MAX(sort_order)+1 FROM media_entity_links WHERE entity_type='LEAGUE' AND entity_id=$3),0))`,randomUUID(),id,req.params.leagueId,usage);if(usage==='PROFILE')await tx.$executeRawUnsafe(`UPDATE leagues SET "logoUrl"=$1,"updatedAt"=NOW() WHERE id=$2`,publicUrl,req.params.leagueId)});res.status(201).json({data:{id,url:publicUrl,caption,credit,altText,usage},message:'League media uploaded'})})
router.patch('/leagues/:leagueId/media/:mediaId',authenticateLeagueUser,requireActiveLeagueMembership,requireMedia,async(req,res)=>{const asset=await linkedAsset(req.params.leagueId,req.params.mediaId);if(!asset)return res.status(404).json({error:'League media not found'});const caption=String(req.body?.caption??asset.caption??'').trim().slice(0,500)||null,credit=String(req.body?.credit??asset.credit??'').trim().slice(0,240)||null,altText=String(req.body?.altText??asset.alt_text??'').trim().slice(0,500)||null,sortOrder=Number(req.body?.sortOrder??asset.sortOrder??0);await prisma.$executeRawUnsafe(`UPDATE media_assets SET caption=$1,credit=$2,alt_text=$3,updated_at=NOW() WHERE id=$4`,caption,credit,altText,req.params.mediaId);await prisma.$executeRawUnsafe(`UPDATE media_entity_links SET sort_order=$1 WHERE media_id=$2 AND entity_type='LEAGUE' AND entity_id=$3`,Number.isFinite(sortOrder)?sortOrder:0,req.params.mediaId,req.params.leagueId);res.json({data:{id:req.params.mediaId,caption,credit,altText,sortOrder},message:'Media details saved'})})
router.post('/leagues/:leagueId/media/:mediaId/use',authenticateLeagueUser,requireActiveLeagueMembership,requireMedia,async(req,res)=>{const asset=await linkedAsset(req.params.leagueId,req.params.mediaId);if(!asset)return res.status(404).json({error:'League media not found'});const usage=String(req.body?.usage??'GALLERY').toUpperCase();if(!['GALLERY','PROFILE','HEADER'].includes(usage))return res.status(400).json({error:'Invalid media usage'});await prisma.$transaction(async tx=>{if(usage!=='GALLERY')await tx.$executeRawUnsafe(`DELETE FROM media_entity_links WHERE entity_type='LEAGUE' AND entity_id=$1 AND usage=$2`,req.params.leagueId,usage);await tx.$executeRawUnsafe(`INSERT INTO media_entity_links(id,media_id,entity_type,entity_id,usage,sort_order) VALUES($1,$2,'LEAGUE',$3,$4,0) ON CONFLICT(media_id,entity_type,entity_id,usage) DO NOTHING`,randomUUID(),req.params.mediaId,req.params.leagueId,usage);if(usage==='PROFILE')await tx.$executeRawUnsafe(`UPDATE leagues SET "logoUrl"=$1,"updatedAt"=NOW() WHERE id=$2`,String(asset.url),req.params.leagueId)});res.json({data:{id:req.params.mediaId,usage},message:'Media usage updated'})})
router.delete('/leagues/:leagueId/media/:mediaId',authenticateLeagueUser,requireActiveLeagueMembership,requireMedia,async(req,res)=>{const asset=await linkedAsset(req.params.leagueId,req.params.mediaId);if(!asset)return res.status(404).json({error:'League media not found'});await prisma.$executeRawUnsafe(`UPDATE media_assets SET archived_at=NOW(),updated_at=NOW() WHERE id=$1`,req.params.mediaId);res.json({data:{archived:true}})})
export {router as leaguePortalMediaRouter}
