import { Router } from 'express'
import { prisma } from '../../db/client.js'
import { LEAGUE_ROLES, auditLeagueMembership, authenticateLeagueUser, ensureLeagueMembershipSchema, issueLeagueInvitation, membershipForLeague, requireActiveLeagueMembership, type LeagueRole } from '../../auth/league-auth.js'

const router=Router()
async function requireOwner(req:any,res:any,next:any){const membership=res.locals.leagueMembership as Awaited<ReturnType<typeof membershipForLeague>>;if(!membership||membership.role!=='OWNER')return res.status(403).json({error:'Only a league owner can manage league users'});next()}
async function ownerCount(leagueId:string){const rows=await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT COUNT(*)::int AS count FROM league_portal_memberships WHERE league_id=$1 AND role='OWNER' AND status='ACTIVE'`,leagueId);return rows[0]?.count??0}

router.get('/leagues/:leagueId/users',authenticateLeagueUser,requireActiveLeagueMembership,requireOwner,async(req,res)=>{await ensureLeagueMembershipSchema();const members=await prisma.$queryRawUnsafe(`SELECT id,user_id AS "userId",email,role,status,applicant_name AS "applicantName",league_position AS "leaguePosition",phone,review_notes AS "reviewNotes",approved_at AS "approvedAt",revoked_at AS "revokedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM league_portal_memberships WHERE league_id=$1 ORDER BY CASE status WHEN 'ACTIVE' THEN 0 WHEN 'PENDING' THEN 1 WHEN 'INVITED' THEN 2 WHEN 'SUSPENDED' THEN 3 ELSE 4 END,created_at`,req.params.leagueId);const invitations=await prisma.$queryRawUnsafe(`SELECT id,email,role,invited_by AS "invitedBy",expires_at AS "expiresAt",accepted_by AS "acceptedBy",accepted_at AS "acceptedAt",revoked_at AS "revokedAt",created_at AS "createdAt" FROM league_portal_invitations WHERE league_id=$1 ORDER BY created_at DESC LIMIT 100`,req.params.leagueId);const audit=await prisma.$queryRawUnsafe(`SELECT id,membership_id AS "membershipId",user_id AS "userId",action,actor_id AS "actorId",detail,created_at AS "createdAt" FROM league_portal_membership_audit WHERE league_id=$1 ORDER BY created_at DESC LIMIT 100`,req.params.leagueId);res.json({data:{members,invitations,audit,currentUserId:req.clubUser!.id}})})

router.post('/leagues/:leagueId/users/invitations',authenticateLeagueUser,requireActiveLeagueMembership,requireOwner,async(req,res)=>{await ensureLeagueMembershipSchema();const email=String(req.body?.email??'').trim().toLowerCase(),role=String(req.body?.role??'VIEWER').toUpperCase() as LeagueRole;if(!email.includes('@'))return res.status(400).json({error:'A valid email address is required'});if(!LEAGUE_ROLES.includes(role))return res.status(400).json({error:'Invalid league role'});const existing=await prisma.$queryRawUnsafe<Array<{id:string;status:string}>>(`SELECT id,status FROM league_portal_memberships WHERE league_id=$1 AND lower(email)=lower($2) ORDER BY created_at DESC LIMIT 1`,req.params.leagueId,email);if(existing[0]?.status==='ACTIVE')return res.status(409).json({error:'This email already has active league access'});await prisma.$executeRawUnsafe(`UPDATE league_portal_invitations SET revoked_at=NOW() WHERE league_id=$1 AND lower(email)=lower($2) AND accepted_at IS NULL AND revoked_at IS NULL`,req.params.leagueId,email);const token=await issueLeagueInvitation(req.params.leagueId,email,role,req.clubUser!.id);res.status(201).json({data:{email,role,invitePath:`/league-portal?invite=${token}`,expiresInDays:7},message:'Invitation created'})})

router.patch('/leagues/:leagueId/users/:membershipId',authenticateLeagueUser,requireActiveLeagueMembership,requireOwner,async(req,res)=>{await ensureLeagueMembershipSchema();const action=String(req.body?.action??'').toUpperCase(),role=String(req.body?.role??'').toUpperCase() as LeagueRole,notes=String(req.body?.notes??'').trim();if(!['CHANGE_ROLE','SUSPEND','REACTIVATE','REVOKE','APPROVE','REJECT'].includes(action))return res.status(400).json({error:'Invalid membership action'});if((action==='CHANGE_ROLE'||action==='APPROVE')&&!LEAGUE_ROLES.includes(role))return res.status(400).json({error:'Invalid league role'});const rows=await prisma.$queryRawUnsafe<Array<{id:string;leagueId:string;userId:string;role:LeagueRole;status:string}>>(`SELECT id,league_id AS "leagueId",user_id AS "userId",role,status FROM league_portal_memberships WHERE id=$1 AND league_id=$2 LIMIT 1`,req.params.membershipId,req.params.leagueId);const target=rows[0];if(!target)return res.status(404).json({error:'League membership not found'});if(target.userId===req.clubUser!.id&&['SUSPEND','REVOKE','REJECT'].includes(action))return res.status(400).json({error:'You cannot remove or suspend your own league access'});const removesOwner=target.role==='OWNER'&&target.status==='ACTIVE'&&(['SUSPEND','REVOKE','REJECT'].includes(action)||(action==='CHANGE_ROLE'&&role!=='OWNER'));if(removesOwner&&await ownerCount(req.params.leagueId)<=1)return res.status(409).json({error:'The league must retain at least one active Owner'});let nextStatus=target.status,nextRole=target.role;if(action==='CHANGE_ROLE')nextRole=role;if(action==='APPROVE'){nextStatus='ACTIVE';nextRole=role}if(action==='REACTIVATE')nextStatus='ACTIVE';if(action==='SUSPEND')nextStatus='SUSPENDED';if(action==='REVOKE'||action==='REJECT')nextStatus='REVOKED';await prisma.$executeRawUnsafe(`UPDATE league_portal_memberships SET role=$1,status=$2,review_notes=$3,approved_by=CASE WHEN $2='ACTIVE' THEN $4 ELSE approved_by END,approved_at=CASE WHEN $2='ACTIVE' THEN COALESCE(approved_at,NOW()) ELSE approved_at END,revoked_at=CASE WHEN $2='REVOKED' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=$5`,nextRole,nextStatus,notes||null,req.clubUser!.id,target.id);await auditLeagueMembership(target.id,req.params.leagueId,target.userId,action,req.clubUser!.id,{fromRole:target.role,toRole:nextRole,fromStatus:target.status,toStatus:nextStatus,notes});res.json({data:{id:target.id,role:nextRole,status:nextStatus},message:'League access updated'})})

router.post('/leagues/:leagueId/users/invitations/:invitationId/revoke',authenticateLeagueUser,requireActiveLeagueMembership,requireOwner,async(req,res)=>{await ensureLeagueMembershipSchema();const changed=await prisma.$executeRawUnsafe(`UPDATE league_portal_invitations SET revoked_at=NOW() WHERE id=$1 AND league_id=$2 AND accepted_at IS NULL AND revoked_at IS NULL`,req.params.invitationId,req.params.leagueId);if(!changed)return res.status(404).json({error:'Active invitation not found'});await auditLeagueMembership(null,req.params.leagueId,null,'INVITATION_REVOKED',req.clubUser!.id,{invitationId:req.params.invitationId});res.json({data:{revoked:true}})})

export {router as leaguePortalUsersRouter}
