import { randomUUID } from 'node:crypto'
import { Router } from 'express'
import { prisma } from '../../db/client.js'
import { authenticateClubUser, requireActiveClubMembership, roleCan } from '../../auth/club-auth.js'

export const whiteboardLearningRouter=Router()
let ready:Promise<void>|null=null
function ensureTables(){if(!ready)ready=(async()=>{
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS football_whiteboard_assignments(id uuid PRIMARY KEY,club_id text NOT NULL,play_id uuid NOT NULL,title text NOT NULL,audience text NOT NULL DEFAULT 'TEAM',recipient_ids jsonb NOT NULL DEFAULT '[]'::jsonb,instructions text NULL,quiz_question text NULL,quiz_answer text NULL,access_token text NOT NULL UNIQUE,meeting_frame text NULL,meeting_active boolean NOT NULL DEFAULT false,created_by text NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`)
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS football_whiteboard_responses(id uuid PRIMARY KEY,assignment_id uuid NOT NULL,player_name text NOT NULL,player_id text NULL,status text NOT NULL,quiz_response text NULL,quiz_correct boolean NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(assignment_id,player_name))`)
 await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS football_whiteboard_assignments_club_idx ON football_whiteboard_assignments(club_id,updated_at DESC)`)
})().catch(e=>{ready=null;throw e});return ready}
const clean=(v:unknown,n:number)=>String(v??'').trim().slice(0,n)
function canManage(res:any){const m=res.locals.clubMembership as {role?:Parameters<typeof roleCan>[0]}|undefined;return Boolean(m?.role&&roleCan(m.role,'team_selection'))}

whiteboardLearningRouter.get('/assignment/:token',async(req,res)=>{try{await ensureTables();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT a.id::text,a.title,a.audience,a.instructions,a.quiz_question AS "quizQuestion",a.meeting_frame AS "meetingFrame",a.meeting_active AS "meetingActive",p.title AS "playTitle",p.fixture_label AS "fixtureLabel",p.play_data AS play FROM football_whiteboard_assignments a JOIN football_whiteboard_plays p ON p.id=a.play_id WHERE a.access_token=$1 LIMIT 1`,req.params.token);if(!rows[0])return res.status(404).json({error:'Tactic assignment not found'});return res.json({data:rows[0]})}catch(e){return res.status(500).json({error:'Unable to load tactic assignment',detail:String(e)})}})
whiteboardLearningRouter.post('/assignment/:token/respond',async(req,res)=>{try{await ensureTables();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id::text,quiz_answer AS "quizAnswer" FROM football_whiteboard_assignments WHERE access_token=$1 LIMIT 1`,req.params.token);if(!rows[0])return res.status(404).json({error:'Assignment not found'});const name=clean(req.body?.playerName,100);if(!name)return res.status(400).json({error:'Enter your name'});const status=['VIEWED','UNDERSTOOD','NEEDS_CLARIFICATION'].includes(req.body?.status)?req.body.status:'VIEWED';const response=clean(req.body?.quizResponse,300)||null;const correct=rows[0].quizAnswer&&response?clean(rows[0].quizAnswer,300).toLowerCase()===response.toLowerCase():null;await prisma.$executeRawUnsafe(`INSERT INTO football_whiteboard_responses(id,assignment_id,player_name,player_id,status,quiz_response,quiz_correct) VALUES($1::uuid,$2::uuid,$3,$4,$5,$6,$7) ON CONFLICT(assignment_id,player_name) DO UPDATE SET status=EXCLUDED.status,quiz_response=EXCLUDED.quiz_response,quiz_correct=EXCLUDED.quiz_correct,updated_at=now()`,randomUUID(),rows[0].id,name,clean(req.body?.playerId,100)||null,status,response,correct);return res.json({data:{status,quizCorrect:correct}})}catch(e){return res.status(500).json({error:'Unable to save response',detail:String(e)})}})

whiteboardLearningRouter.use(authenticateClubUser)
whiteboardLearningRouter.use('/clubs/:clubId',requireActiveClubMembership)
whiteboardLearningRouter.post('/clubs/:clubId/plays/:playId/assign',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot assign tactics'});const title=clean(req.body?.title,120)||'Team tactic';const token=randomUUID().replaceAll('-','');const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO football_whiteboard_assignments(id,club_id,play_id,title,audience,recipient_ids,instructions,quiz_question,quiz_answer,access_token,created_by) VALUES($1::uuid,$2,$3::uuid,$4,$5,$6::jsonb,$7,$8,$9,$10,$11)`,id,req.params.clubId,req.params.playId,title,['TEAM','LINE_GROUP','SELECTED'].includes(req.body?.audience)?req.body.audience:'TEAM',JSON.stringify(Array.isArray(req.body?.recipientIds)?req.body.recipientIds.slice(0,80):[]),clean(req.body?.instructions,1500)||null,clean(req.body?.quizQuestion,300)||null,clean(req.body?.quizAnswer,300)||null,token,res.locals.clubMembership?.userId??null);return res.status(201).json({data:{id,token,url:`/coach-app/tactic/${token}`}})}catch(e){return res.status(500).json({error:'Unable to assign tactic',detail:String(e)})}})
whiteboardLearningRouter.get('/clubs/:clubId/plays/:playId/assignments',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot view learning progress'});const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT a.id::text,a.title,a.audience,a.instructions,a.created_at AS "createdAt",a.meeting_active AS "meetingActive",a.meeting_frame AS "meetingFrame",a.access_token AS token,COUNT(r.id)::int AS responses,COUNT(*) FILTER(WHERE r.status='UNDERSTOOD')::int AS understood,COUNT(*) FILTER(WHERE r.status='NEEDS_CLARIFICATION')::int AS "needsClarification" FROM football_whiteboard_assignments a LEFT JOIN football_whiteboard_responses r ON r.assignment_id=a.id WHERE a.club_id=$1 AND a.play_id::text=$2 GROUP BY a.id ORDER BY a.created_at DESC`,req.params.clubId,req.params.playId);return res.json({data:rows})}catch(e){return res.status(500).json({error:'Unable to load learning progress',detail:String(e)})}})
whiteboardLearningRouter.get('/clubs/:clubId/assignments/:id/responses',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot view player responses'});const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT r.player_name AS "playerName",r.player_id AS "playerId",r.status,r.quiz_response AS "quizResponse",r.quiz_correct AS "quizCorrect",r.updated_at AS "updatedAt" FROM football_whiteboard_responses r JOIN football_whiteboard_assignments a ON a.id=r.assignment_id WHERE a.id::text=$1 AND a.club_id=$2 ORDER BY r.updated_at DESC`,req.params.id,req.params.clubId);return res.json({data:rows})}catch(e){return res.status(500).json({error:'Unable to load responses',detail:String(e)})}})
whiteboardLearningRouter.put('/clubs/:clubId/assignments/:id/meeting',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot control meetings'});const changed=await prisma.$executeRawUnsafe(`UPDATE football_whiteboard_assignments SET meeting_active=$3,meeting_frame=$4,updated_at=now() WHERE id::text=$1 AND club_id=$2`,req.params.id,req.params.clubId,Boolean(req.body?.active),clean(req.body?.frameId,100)||null);if(!changed)return res.status(404).json({error:'Assignment not found'});return res.json({data:{active:Boolean(req.body?.active),frameId:clean(req.body?.frameId,100)||null}})}catch(e){return res.status(500).json({error:'Unable to update meeting',detail:String(e)})}})
