import { randomUUID } from 'node:crypto'
import { Router } from 'express'
import { prisma } from '../../db/client.js'
import { authenticateClubUser, requireActiveClubMembership, roleCan } from '../../auth/club-auth.js'

export const whiteboardLiveRouter=Router()
let ready:Promise<void>|null=null
function ensureTables(){if(!ready)ready=(async()=>{
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS football_whiteboard_live_sessions(id uuid PRIMARY KEY,play_id uuid NOT NULL,club_id text NOT NULL,active boolean NOT NULL DEFAULT true,active_frame_id text NULL,presenter_name text NULL,revision integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now())`)
 await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS football_whiteboard_live_play_idx ON football_whiteboard_live_sessions(play_id)`)
 await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS football_whiteboard_media(id uuid PRIMARY KEY,play_id uuid NOT NULL,club_id text NOT NULL,frame_id text NULL,media_type text NOT NULL,url text NULL,data_url text NULL,title text NULL,telestration jsonb NULL,created_by text NULL,created_at timestamptz NOT NULL DEFAULT now())`)
 await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS football_whiteboard_media_play_idx ON football_whiteboard_media(play_id,created_at DESC)`)
})().catch(e=>{ready=null;throw e});return ready}
const clean=(v:unknown,n:number)=>String(v??'').trim().slice(0,n)
function canManage(res:any){const m=res.locals.clubMembership as {role?:Parameters<typeof roleCan>[0]}|undefined;return Boolean(m?.role&&roleCan(m.role,'team_selection'))}

whiteboardLiveRouter.get('/public/assignment/:token/live',async(req,res)=>{try{await ensureTables();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT s.active,s.active_frame_id AS "activeFrameId",s.presenter_name AS "presenterName",s.revision,s.updated_at AS "updatedAt" FROM football_whiteboard_assignments a JOIN football_whiteboard_live_sessions s ON s.play_id=a.play_id WHERE a.token=$1 LIMIT 1`,req.params.token);return res.json({data:rows[0]??{active:false}})}catch(e){return res.status(500).json({error:'Unable to load live meeting',detail:String(e)})}})
whiteboardLiveRouter.use(authenticateClubUser)
whiteboardLiveRouter.use('/clubs/:clubId',requireActiveClubMembership)
whiteboardLiveRouter.get('/clubs/:clubId/plays/:playId/live',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot access live tactics'});const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id::text,active,active_frame_id AS "activeFrameId",presenter_name AS "presenterName",revision,updated_at AS "updatedAt" FROM football_whiteboard_live_sessions WHERE play_id::text=$1 AND club_id=$2 LIMIT 1`,req.params.playId,req.params.clubId);return res.json({data:rows[0]??{active:false,revision:0}})}catch(e){return res.status(500).json({error:'Unable to load live meeting',detail:String(e)})}})
whiteboardLiveRouter.put('/clubs/:clubId/plays/:playId/live',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot control live tactics'});const active=Boolean(req.body?.active);const frame=clean(req.body?.activeFrameId,100)||null;const presenter=clean(req.body?.presenterName,100)||'Coach';const id=randomUUID();const rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO football_whiteboard_live_sessions(id,play_id,club_id,active,active_frame_id,presenter_name) VALUES($1::uuid,$2::uuid,$3,$4,$5,$6) ON CONFLICT(play_id) DO UPDATE SET active=$4,active_frame_id=$5,presenter_name=$6,revision=football_whiteboard_live_sessions.revision+1,updated_at=now() RETURNING id::text,active,active_frame_id AS "activeFrameId",presenter_name AS "presenterName",revision,updated_at AS "updatedAt"`,id,req.params.playId,req.params.clubId,active,frame,presenter);return res.json({data:rows[0]})}catch(e){return res.status(500).json({error:'Unable to update live meeting',detail:String(e)})}})
whiteboardLiveRouter.get('/clubs/:clubId/plays/:playId/media',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot access tactic media'});const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id::text,frame_id AS "frameId",media_type AS "mediaType",url,data_url AS "dataUrl",title,telestration,created_at AS "createdAt" FROM football_whiteboard_media WHERE play_id::text=$1 AND club_id=$2 ORDER BY created_at DESC LIMIT 100`,req.params.playId,req.params.clubId);return res.json({data:rows})}catch(e){return res.status(500).json({error:'Unable to load tactic media',detail:String(e)})}})
whiteboardLiveRouter.post('/clubs/:clubId/plays/:playId/media',async(req,res)=>{try{await ensureTables();if(!canManage(res))return res.status(403).json({error:'Your role cannot attach tactic media'});const type=req.body?.mediaType==='AUDIO'?'AUDIO':'CLIP';const dataUrl=clean(req.body?.dataUrl,7000000)||null;const url=clean(req.body?.url,1500)||null;if(!dataUrl&&!url)return res.status(400).json({error:'Add a recording or clip URL'});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO football_whiteboard_media(id,play_id,club_id,frame_id,media_type,url,data_url,title,telestration,created_by) VALUES($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)`,id,req.params.playId,req.params.clubId,clean(req.body?.frameId,100)||null,type,url,dataUrl,clean(req.body?.title,120)||null,JSON.stringify(req.body?.telestration&&typeof req.body.telestration==='object'?req.body.telestration:{}),res.locals.clubMembership?.userId??null);return res.status(201).json({data:{id}})}catch(e){return res.status(500).json({error:'Unable to attach tactic media',detail:String(e)})}})
