import { useEffect, useState, type CSSProperties } from 'react'
import { ArrowLeft, CheckCircle2, Trash2, UploadCloud } from 'lucide-react'
import { Link } from 'react-router-dom'
import { admin, getKey, setKey, type AdminClub, type FootballLeague } from '../lib/admin'
import { goalKickerImageImports, type GoalKickerImagePreview, type GoalKickerImageRow } from '../lib/goalKickerImageImports'

type ReviewRow=GoalKickerImageRow&{decision:'import'|'skip';clubId:string}
type Item={id:string;file:File;url:string;status:'ready'|'analysing'|'review'|'failed'|'committed';preview?:GoalKickerImagePreview;error?:string}
const input:CSSProperties={width:'100%',padding:'10px 11px',border:'1px solid #dce3eb',borderRadius:10,font:'inherit',boxSizing:'border-box'}
const button=(dark=false):CSSProperties=>({border:0,borderRadius:999,padding:'11px 16px',background:dark?'#050505':'#42b8ff',color:dark?'#fff':'#050505',fontWeight:900,cursor:'pointer'})

export default function AdminGoalKickerImages(){
 const[authed,setAuthed]=useState(!!getKey());const[key,setLocalKey]=useState('');const[items,setItems]=useState<Item[]>([]);const[leagues,setLeagues]=useState<FootballLeague[]>([]);const[clubs,setClubs]=useState<AdminClub[]>([]);const[leagueId,setLeagueId]=useState('');const[season,setSeason]=useState('2026');const[grade,setGrade]=useState('Senior Football');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('')
 useEffect(()=>{if(!authed)return;admin.listFootballLeagues().then(setLeagues);admin.listClubs().then(setClubs)},[authed])
 const add=(files:FileList)=>setItems(p=>[...p,...Array.from(files).filter(f=>f.type.startsWith('image/')).map(file=>({id:`${Date.now()}-${Math.random()}`,file,url:URL.createObjectURL(file),status:'ready' as const}))])
 const analyse=async()=>{if(!items.length)return setMsg('Add at least one screenshot.');setBusy(true);for(const item of items.filter(i=>i.status==='ready'||i.status==='failed')){setItems(p=>p.map(x=>x.id===item.id?{...x,status:'analysing',error:undefined}:x));try{const image=await fileDataUrl(item.file);const preview=await goalKickerImageImports.parse(image,leagueId||undefined);setItems(p=>p.map(x=>x.id===item.id?{...x,status:'review',preview}:x));if(!leagueId&&preview.matchedLeagueId)setLeagueId(preview.matchedLeagueId);if(preview.season)setSeason(preview.season);if(preview.grade)setGrade(preview.grade)}catch(e){setItems(p=>p.map(x=>x.id===item.id?{...x,status:'failed',error:e instanceof Error?e.message:String(e)}:x))}}setBusy(false)}
 const replacePreview=(id:string,preview:GoalKickerImagePreview)=>setItems(p=>p.map(x=>x.id===id?{...x,preview}:x))
 const commit=async(item:Item)=>{if(!item.preview)return;const rows=(item.preview.rows as ReviewRow[]).filter(r=>(r.decision??'import')==='import').map(r=>({playerName:r.playerName.trim(),clubName:r.clubName.trim(),clubId:r.clubId||r.clubMatch.clubId,goals:Number(r.goals),matches:r.matches==null?null:Number(r.matches)}));if(!leagueId)return setMsg('Choose the league before committing.');if(!rows.length)return setMsg('No approved players to import.');if(rows.some(r=>!r.playerName||!r.clubName||!r.clubId||!Number.isFinite(r.goals)||r.goals<0))return setMsg('Every approved row needs a player, matched club and valid goal total.');const keys=rows.map(r=>`${r.playerName.toLowerCase()}|${r.clubId}`);if(new Set(keys).size!==keys.length)return setMsg('Duplicate player and club rows must be skipped or corrected.');if(!window.confirm(`Update ${rows.length} goal-kicker records for ${season} ${grade}?`))return;setBusy(true);try{const result=await goalKickerImageImports.commit({leagueId,season,grade,rows});setItems(p=>p.map(x=>x.id===item.id?{...x,status:'committed'}:x));setMsg(`Updated ${result.data.imported} goal-kicker records${result.data.errors?` with ${result.data.errors} errors`:''}.`)}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(!authed)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#050505'}}><div style={{background:'#fff',padding:24,borderRadius:18,width:'min(92vw,420px)'}}><h1>Goal-kicker image imports</h1><input style={input} type="password" value={key} onChange={e=>setLocalKey(e.target.value)}/><button style={{...button(),width:'100%',marginTop:12}} onClick={()=>{if(key.trim()){setKey(key.trim());setAuthed(true)}}}>Open</button></div></div>
 return <main style={{minHeight:'100vh',background:'#eef2f6',padding:24,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1380,margin:'0 auto',display:'grid',gap:18}}><header style={{background:'#050505',color:'#fff',borderRadius:20,padding:28}}><Link to="/admin" style={{color:'#42b8ff',textDecoration:'none',display:'inline-flex',gap:7,alignItems:'center'}}><ArrowLeft size={16}/>Back to Control Centre</Link><h1 style={{fontSize:'clamp(42px,7vw,84px)',margin:'12px 0 6px',textTransform:'uppercase'}}>Goal-kicker images</h1><p>Upload screenshots, match players and clubs, review every total, then explicitly update the website.</p></header><section style={{background:'#fff',borderRadius:16,padding:18,display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12}}><label>League<select style={input} value={leagueId} onChange={e=>setLeagueId(e.target.value)}><option value="">Auto-detect / choose</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Season<input style={input} value={season} onChange={e=>setSeason(e.target.value)}/></label><label>Grade<input style={input} value={grade} onChange={e=>setGrade(e.target.value)}/></label></section><label style={{minHeight:200,border:'2px dashed #92cfee',borderRadius:18,background:'#f7fcff',display:'grid',placeItems:'center',textAlign:'center',padding:24,cursor:'pointer'}}><div><UploadCloud size={44}/><h2>Choose goal-kicker screenshots</h2><span style={button()}>Select images</span></div><input hidden type="file" accept="image/*" multiple onChange={e=>{if(e.target.files)add(e.target.files);e.currentTarget.value=''}}/></label>{items.length>0&&<><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{items.map(item=><article key={item.id} style={{background:'#fff',borderRadius:15,overflow:'hidden',border:'1px solid #dce3eb'}}><img src={item.url} alt="Goal-kicker screenshot" style={{width:'100%',height:150,objectFit:'cover'}}/><div style={{padding:13,display:'grid',gap:9}}><strong>{item.file.name}</strong><small>{item.status}{item.error?` — ${item.error}`:''}</small><button style={button(true)} disabled={busy} onClick={()=>setItems(p=>p.filter(x=>x.id!==item.id))}><Trash2 size={14}/> Remove</button></div></article>)}</section><button style={button()} disabled={busy} onClick={analyse}>{busy?'Analysing…':'Analyse screenshots'}</button></>}{msg&&<div style={{background:'#fff8dc',padding:14,borderRadius:12}}>{msg}</div>}{items.map(item=>item.preview?<Review key={item.id} item={item} clubs={clubs} onChange={p=>replacePreview(item.id,p)} onCommit={()=>commit(item)} busy={busy}/>:null)}</div></main>
}

function Review({item,clubs,onChange,onCommit,busy}:{item:Item;clubs:AdminClub[];onChange:(p:GoalKickerImagePreview)=>void;onCommit:()=>void;busy:boolean}){const p=item.preview!;const rows=(p.rows as ReviewRow[]).map(r=>({...r,decision:r.decision??'import',clubId:r.clubId??r.clubMatch.clubId??''}));const patch=(i:number,v:Partial<ReviewRow>)=>onChange({...p,rows:rows.map((r,x)=>x===i?{...r,...v}:r)});const active=rows.filter(r=>r.decision==='import');const unmatched=active.filter(r=>!r.clubId).length;return <section style={{background:'#fff',borderRadius:18,overflow:'hidden',border:'1px solid #dce3eb'}}><header style={{padding:16,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><strong>{item.file.name}</strong><div>{p.league??'Unknown league'} · {p.grade} · {p.season} · {rows.length} players · {unmatched} unmatched</div></div><button style={button()} disabled={busy||item.status==='committed'} onClick={onCommit}>{item.status==='committed'?<><CheckCircle2 size={16}/> Updated</>:`Approve & update ${active.length}`}</button></header><div style={{overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1050}}><thead><tr>{['Action','Player name','Extracted club','Matched club','Existing player record','Goals','Matches','Confidence','Warning'].map(h=><th key={h} style={{padding:9,textAlign:'left',borderTop:'1px solid #e8edf2',borderBottom:'1px solid #e8edf2'}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const warning=!r.clubId?'Club match required':r.goals<0?'Invalid goals':r.playerMatch?`Updates existing ${r.playerMatch.goals} goals`:'Creates player record';return <tr key={i} style={{opacity:r.decision==='skip'?.45:1}}><td><select style={input} value={r.decision} onChange={e=>patch(i,{decision:e.target.value as 'import'|'skip'})}><option value="import">Import</option><option value="skip">Skip</option></select></td><td><input style={input} value={r.playerName} onChange={e=>patch(i,{playerName:e.target.value})}/></td><td><input style={input} value={r.clubName} onChange={e=>patch(i,{clubName:e.target.value})}/></td><td><select style={{...input,minWidth:210}} value={r.clubId} onChange={e=>patch(i,{clubId:e.target.value})}><option value="">Choose club</option>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td>{r.playerMatch?`${r.playerMatch.playerName} · ${r.playerMatch.clubName}`:'New record'}</td><td><input style={input} type="number" min={0} value={r.goals} onChange={e=>patch(i,{goals:Number(e.target.value)})}/></td><td><input style={input} type="number" min={0} value={r.matches??''} onChange={e=>patch(i,{matches:e.target.value===''?undefined:Number(e.target.value)})}/></td><td>{Math.round(r.clubMatch.score*100)}%</td><td>{warning}</td></tr>})}</tbody></table></div></section>}
function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
