import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ExternalLink, Save } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getKey } from '../lib/admin'

type ResultRow={id:string;leagueId:string;leagueName:string;season:string;grade:string;round:string|null;matchDate:string|null;homeName:string;awayName:string;homeGoals:number;homeBehinds:number;homePoints:number;awayGoals:number;awayBehinds:number;awayPoints:number;detailUrl:string}
type Kicker={playerName:string;goals:number}
type Detail={homeQuarterScores:Array<string|null>;awayQuarterScores:Array<string|null>;homeBestPlayers:string[];awayBestPlayers:string[];homeGoalKickers:Kicker[];awayGoalKickers:Kicker[];notes:string|null}
const empty:Detail={homeQuarterScores:[null,null,null,null],awayQuarterScores:[null,null,null,null],homeBestPlayers:[],awayBestPlayers:[],homeGoalKickers:[],awayGoalKickers:[],notes:null}

export default function AdminDetailedResults(){
 const[rows,setRows]=useState<ResultRow[]>([]),[selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<Detail>(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('')
 const selected=rows.find(row=>row.id===selectedId)
 const filtered=useMemo(()=>rows.filter(row=>`${row.homeName} ${row.awayName} ${row.leagueName} ${row.round??''}`.toLowerCase().includes(search.toLowerCase())),[rows,search])
 const request=async(path:string,options:RequestInit={})=>{const response=await fetch(path,{...options,headers:{...(options.headers??{}),authorization:`Bearer ${getKey()}`}});const payload=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(payload.error||`HTTP ${response.status}`);return payload}
 useEffect(()=>{void request('/admin/match-details/results').then(payload=>{const data=Array.isArray(payload.data)?payload.data:[];setRows(data);if(data[0])setSelectedId(data[0].id)}).catch(reason=>setError(reason instanceof Error?reason.message:String(reason))).finally(()=>setLoading(false))},[])
 useEffect(()=>{if(!selectedId)return;setMessage('');setError('');void request(`/admin/match-details/${encodeURIComponent(selectedId)}`).then(payload=>setDetail({...empty,...(payload.data?.detail??{})})).catch(reason=>setError(reason instanceof Error?reason.message:String(reason)))},[selectedId])
 const save=async()=>{if(!selectedId)return;setSaving(true);setError('');setMessage('');try{await request(`/admin/match-details/${encodeURIComponent(selectedId)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(detail)});setMessage('Detailed result saved and published.')}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
 const quarter=(side:'homeQuarterScores'|'awayQuarterScores',index:number,value:string)=>setDetail(current=>({...current,[side]:current[side].map((item,i)=>i===index?(value||null):item)}))
 return <main className="adr"><div className="adr-shell"><header><Link to="/admin"><ArrowLeft size={16}/>Admin</Link><span>Match Centre</span><h1>Detailed results</h1><p>Select an imported result, add quarter scores, best players and match goal kickers, then publish it to the existing Match Centre page.</p></header>{error&&<div className="err">{error}</div>}{message&&<div className="ok">{message}</div>}
 <section className="adr-layout"><aside><input placeholder="Search results" value={search} onChange={e=>setSearch(e.target.value)}/>{loading?<p>Loading results…</p>:<div className="result-list">{filtered.map(row=><button key={row.id} className={row.id===selectedId?'active':''} onClick={()=>setSelectedId(row.id)}><strong>{row.homeName} v {row.awayName}</strong><span>{row.leagueName} · {row.round?`Round ${row.round}`:'Round not set'}</span><small>{row.homePoints}–{row.awayPoints}</small></button>)}</div>}</aside>
 <section className="editor">{selected?<><div className="score-head"><div><span>{selected.leagueName} · {selected.season}</span><h2>{selected.homeName} {selected.homePoints}–{selected.awayPoints} {selected.awayName}</h2></div><a href={selected.detailUrl} target="_blank" rel="noreferrer">Preview <ExternalLink size={15}/></a></div>
 <div className="card"><h3>Quarter-by-quarter scores</h3><div className="quarters"><b>Team</b>{[1,2,3,4].map(q=><b key={q}>Q{q}</b>)}<strong>{selected.homeName}</strong>{[0,1,2,3].map(i=><input key={`h${i}`} placeholder="0.0" value={detail.homeQuarterScores[i]??''} onChange={e=>quarter('homeQuarterScores',i,e.target.value)}/>)}<strong>{selected.awayName}</strong>{[0,1,2,3].map(i=><input key={`a${i}`} placeholder="0.0" value={detail.awayQuarterScores[i]??''} onChange={e=>quarter('awayQuarterScores',i,e.target.value)}/>)}</div></div>
 <div className="two"><ListEditor title={`${selected.homeName} best players`} values={detail.homeBestPlayers} onChange={values=>setDetail(current=>({...current,homeBestPlayers:values}))}/><ListEditor title={`${selected.awayName} best players`} values={detail.awayBestPlayers} onChange={values=>setDetail(current=>({...current,awayBestPlayers:values}))}/></div>
 <div className="two"><KickerEditor title={`${selected.homeName} goal kickers`} values={detail.homeGoalKickers} onChange={values=>setDetail(current=>({...current,homeGoalKickers:values}))}/><KickerEditor title={`${selected.awayName} goal kickers`} values={detail.awayGoalKickers} onChange={values=>setDetail(current=>({...current,awayGoalKickers:values}))}/></div>
 <label className="card"><h3>Match notes</h3><textarea value={detail.notes??''} onChange={e=>setDetail(current=>({...current,notes:e.target.value||null}))} placeholder="Optional match context or review notes"/></label><button className="save" disabled={saving} onClick={()=>void save()}><Save size={17}/>{saving?'Saving…':'Save and publish detailed result'}</button></>:<p>Select a result to begin.</p>}</section></section></div><style>{styles}</style></main>
}
function ListEditor({title,values,onChange}:{title:string;values:string[];onChange:(values:string[])=>void}){return <label className="card"><h3>{title}</h3><textarea value={values.join('\n')} onChange={e=>onChange(e.target.value.split(/\n|,/).map(v=>v.trim()).filter(Boolean))} placeholder="One player per line"/></label>}
function KickerEditor({title,values,onChange}:{title:string;values:Kicker[];onChange:(values:Kicker[])=>void}){const text=values.map(row=>`${row.playerName} | ${row.goals}`).join('\n');return <label className="card"><h3>{title}</h3><textarea value={text} onChange={e=>onChange(e.target.value.split('\n').flatMap(line=>{const match=line.trim().match(/^(.*?)\s*(?:\||-|–)\s*(\d+)$/);return match?[{playerName:match[1].trim(),goals:Number(match[2])}]:[]}))} placeholder={'Player name | goals\nKeenan Hughes | 8'}/><small>Use: Player name | goals</small></label>}
const styles=`.adr{min-height:100vh;background:#eef3f7;padding:22px;color:#111318;font-family:Barlow,Inter,Arial,sans-serif}.adr-shell{max-width:1280px;margin:auto}.adr header{background:#050505;color:#fff;padding:26px;border-radius:18px}.adr header>a,.score-head a{color:#42b8ff;text-decoration:none;display:inline-flex;gap:6px;align-items:center;font-weight:900}.adr header>span{display:block;margin-top:18px;color:#42b8ff;text-transform:uppercase;font-size:10px;font-weight:950;letter-spacing:.15em}.adr h1,.adr h2,.adr h3{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.adr h1{font-size:64px;line-height:.9;margin:6px 0}.adr header p{color:#c7d0da}.adr-layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:16px;margin-top:16px}.adr aside,.editor,.card{background:#fff;border:1px solid #dce3e9;border-radius:14px}.adr aside{padding:14px;max-height:78vh;overflow:auto}.adr input,.adr textarea{width:100%;box-sizing:border-box;border:1px solid #ccd6df;border-radius:8px;padding:11px;font:inherit}.result-list{display:grid;gap:7px;margin-top:10px}.result-list button{border:1px solid #e0e6eb;border-radius:10px;padding:11px;text-align:left;background:#fff;cursor:pointer}.result-list button.active{border-color:#42b8ff;background:#eef9ff}.result-list strong,.result-list span,.result-list small{display:block}.result-list span,.result-list small{color:#687385;margin-top:3px}.editor{padding:18px}.score-head{display:flex;justify-content:space-between;gap:15px;align-items:start}.score-head span{color:#687385;font-weight:800}.score-head h2{font-size:38px;margin:5px 0 16px}.card{padding:16px;margin-top:12px}.card h3{font-size:28px;margin:0 0 10px}.card textarea{min-height:135px;resize:vertical}.card small{display:block;color:#687385;margin-top:6px}.quarters{display:grid;grid-template-columns:minmax(130px,1fr) repeat(4,minmax(60px,1fr));gap:7px;align-items:center}.quarters b{font-size:10px;color:#687385;text-transform:uppercase}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.save{width:100%;margin-top:14px;border:0;border-radius:10px;background:#21c879;padding:15px;font-weight:950;text-transform:uppercase;display:flex;justify-content:center;align-items:center;gap:7px}.ok,.err{padding:12px;border-radius:9px;margin-top:12px;font-weight:800}.ok{background:#dcf7e8;color:#17643b}.err{background:#fff0f0;color:#a51c1c}@media(max-width:850px){.adr{padding:10px}.adr h1{font-size:46px}.adr-layout{grid-template-columns:1fr}.adr aside{max-height:300px}.two{grid-template-columns:1fr}.quarters{grid-template-columns:minmax(95px,1fr) repeat(4,minmax(48px,1fr))}.score-head{flex-direction:column}}`
