import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import { getKey } from '../lib/admin'

type Club={clubId:string;clubName:string;logoUrl:string|null;planCode:string;status:string;startsAt:string|null;endsAt:string|null;notes:string|null;openRequests:number}
type Request={id:string;clubId:string;clubName:string;requestedPlan:string;requesterEmail:string|null;message:string|null;status:string;reviewNotes:string|null;createdAt:string}
type Payload={clubs:Club[];requests:Request[]}
const headers=()=>({authorization:`Bearer ${getKey()}`,'Content-Type':'application/json'})
export default function AdminClubPlans(){
 const[data,setData]=useState<Payload>({clubs:[],requests:[]});const[query,setQuery]=useState('');const[message,setMessage]=useState('')
 async function load(){const r=await fetch('/api/club-portal/admin/plans',{headers:headers()});const p=await r.json() as{data?:Payload;error?:string};if(!r.ok||!p.data){setMessage(p.error||'Unable to load plans');return}setData(p.data)}
 useEffect(()=>{void load()},[])
 const clubs=useMemo(()=>data.clubs.filter(c=>c.clubName.toLowerCase().includes(query.toLowerCase())),[data.clubs,query])
 async function assign(club:Club,planCode:string){setMessage(`Updating ${club.clubName}…`);const r=await fetch(`/api/club-portal/admin/plans/clubs/${encodeURIComponent(club.clubId)}`,{method:'PUT',headers:headers(),body:JSON.stringify({planCode,status:'ACTIVE'})});const p=await r.json() as{error?:string;message?:string};setMessage(r.ok?p.message||'Plan updated':p.error||'Plan update failed');if(r.ok)await load()}
 async function review(item:Request,status:string){const notes=window.prompt('Review notes (optional)')||'';const r=await fetch(`/api/club-portal/admin/plans/requests/${encodeURIComponent(item.id)}`,{method:'PATCH',headers:headers(),body:JSON.stringify({status,notes})});const p=await r.json() as{error?:string;message?:string};setMessage(r.ok?p.message||'Request updated':p.error||'Request update failed');if(r.ok)await load()}
 return <><Nav/><main className="acp"><header><Link to="/admin">← Admin</Link><small>COMMERCIAL ACCESS</small><h1>Club plans</h1><p>Assign club plans and review upgrade requests. Approving a request activates that plan immediately.</p></header>{message&&<div className="msg">{message}</div>}<section><h2>Upgrade requests</h2>{data.requests.filter(r=>['PENDING','CONTACTED'].includes(r.status)).length?<div className="requests">{data.requests.filter(r=>['PENDING','CONTACTED'].includes(r.status)).map(item=><article key={item.id}><div><strong>{item.clubName}</strong><span>{item.requestedPlan} · {item.requesterEmail||'No email'}</span>{item.message&&<p>{item.message}</p>}</div><div><button onClick={()=>void review(item,'CONTACTED')}>Contacted</button><button className="approve" onClick={()=>void review(item,'APPROVED')}>Approve</button><button className="reject" onClick={()=>void review(item,'REJECTED')}>Reject</button></div></article>)}</div>:<p>No upgrade requests are waiting.</p>}</section><section><div className="head"><h2>All clubs</h2><input placeholder="Search clubs" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="clubs">{clubs.map(club=><article key={club.clubId}><div className="identity"><span>{club.logoUrl?<img src={club.logoUrl} alt=""/>:club.clubName.slice(0,2).toUpperCase()}</span><div><strong>{club.clubName}</strong><small>{club.openRequests} open request{club.openRequests===1?'':'s'}</small></div></div><div className="plan"><b>{club.planCode}</b><em>{club.status}</em></div><select value={club.planCode} onChange={e=>void assign(club,e.target.value)}><option value="FREE">Free</option><option value="STANDARD">Standard</option><option value="PRO">Pro</option></select></article>)}</div></section></main><style>{styles}</style></>
}
const styles=`.acp{min-height:100vh;background:#eef3f7;padding:30px clamp(12px,4vw,42px) 60px;color:#111318}.acp>*{max-width:1200px;margin-left:auto;margin-right:auto}.acp header a{color:#111;text-decoration:none;font-weight:900}.acp header small{display:block;margin-top:18px;color:#0783c9;font-weight:900;letter-spacing:.14em}.acp h1,.acp h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.acp h1{font-size:64px;margin:5px 0}.acp header p{color:#687385}.acp section{background:#fff;border:1px solid #dce4ea;border-radius:16px;padding:20px;margin-top:16px}.acp h2{font-size:34px;margin:0 0 14px}.msg{padding:12px;border-radius:10px;background:#dff4ff;color:#066c9f;font-weight:800;margin-top:14px}.requests{display:grid;gap:10px}.requests article,.clubs article{display:flex;justify-content:space-between;align-items:center;gap:14px;border:1px solid #e2e7eb;border-radius:11px;padding:13px}.requests span,.requests strong{display:block}.requests span{color:#687385;font-size:12px;margin-top:3px}.requests p{margin:7px 0 0;color:#4f5c69}.requests article>div:last-child{display:flex;gap:7px}.acp button{border:0;border-radius:8px;padding:9px 11px;font-weight:900;cursor:pointer}.approve{background:#21c879}.reject{background:#ffe3e3;color:#9a2020}.head{display:flex;justify-content:space-between;align-items:center;gap:12px}.head input,.clubs select{border:1px solid #ccd6de;border-radius:8px;padding:10px}.clubs{display:grid;gap:8px}.identity{display:flex;align-items:center;gap:10px;min-width:0}.identity>span{width:42px;height:42px;border-radius:9px;background:#edf2f6;display:grid;place-items:center;font-weight:900;overflow:hidden}.identity img{width:100%;height:100%;object-fit:contain}.identity strong,.identity small{display:block}.identity small{color:#7a8590;margin-top:3px}.plan{margin-left:auto;text-align:right}.plan b,.plan em{display:block}.plan em{font-style:normal;color:#6d7781;font-size:10px;margin-top:3px}@media(max-width:650px){.requests article,.clubs article{align-items:flex-start;flex-direction:column}.requests article>div:last-child{width:100%;flex-wrap:wrap}.head{align-items:stretch;flex-direction:column}.plan{margin-left:0;text-align:left}.clubs select{width:100%}}`
