import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, RefreshCw, Save, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getKey } from '../lib/admin'

type League = { id:string; name:string; state:string; currentSeason?:string|null }
type Fixture = { id:string; sourceId?:string; leagueId:string; leagueName:string; season:string; grade:string; round?:string|null; matchDate?:string|null; venue?:string|null; homeClubId?:string|null; homeClubName:string; awayClubId?:string|null; awayClubName:string }

const authHeaders=()=>({authorization:`Bearer ${getKey()}`})
const jsonHeaders=()=>({'content-type':'application/json',authorization:`Bearer ${getKey()}`})

export default function AdminFeaturedGames(){
  const[leagues,setLeagues]=useState<League[]>([]),[leagueId,setLeagueId]=useState(''),[fixtures,setFixtures]=useState<Fixture[]>([]),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(false)
  useEffect(()=>{void Promise.all([
    fetch('/api/leagues').then(r=>r.json()),
    fetch('/admin/featured-games',{headers:authHeaders()}).then(r=>r.json()),
  ]).then(([leaguePayload,selectedPayload])=>{
    setLeagues(Array.isArray(leaguePayload.data)?leaguePayload.data:[])
    setSelected(Array.isArray(selectedPayload.data?.fixtureIds)?selectedPayload.data.fixtureIds:[])
  }).catch(error=>setMessage(String(error)))},[])
  useEffect(()=>{if(!leagueId){setFixtures([]);return}void loadFixtures(leagueId)},[leagueId])
  const selectedFixtures=useMemo(()=>selected.map(id=>fixtures.find(row=>(row.sourceId??row.id.replace(/^football:/,''))===id)).filter(Boolean) as Fixture[],[selected,fixtures])
  async function loadFixtures(id=leagueId){setLoading(true);setMessage('');try{const payload=await fetch(`/api/fixtures/football?league=${encodeURIComponent(id)}&limit=500`).then(r=>r.json()) as{data?:Fixture[]};setFixtures(Array.isArray(payload.data)?payload.data:[])}catch(error){setFixtures([]);setMessage(String(error))}finally{setLoading(false)}}
  function addFixture(value:string){const id=value.replace(/^football:/,'');if(!id||selected.includes(id))return;setSelected(current=>[...current,id].slice(0,3))}
  async function save(){setMessage('Saving featured games…');const response=await fetch('/admin/featured-games',{method:'PUT',headers:jsonHeaders(),body:JSON.stringify({fixtureIds:selected})});const payload=await response.json().catch(()=>({})) as{error?:string};if(!response.ok){setMessage(payload.error??'Featured games could not be saved');return}setMessage('Featured games saved to the homepage')}
  return <main className="afg"><header><div><small>PLAYFOOTY CONTROL CENTRE</small><h1>Featured games</h1><p>Choose up to three imported fixtures. Rankings, ladder positions and team ratings are read from the existing live football data.</p></div><Link to="/admin"><ArrowLeft size={17}/>Admin home</Link></header>
    <section className="afg-card"><label>League<select value={leagueId} onChange={event=>setLeagueId(event.target.value)}><option value="">Select a league</option>{leagues.map(league=><option key={league.id} value={league.id}>{league.name} · {league.state}</option>)}</select></label><button className="refresh" disabled={!leagueId||loading} onClick={()=>void loadFixtures()}><RefreshCw size={17}/>{loading?'Loading…':'Refresh games'}</button></section>
    {leagueId&&<section className="afg-card"><label>Game<select defaultValue="" onChange={event=>{addFixture(event.target.value);event.currentTarget.value=''}}><option value="">Select a game to feature</option>{fixtures.filter(row=>!selected.includes(row.sourceId??row.id.replace(/^football:/,''))).map(row=><option key={row.id} value={row.sourceId??row.id}>{fixtureLabel(row)}</option>)}</select></label><p className="hint">Select the strongest match-ups first. Their order below is the homepage carousel order.</p></section>}
    <section className="afg-list">{selected.map((id,index)=>{const fixture=selectedFixtures.find(row=>(row.sourceId??row.id.replace(/^football:/,''))===id);return <article key={id}><span>{index+1}</span><div><strong>{fixture?`${fixture.homeClubName} v ${fixture.awayClubName}`:id}</strong><small>{fixture?`${fixture.leagueName} · ${fixture.round??'Upcoming'} · ${formatDate(fixture.matchDate)}`:'Open the correct league above to preview this saved fixture'}</small></div><div className="moves"><button disabled={index===0} onClick={()=>setSelected(move(selected,index,index-1))}>↑</button><button disabled={index===selected.length-1} onClick={()=>setSelected(move(selected,index,index+1))}>↓</button><button className="remove" onClick={()=>setSelected(current=>current.filter(value=>value!==id))}><Trash2 size={17}/></button></div></article>})}{selected.length===0&&<div className="empty">No featured games selected yet.</div>}</section>
    <button className="save" onClick={()=>void save()}><Save size={18}/>Save featured games</button>{message&&<p className="message">{message}</p>}<style>{styles}</style></main>
}
function move(rows:string[],from:number,to:number){const next=[...rows];const[item]=next.splice(from,1);next.splice(to,0,item);return next}
function fixtureLabel(row:Fixture){return `${row.homeClubName} v ${row.awayClubName} · ${row.round??'Upcoming'} · ${formatDate(row.matchDate)} · ${row.grade}`}
function formatDate(value?:string|null){return value?new Date(value).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}):'Date TBC'}
const styles=`.afg{min-height:100vh;background:#eef3f7;padding:28px 18px 70px;color:#111318;font-family:Inter,Arial,sans-serif}.afg>header,.afg>section,.afg>.save,.afg>.message{width:min(980px,100%);margin-left:auto;margin-right:auto;box-sizing:border-box}.afg>header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.afg header small{color:#159ee8;font-size:10px;font-weight:950;letter-spacing:.16em}.afg h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:clamp(3.5rem,8vw,6.5rem);line-height:.86;text-transform:uppercase;margin:8px 0 12px}.afg header p{max-width:720px;color:#687385;line-height:1.55}.afg a,.afg button{display:inline-flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:9px;padding:11px 14px;background:#fff;color:#111318;text-decoration:none;font-weight:900;cursor:pointer}.afg button:disabled{opacity:.4;cursor:not-allowed}.afg-card{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:end;margin-top:18px;padding:18px;border:1px solid #dce3eb;border-radius:14px;background:#fff}.afg label{display:grid;gap:7px;color:#687385;font-size:11px;font-weight:900;text-transform:uppercase}.afg select{width:100%;padding:12px;border:1px solid #d7dfe7;border-radius:9px;background:#fff;color:#111318;font:inherit}.afg .refresh{background:#050505;color:#fff}.hint{grid-column:1/-1;margin:0;color:#687385;font-size:12px}.afg-list{display:grid;gap:10px;margin-top:18px}.afg-list article{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:13px;align-items:center;padding:15px;border:1px solid #dce3eb;border-radius:14px;background:#fff}.afg-list article>span{display:grid;place-items:center;width:44px;height:44px;border-radius:11px;background:#42b8ff;font-family:'Bebas Neue',Impact,sans-serif;font-size:27px}.afg-list strong,.afg-list small{display:block}.afg-list strong{font-size:17px}.afg-list small{margin-top:4px;color:#687385}.moves{display:flex;gap:6px}.moves button{padding:9px 11px;background:#eef3f7}.moves .remove{background:#ffe9e9;color:#b5161b}.empty{padding:32px;text-align:center;border:1px dashed #c9d3dd;border-radius:14px;color:#687385;background:#fff}.afg>.save{margin-top:18px;background:#42b8ff;padding:14px}.message{margin-top:12px;padding:12px;border-radius:10px;background:#fff}@media(max-width:700px){.afg>header{display:grid}.afg-card{grid-template-columns:1fr}.afg .refresh{width:100%}.afg-list article{grid-template-columns:42px minmax(0,1fr)}.moves{grid-column:1/-1;justify-content:flex-end}}`
