import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'

type Membership={id:string;userId:string;email:string;leagueId:string;leagueName:string;role:string;status:string;applicantName?:string|null;leaguePosition?:string|null;phone?:string|null;reason?:string|null;reviewNotes?:string|null;createdAt:string}
type League={id:string;name:string;state:string;association?:string|null}
const key=()=>localStorage.getItem('cnca_admin_key')??''
const roles=['OWNER','ADMIN','DATA_MANAGER','MEDIA_MANAGER','SPONSOR_MANAGER','VIEWER']

export default function AdminLeagueClaims(){
 const[rows,setRows]=useState<Membership[]>([]),[filter,setFilter]=useState('PENDING'),[message,setMessage]=useState(''),[leagues,setLeagues]=useState<League[]>([])
 const[invite,setInvite]=useState({leagueId:'',email:'',role:'ADMIN'})
 const load=()=>fetch(`/api/league-portal/admin?status=${filter}`,{headers:{authorization:`Bearer ${key()}`}}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load league memberships');setRows(j.data??[])}).catch((e:Error)=>setMessage(e.message))
 useEffect(()=>{void load()},[filter])
 useEffect(()=>{fetch('/api/leagues').then(r=>r.json()).then(j=>setLeagues(j.data??[])).catch(()=>setLeagues([]))},[])
 const review=async(row:Membership,action:string)=>{const role=action==='APPROVE'?window.prompt('Role: OWNER, ADMIN, DATA_MANAGER, MEDIA_MANAGER, SPONSOR_MANAGER or VIEWER',row.role==='VIEWER'?'ADMIN':row.role)??'ADMIN':row.role;const notes=window.prompt('Review notes (optional)',row.reviewNotes??'')??'';const r=await fetch(`/api/league-portal/admin/${row.id}`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${key()}`},body:JSON.stringify({action,role:role.toUpperCase(),notes})});const j=await r.json().catch(()=>({}));setMessage(r.ok?j.message??'Membership updated':j.error??'Update failed');if(r.ok)void load()}
 const sendInvite=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/league-portal/admin/invitations',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key()}`},body:JSON.stringify(invite)});const j=await r.json().catch(()=>({}));if(!r.ok)return setMessage(j.error??'Invitation failed');const url=`${window.location.origin}${j.data.invitePath}`;await navigator.clipboard?.writeText(url);setMessage(`Invitation created and copied: ${url}`);setInvite({...invite,email:''})}
 return <main className="membership-admin"><header><div><span>PLAYFOOTY OPERATIONS</span><h1>League access</h1></div><div><Link to="/admin">Admin home</Link><Link to="/admin/claims">Club access</Link><Link to="/league-portal">League login</Link></div></header>
 <section className="notice-box"><strong>Admin remains the master system.</strong><p>League accounts can be approved for restricted profile access only. Rankings, ladders, results and official statistics remain controlled through Admin.</p></section>
 <section className="invite-box"><div><h2>Invite a league user</h2><p>Create a secure seven-day invitation connected to a role and league.</p></div><form onSubmit={sendInvite}><select value={invite.leagueId} onChange={e=>setInvite({...invite,leagueId:e.target.value})} required><option value="">Select league</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name} — {[l.state,l.association].filter(Boolean).join(' · ')}</option>)}</select><input type="email" placeholder="Email address" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} required/><select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><button>Generate invitation</button></form></section>
 <section className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>PENDING</option><option>ACTIVE</option><option>SUSPENDED</option><option>REVOKED</option><option>ALL</option></select><p>Review league claims and assign the minimum role required.</p></section>{message&&<div className="msg">{message}</div>}
 <section className="list">{rows.map(row=><article key={row.id}><div className="title"><div><small>{row.leaguePosition||row.role}</small><h2>{row.leagueName}</h2></div><b>{row.status}</b></div><dl><div><dt>Applicant</dt><dd>{row.applicantName||row.email}</dd></div><div><dt>Email</dt><dd>{row.email}</dd></div><div><dt>Phone</dt><dd>{row.phone||'Not supplied'}</dd></div><div className="wide"><dt>Verification reason</dt><dd>{row.reason||'Invitation-based membership'}</dd></div></dl><footer>{row.status==='PENDING'&&<><button className="secondary" onClick={()=>review(row,'REJECT')}>Reject</button><button onClick={()=>review(row,'APPROVE')}>Approve membership</button></>}{row.status==='ACTIVE'&&<><button className="secondary" onClick={()=>review(row,'SUSPEND')}>Suspend</button><button className="danger" onClick={()=>review(row,'REVOKE')}>Revoke</button></>}{row.status==='SUSPENDED'&&<><button onClick={()=>review(row,'REACTIVATE')}>Reactivate</button><button className="danger" onClick={()=>review(row,'REVOKE')}>Revoke</button></>}</footer></article>)}{!rows.length&&<div className="empty">No {filter.toLowerCase()} league memberships.</div>}</section>
 <style>{`.membership-admin{min-height:100vh;background:#f5f7fa;color:#172033;padding:28px clamp(14px,4vw,34px) 60px;font-family:Inter,system-ui,sans-serif}.membership-admin>header,.notice-box,.invite-box,.toolbar,.list,.msg{max-width:1100px;margin-left:auto;margin-right:auto}.membership-admin>header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px}.membership-admin header span{color:#2daaf5;font-size:11px;font-weight:950;letter-spacing:.16em}.membership-admin h1{font-size:56px;letter-spacing:-.06em;margin:2px 0}.membership-admin header>div:last-child{display:flex;gap:10px;flex-wrap:wrap}.membership-admin a{color:#172033;text-decoration:none;border:1px solid #e2e7ee;background:#fff;border-radius:999px;padding:11px 15px;font-weight:850}.notice-box{padding:16px 18px;margin-bottom:16px;border:1px solid #b8e5ff;background:#e8f7ff;border-radius:14px}.notice-box p{margin:5px 0 0;color:#526070}.invite-box,.toolbar,.list article,.empty{background:#fff;border:1px solid #e2e7ee;border-radius:16px;box-shadow:0 10px 26px rgba(23,32,51,.06)}.invite-box{padding:20px;margin-bottom:16px}.invite-box h2{margin:0}.invite-box p{color:#68758a}.invite-box form{display:grid;grid-template-columns:2fr 1.4fr 1fr auto;gap:10px}.invite-box input,.invite-box select,.toolbar select{border:1px solid #dce2e8;border-radius:10px;padding:11px;font:inherit}.invite-box button,.list button{border:0;border-radius:999px;background:#2daaf5;padding:12px 16px;font-weight:950;cursor:pointer}.toolbar{display:flex;gap:18px;align-items:center;padding:16px;margin-bottom:15px}.toolbar p{margin:0;color:#68758a}.msg{margin-bottom:15px;padding:13px;background:#e8f7ff;border:1px solid #b8e5ff;border-radius:10px;font-weight:800;overflow-wrap:anywhere}.list{display:grid;gap:14px}.list article,.empty{padding:20px}.title{display:flex;justify-content:space-between}.title small{color:#2daaf5;font-weight:950;text-transform:uppercase}.title h2{margin:4px 0;font-size:28px}.list dl{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.list dl>div{background:#f7f8fb;border-radius:10px;padding:12px}.list .wide{grid-column:1/-1}.list dt{color:#68758a;text-transform:uppercase;font-size:10px;font-weight:900}.list dd{margin:5px 0 0;font-weight:750}.list footer{display:flex;justify-content:flex-end;gap:10px}.list button.secondary{background:#fff;border:1px solid #dce2e8}.list button.danger{background:#e53935;color:#fff}@media(max-width:760px){.membership-admin>header,.toolbar{align-items:stretch;flex-direction:column}.invite-box form{grid-template-columns:1fr}.list dl{grid-template-columns:1fr}.list .wide{grid-column:auto}.list footer{flex-direction:column}.list button{width:100%}}`}</style></main>
}