import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ImagePlus, Newspaper, Search, Trash2, Upload } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Session={access_token:string}
type Asset={id:string;title:string;description:string|null;mediaType:string;status:string;fileUrl:string;contentType:string|null;fileSize:number|null;tags:string[];createdAt:string}
const SESSION_KEY='playfooty.clubPortal.session.v1'
const TYPES=['ALL','PLAYER','MATCH','MILESTONE','TEAM_SELECTION','SPONSOR','CLUB','GENERATED','OTHER']
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read image'));reader.readAsDataURL(file)})}

export default function ClubPortalMedia(){
 const{clubId=''}=useParams();const[current]=useState(()=>session());const[assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState('ALL')
 const headers=useMemo(()=>current?{authorization:`Bearer ${current.access_token}`}:{authorization:''},[current])
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 async function load(){if(!current){setError('Sign in through the Club Portal to continue.');setLoading(false);return}setLoading(true);setError('');try{const params=new URLSearchParams();if(type!=='ALL')params.set('type',type);if(query.trim())params.set('q',query.trim());const payload=await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}?${params}`);setAssets(Array.isArray(payload.data)?payload.data:[])}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load media')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[clubId,type])
 async function upload(file:File){if(file.size>10*1024*1024)return setError('Image must be 10 MB or smaller');setUploading(true);setError('');setMessage('');try{const dataUrl=await fileData(file);const image=new Image();const size=await new Promise<{width:number;height:number}>(resolve=>{image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>resolve({width:0,height:0});image.src=dataUrl});await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl,contentType:file.type,title:file.name.replace(/\.[^.]+$/,''),mediaType:type==='ALL'?'OTHER':type,status:'READY',width:size.width,height:size.height,tags:[]})});setMessage('Media uploaded to the shared library');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to upload media')}finally{setUploading(false)}}
 async function archive(asset:Asset){if(!confirm(`Archive ${asset.title}?`))return;try{await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/${encodeURIComponent(asset.id)}`,{method:'DELETE'});setMessage('Media archived');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to archive media')}}
 return <><Nav/><main className="cm"><header><Link to={`/club-portal/${clubId}`}><ArrowLeft size={17}/>Club portal</Link><span>MEDIA CENTRE</span><h1>Media Library</h1><p>Store reusable player, match, milestone, club and sponsor images for future social graphics and news publishing.</p><label className="upload"><Upload size={18}/>{uploading?'Uploading…':'Upload image'}<input disabled={uploading} type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.currentTarget.value=''}}/></label></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<section className="tools"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')void load()}} placeholder="Search media"/></label><select value={type} onChange={event=>setType(event.target.value)}>{TYPES.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><button onClick={()=>void load()}>Search</button></section>{loading?<div className="state">Loading shared media…</div>:assets.length?<section className="grid">{assets.map(asset=><article key={asset.id}><img src={asset.fileUrl} alt={asset.title}/><div><span>{asset.mediaType.replaceAll('_',' ')}</span><h2>{asset.title}</h2><small>{new Date(asset.createdAt).toLocaleDateString('en-AU')} · {asset.status}</small>{asset.description&&<p>{asset.description}</p>}<div className="asset-actions"><Link to={`/club-portal/${clubId}/media-publish?asset=${encodeURIComponent(asset.id)}`}><Newspaper size={15}/>Create news post</Link><button onClick={()=>void archive(asset)}><Trash2 size={15}/>Archive</button></div></div></article>)}</section>:<section className="empty"><ImagePlus size={42}/><h2>No media uploaded</h2><p>Upload the first club, player or match image. It will be available to authorised club users on every device.</p></section>}</main><Footer/><style>{styles}</style></>
}
const styles=`.cm{min-height:80vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 110px;color:#111318}.cm>*{max-width:1240px;margin-left:auto;margin-right:auto}.cm header{position:relative;padding-right:190px}.cm header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.cm header>span{display:block;margin-top:22px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.cm h1,.cm h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.cm h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.cm header p{max-width:720px;color:#687385}.upload{position:absolute;right:0;bottom:4px;display:flex;align-items:center;gap:8px;padding:12px 16px;border-radius:999px;background:#111318;color:#fff;font-weight:950;text-transform:uppercase;cursor:pointer}.upload input{display:none}.tools{display:grid;grid-template-columns:1fr 220px auto;gap:9px;margin-top:24px}.tools label{display:flex;align-items:center;gap:8px;padding:0 13px;border:1px solid #dce4ea;border-radius:12px;background:#fff}.tools input,.tools select,.tools button{width:100%;padding:12px;border:1px solid #dce4ea;border-radius:12px;background:#fff;font:inherit}.tools label input{border:0;outline:0;padding-left:0}.tools button{width:auto;background:#35b6ff;border:0;font-weight:950}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-top:16px}.grid article{overflow:hidden;border:1px solid #dce4ea;border-radius:16px;background:#fff;box-shadow:0 8px 22px rgba(15,23,42,.05)}.grid img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;background:#e6ebef}.grid article>div{padding:15px}.grid span{color:#0783c9;font-size:9px;font-weight:950;letter-spacing:.12em}.grid h2{margin:5px 0;font-size:28px}.grid small{color:#75808b}.grid p{color:#687385}.asset-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.asset-actions a,.asset-actions button{display:flex;align-items:center;gap:6px;border:0;border-radius:999px;padding:8px 11px;font-weight:900;text-decoration:none}.asset-actions a{background:#dff4ff;color:#086c9f}.asset-actions button{background:#ffe7e7;color:#9c2020}.state,.empty,.alert{margin-top:18px;padding:35px;border-radius:15px;background:#fff;border:1px solid #dce4ea;text-align:center}.empty h2{font-size:34px;margin:12px 0 5px}.empty p{color:#687385}.alert{padding:12px;text-align:left}.alert.error{background:#ffe8e8;color:#9f2020}.alert.success{background:#e3f8ec;color:#167343}@media(max-width:800px){.cm header{padding-right:0}.upload{position:static;width:max-content;margin-top:16px}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.tools{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.cm{padding:18px 9px 100px}}`
