import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Download, Image as ImageIcon, Save, ShieldCheck } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Session={access_token:string}
type Sheet={id:string;roundLabel:string;opponentName:string|null;matchDate:string|null;status:string}
type MatchState={sheetId:string;quarter:number;elapsed:number;runningSince:number|null;homeGoals:number;homeBehinds:number;awayGoals:number;awayBehinds:number;finishedAt?:string|null}
type Club={clubId:string;clubName:string;logoUrl:string|null;primaryColour:string|null;secondaryColour:string|null;leagueName:string|null}
type Deal={id:string;status:string;sponsor:{id:string;name:string;logoUrl:string|null}|null}
type Media={id:string;title:string;mediaType:string;fileUrl:string}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function total(goals:number,behinds:number){return goals*6+behinds}
function safeColour(value:string|null|undefined,fallback:string){return /^#[0-9a-f]{6}$/i.test(value||'')?value!:fallback}
function labelFor(state:MatchState){if(state.finishedAt)return'FULL TIME';if(state.quarter===1)return'QUARTER TIME';if(state.quarter===2)return'HALF TIME';if(state.quarter===3)return'THREE QUARTER TIME';return'FINAL QUARTER'}
async function loadImage(url:string|null){if(!url)return null;return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url})}
function fitCover(ctx:CanvasRenderingContext2D,image:HTMLImageElement,w:number,h:number){const scale=Math.max(w/image.width,h/image.height);const sw=w/scale,sh=h/scale;ctx.drawImage(image,(image.width-sw)/2,(image.height-sh)/2,sw,sh,0,0,w,h)}

export default function ClubPortalMatchGraphic(){
 const{clubId=''}=useParams();const[params]=useSearchParams();const[current]=useState(()=>session());const canvas=useRef<HTMLCanvasElement>(null)
 const[club,setClub]=useState<Club|null>(null),[sheets,setSheets]=useState<Sheet[]>([]),[state,setState]=useState<MatchState|null>(null),[deals,setDeals]=useState<Deal[]>([]),[media,setMedia]=useState<Media[]>([])
 const[sheetId,setSheetId]=useState(params.get('sheetId')||''),[sponsorId,setSponsorId]=useState(''),[photoId,setPhotoId]=useState(''),[breakLabel,setBreakLabel]=useState(''),[generated,setGenerated]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const headers=useMemo(()=>current?{authorization:`Bearer ${current.access_token}`}:{authorization:''},[current]);const sheet=sheets.find(item=>item.id===sheetId)||null;const sponsor=deals.find(item=>item.id===sponsorId)?.sponsor||null;const photo=media.find(item=>item.id===photoId)||null
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),...headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 useEffect(()=>{if(!current){setError('Sign in through the Club Portal to continue.');return}let active=true;Promise.all([request(`/api/club-portal/team-sheets/clubs/${encodeURIComponent(clubId)}/sheets`),fetch(`/api/clubs/${encodeURIComponent(clubId)}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load club');return p}),request(`/api/club-portal/clubs/${encodeURIComponent(clubId)}/sponsors`).catch(()=>({data:[]})),request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}?type=MATCH`).catch(()=>({data:[]}))]).then(([sheetPayload,clubPayload,sponsorPayload,mediaPayload])=>{if(!active)return;const nextSheets=Array.isArray(sheetPayload.data)?sheetPayload.data as Sheet[]:[];setSheets(nextSheets);setSheetId(value=>value||nextSheets.find(item=>item.status==='PUBLISHED')?.id||nextSheets[0]?.id||'');setClub(clubPayload.data||null);const activeDeals=(Array.isArray(sponsorPayload.data)?sponsorPayload.data:[]).filter((deal:Deal)=>['ACTIVE','APPROVED','PAYMENT_COMPLETE'].includes(deal.status));setDeals(activeDeals);setSponsorId(activeDeals[0]?.id||'');setMedia(Array.isArray(mediaPayload.data)?mediaPayload.data:[])}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load Match Day graphic')});return()=>{active=false}},[clubId,current])
 useEffect(()=>{if(!sheetId||!current)return;let active=true;request(`/api/club-portal/match-day/clubs/${encodeURIComponent(clubId)}/sheets/${encodeURIComponent(sheetId)}`).then(payload=>{if(!active)return;const next=payload.data?.state as MatchState|null;setState(next);setBreakLabel(next?labelFor(next):'');setGenerated(false)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load Match Day score')});return()=>{active=false}},[sheetId,current,clubId])
 async function generate(){if(!state||!sheet||!club||!canvas.current)return;setBusy(true);setError('');setMessage('');try{const ctx=canvas.current.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable');const W=1080,H=1350,primary=safeColour(club.primaryColour,'#082f6d'),secondary=safeColour(club.secondaryColour,'#f4b000');canvas.current.width=W;canvas.current.height=H
  const[logo,sponsorLogo,background]=await Promise.all([loadImage(club.logoUrl),loadImage(sponsor?.logoUrl||null),loadImage(photo?.fileUrl||null)])
  if(background){fitCover(ctx,background,W,H);ctx.fillStyle='rgba(4,12,24,.70)';ctx.fillRect(0,0,W,H)}else{const gradient=ctx.createLinearGradient(0,0,W,H);gradient.addColorStop(0,primary);gradient.addColorStop(1,'#061427');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H)}
  ctx.globalAlpha=.13;ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(600,0);ctx.lineTo(W,0);ctx.lineTo(W,520);ctx.closePath();ctx.fill();ctx.globalAlpha=1
  if(logo){const scale=Math.min(165/logo.width,165/logo.height);ctx.drawImage(logo,72,55,logo.width*scale,logo.height*scale)}
  ctx.fillStyle=secondary;ctx.font='900 34px Arial';ctx.textAlign='right';ctx.fillText((breakLabel||labelFor(state)).toUpperCase(),1005,98);ctx.fillStyle='#fff';ctx.font='800 28px Arial';ctx.fillText(sheet.roundLabel.toUpperCase(),1005,140);ctx.textAlign='left'
  ctx.fillStyle='#fff';ctx.font='900 78px Arial';ctx.fillText(club.clubName.toUpperCase(),72,310);ctx.fillStyle=secondary;ctx.font='900 36px Arial';ctx.fillText(`V ${sheet.opponentName||'OPPOSITION'}`.toUpperCase(),74,365)
  ctx.strokeStyle='rgba(255,255,255,.32)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(72,410);ctx.lineTo(1008,410);ctx.stroke()
  const home=total(state.homeGoals,state.homeBehinds),away=total(state.awayGoals,state.awayBehinds)
  drawScore(ctx,club.clubName,state.homeGoals,state.homeBehinds,home,250,610,secondary)
  ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='900 52px Arial';ctx.textAlign='center';ctx.fillText('—',540,738)
  drawScore(ctx,sheet.opponentName||'Opposition',state.awayGoals,state.awayBehinds,away,830,610,secondary)
  ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 44px Arial';ctx.fillText(resultText(home,away,club.clubName,sheet.opponentName||'Opposition'),540,960)
  ctx.fillStyle='rgba(255,255,255,.75)';ctx.font='700 24px Arial';ctx.fillText(`${state.homeGoals}.${state.homeBehinds} (${home})  —  ${state.awayGoals}.${state.awayBehinds} (${away})`,540,1012)
  ctx.textAlign='left';ctx.fillStyle=secondary;ctx.font='900 25px Arial';ctx.fillText((sheet.matchDate?new Date(sheet.matchDate).toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',year:'numeric'}):'MATCH DAY').toUpperCase(),72,1285);ctx.fillStyle='#fff';ctx.font='700 21px Arial';ctx.fillText((club.leagueName||'COMMUNITY FOOTBALL').toUpperCase(),72,1320)
  if(sponsor){ctx.fillStyle='rgba(255,255,255,.96)';ctx.beginPath();ctx.roundRect(790,1200,218,118,14);ctx.fill();if(sponsorLogo){const scale=Math.min(165/sponsorLogo.width,72/sponsorLogo.height);ctx.drawImage(sponsorLogo,816,1223,sponsorLogo.width*scale,sponsorLogo.height*scale)}else{ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='900 22px Arial';ctx.fillText(sponsor.name.toUpperCase(),899,1268)}}
  setGenerated(true);setMessage('Match graphic generated. Review it before saving.')
 }catch(reason){setError(reason instanceof Error?reason.message:'Graphic could not be generated')}finally{setBusy(false)}}
 function download(){if(!canvas.current||!generated)return;const anchor=document.createElement('a');anchor.download=`${club?.clubName||'club'}-${breakLabel||'match-score'}.png`.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');anchor.href=canvas.current.toDataURL('image/png');anchor.click()}
 async function save(){if(!canvas.current||!generated||!sheet||!state)return;setBusy(true);setError('');try{const title=`${sheet.roundLabel} ${breakLabel||labelFor(state)}`;const payload=await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl:canvas.current.toDataURL('image/png'),contentType:'image/png',title,description:`${club?.clubName||'Club'} ${breakLabel||labelFor(state)} score${sheet.opponentName?` v ${sheet.opponentName}`:''}`,mediaType:'GENERATED',status:'READY',width:1080,height:1350,tags:['match score',breakLabel||labelFor(state),sheet.roundLabel].filter(Boolean),sponsorId:sponsor?.id||null,sourceEntityType:'MATCH_DAY',sourceEntityId:sheet.id})});setMessage(payload.message||'Graphic saved to the Media Centre.')}catch(reason){setError(reason instanceof Error?reason.message:'Graphic could not be saved')}finally{setBusy(false)}}
 if(error&&!club)return <><Nav/><main className="mg-state"><ShieldCheck/><h1>Match graphic unavailable</h1><p>{error}</p><Link to={`/club-portal/${clubId}/coaching`}>Return to coaching</Link></main><Footer/></>
 return <><Nav/><main className="mg"><header><Link to={`/club-portal/${clubId}/coaching`}><ArrowLeft size={17}/>Coaching</Link><span>MEDIA CENTRE</span><h1>Match graphic</h1><p>Create a score graphic from the shared Match Day record.</p></header>{error&&<div className="mg-alert error">{error}</div>}{message&&<div className="mg-alert success">{message}</div>}<section className="mg-layout"><aside><label>Match<select value={sheetId} onChange={event=>setSheetId(event.target.value)}><option value="">Select match</option>{sheets.map(item=><option key={item.id} value={item.id}>{item.roundLabel} · {item.opponentName||'Opponent TBC'}</option>)}</select></label><label>Graphic label<select value={breakLabel} onChange={event=>{setBreakLabel(event.target.value);setGenerated(false)}}><option>QUARTER TIME</option><option>HALF TIME</option><option>THREE QUARTER TIME</option><option>FULL TIME</option><option>FINAL RESULT</option></select></label><label>Match photo<select value={photoId} onChange={event=>{setPhotoId(event.target.value);setGenerated(false)}}><option value="">Club-colour background</option>{media.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Sponsor<select value={sponsorId} onChange={event=>{setSponsorId(event.target.value);setGenerated(false)}}><option value="">No sponsor</option>{deals.map(deal=><option value={deal.id} key={deal.id}>{deal.sponsor?.name||'Sponsor'}</option>)}</select></label><button className="generate" disabled={!state||!club||busy} onClick={()=>void generate()}><ImageIcon size={17}/>{busy?'Working…':'Generate graphic'}</button><button disabled={!generated||busy} onClick={download}><Download size={17}/>Download PNG</button><button disabled={!generated||busy} onClick={()=>void save()}><Save size={17}/>Save to Media Centre</button><small>The displayed score comes directly from the shared Match Day record.</small></aside><article><canvas ref={canvas} aria-label="Match score graphic preview"/><div className={!generated?'placeholder':''}>{!generated&&(state?'Choose the graphic options and generate the preview.':'No Match Day record exists for this team sheet yet.')}</div></article></section></main><Footer/><style>{styles}</style></>
}
function drawScore(ctx:CanvasRenderingContext2D,name:string,goals:number,behinds:number,totalScore:number,x:number,y:number,accent:string){ctx.textAlign='center';ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='800 28px Arial';ctx.fillText(name.toUpperCase().slice(0,28),x,y);ctx.fillStyle='#fff';ctx.font='900 142px Arial';ctx.fillText(String(totalScore),x,y+160);ctx.fillStyle=accent;ctx.font='900 34px Arial';ctx.fillText(`${goals}.${behinds}`,x,y+215)}
function resultText(home:number,away:number,club:string,opponent:string){if(home===away)return'DRAW';return home>away?`${club.toUpperCase()} BY ${home-away}`:`${opponent.toUpperCase()} BY ${away-home}`}
const styles=`.mg,.mg-state{min-height:78vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 110px;color:#111318}.mg>*{max-width:1220px;margin-left:auto;margin-right:auto}.mg header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.mg header>span{display:block;margin-top:20px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.mg h1,.mg-state h1{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mg h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.mg header p{color:#687385}.mg-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:16px;margin-top:20px}.mg-layout aside,.mg-layout article{border:1px solid #dce4ea;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.05)}.mg-layout aside{padding:18px;align-self:start;display:grid;gap:11px}.mg label{display:grid;gap:6px;color:#687385;font-size:10px;font-weight:900;text-transform:uppercase}.mg select{width:100%;padding:11px;border:1px solid #ccd6df;border-radius:9px;background:#fff}.mg button{display:flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:9px;padding:12px;background:#111318;color:#fff;font-weight:900;text-transform:uppercase;cursor:pointer}.mg button.generate{background:#2daaf5;color:#061019}.mg button:disabled{opacity:.42;cursor:not-allowed}.mg aside small{color:#74808d;line-height:1.45}.mg-layout article{position:relative;padding:14px;min-height:520px;display:grid;place-items:center}.mg canvas{display:block;width:min(100%,520px);height:auto;background:#07172b;box-shadow:0 15px 34px rgba(0,0,0,.2)}.mg-layout article>div.placeholder{position:absolute;color:#687385;text-align:center}.mg-alert{margin-top:14px;padding:12px 14px;border-radius:10px;font-weight:800}.mg-alert.error{background:#ffe9e9;color:#a51d16}.mg-alert.success{background:#e2f8ec;color:#126c40}.mg-state{display:grid;place-items:center;align-content:center;text-align:center}.mg-state a{color:#111;font-weight:900}@media(max-width:820px){.mg-layout{grid-template-columns:1fr}.mg-layout aside{grid-template-columns:1fr 1fr}.mg-layout aside small{grid-column:1/-1}}@media(max-width:560px){.mg{padding:18px 9px 105px}.mg-layout aside{grid-template-columns:1fr}.mg-layout article{padding:8px;min-height:420px}}`
