import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Download, Image as ImageIcon, Save, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Session={access_token:string}
type Player={clubPlayerId:string;positionCode:string;playerName:string;jumperNumber:number|null}
type Sheet={id:string;roundLabel:string;opponentName:string|null;matchDate:string|null;status:string;grade:string;players:Player[]}
type Club={clubId:string;clubName:string;logoUrl:string|null;primaryColour:string|null;secondaryColour:string|null;leagueName:string|null}
type Deal={id:string;status:string;bannerPosition:string|null;sponsor:{id:string;name:string;logoUrl:string|null}|null}
const SESSION_KEY='playfooty.clubPortal.session.v1'
const ROWS=[['BP_LEFT','FB','BP_RIGHT'],['HBF_LEFT','CHB','HBF_RIGHT'],['WING_LEFT','CENTRE','WING_RIGHT'],['RUCK','RUCK_ROVER','ROVER'],['HFF_LEFT','CHF','HFF_RIGHT'],['FP_LEFT','FF','FP_RIGHT']]
const BENCH=['INTERCHANGE_1','INTERCHANGE_2','INTERCHANGE_3','INTERCHANGE_4']
const EMERGENCY=['EMERGENCY_1','EMERGENCY_2','EMERGENCY_3']
const ROW_LABELS=['B','HB','C','R','HF','F']
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function safeColour(value:string|null|undefined,fallback:string){return /^#[0-9a-f]{6}$/i.test(value||'')?value!:fallback}
function dateLabel(value:string|null){if(!value)return'Date TBC';const date=new Date(value);return Number.isNaN(date.getTime())?'Date TBC':date.toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).toUpperCase()}
function shortName(name:string){const parts=name.trim().split(/\s+/);return parts.length>1?`${parts[0]}\n${parts.slice(1).join(' ')}`:name}
async function loadImage(url:string|null){if(!url)return null;return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url})}
function playerAt(sheet:Sheet,code:string){return sheet.players.find(player=>player.positionCode===code)||null}

export default function ClubPortalTeamGraphic(){
 const{clubId=''}=useParams();const[current]=useState(()=>session());const canvas=useRef<HTMLCanvasElement>(null)
 const[club,setClub]=useState<Club|null>(null),[sheets,setSheets]=useState<Sheet[]>([]),[deals,setDeals]=useState<Deal[]>([])
 const[sheetId,setSheetId]=useState(''),[sponsorId,setSponsorId]=useState(''),[generated,setGenerated]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const headers=useMemo(()=>current?{authorization:`Bearer ${current.access_token}`}:{authorization:''},[current]);const sheet=sheets.find(item=>item.id===sheetId)||null;const sponsor=deals.find(item=>item.id===sponsorId)?.sponsor||null
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),...headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 useEffect(()=>{if(!current){setError('Sign in through the Club Portal to continue.');return}let active=true;Promise.all([request(`/api/club-portal/team-sheets/clubs/${encodeURIComponent(clubId)}/sheets`),fetch(`/api/clubs/${encodeURIComponent(clubId)}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load club');return p}),request(`/api/club-portal/clubs/${encodeURIComponent(clubId)}/sponsors`).catch(()=>({data:[]}))]).then(([sheetPayload,clubPayload,sponsorPayload])=>{if(!active)return;const nextSheets=(Array.isArray(sheetPayload.data)?sheetPayload.data:[]).filter((item:Sheet)=>item.status==='PUBLISHED'||item.status==='DRAFT');setSheets(nextSheets);setSheetId(nextSheets.find((item:Sheet)=>item.status==='PUBLISHED')?.id||nextSheets[0]?.id||'');setClub(clubPayload.data||null);const activeDeals=(Array.isArray(sponsorPayload.data)?sponsorPayload.data:[]).filter((deal:Deal)=>['ACTIVE','APPROVED','PAYMENT_COMPLETE'].includes(deal.status));setDeals(activeDeals);setSponsorId(activeDeals[0]?.id||'')}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load team graphic')});return()=>{active=false}},[clubId,current])
 async function generate(){if(!sheet||!club||!canvas.current)return;setBusy(true);setError('');setMessage('');try{const ctx=canvas.current.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable');const W=1080,H=1350,primary=safeColour(club.primaryColour,'#082f6d'),secondary=safeColour(club.secondaryColour,'#f4b000');canvas.current.width=W;canvas.current.height=H
  const gradient=ctx.createLinearGradient(0,0,W,H);gradient.addColorStop(0,primary);gradient.addColorStop(1,'#061427');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H)
  ctx.globalAlpha=.12;ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(W*.52,0);ctx.lineTo(W,0);ctx.lineTo(W,H*.42);ctx.closePath();ctx.fill();ctx.globalAlpha=1
  const[logo,sponsorLogo]=await Promise.all([loadImage(club.logoUrl),loadImage(sponsor?.logoUrl||null)])
  if(logo){const scale=Math.min(150/logo.width,150/logo.height);ctx.drawImage(logo,75,55,logo.width*scale,logo.height*scale)}
  ctx.textAlign='left';ctx.fillStyle='#fff';ctx.font='900 58px Arial';ctx.fillText('TEAM',75,245);ctx.fillStyle=secondary;ctx.font='900 104px Arial';ctx.fillText('SELECTION',75,330)
  ctx.fillStyle='#fff';ctx.font='700 30px Arial';ctx.fillText(sheet.roundLabel.toUpperCase(),760,95);ctx.font='900 34px Arial';ctx.fillText(`V ${sheet.opponentName||'OPPONENT TBC'}`.toUpperCase(),760,143)
  ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(75,370);ctx.lineTo(1005,370);ctx.stroke()
  const startY=425,rowH=126,colX=[250,535,820]
  ROWS.forEach((row,rowIndex)=>{const y=startY+rowIndex*rowH;ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='900 26px Arial';ctx.fillText(ROW_LABELS[rowIndex],75,y+42);row.forEach((code,col)=>drawPlayer(ctx,playerAt(sheet,code),colX[col],y,secondary));ctx.strokeStyle='rgba(255,255,255,.22)';ctx.beginPath();ctx.moveTo(145,y+88);ctx.lineTo(1005,y+88);ctx.stroke()})
  let y=startY+ROWS.length*rowH+6;ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='900 24px Arial';ctx.fillText('INT',75,y+35);BENCH.forEach((code,index)=>drawPlayer(ctx,playerAt(sheet,code),250+(index%3)*285,y+Math.floor(index/3)*88,secondary));y+=180
  ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillText('EMG',75,y+35);EMERGENCY.forEach((code,index)=>drawPlayer(ctx,playerAt(sheet,code),250+index*285,y,secondary))
  ctx.fillStyle=secondary;ctx.font='900 25px Arial';ctx.fillText(dateLabel(sheet.matchDate),75,1280);ctx.fillStyle='#fff';ctx.font='700 21px Arial';ctx.fillText((club.leagueName||sheet.grade||'COMMUNITY FOOTBALL').toUpperCase(),75,1315)
  if(sponsor){ctx.fillStyle='rgba(255,255,255,.95)';roundRect(ctx,805,1210,200,105,12);ctx.fill();if(sponsorLogo){const scale=Math.min(150/sponsorLogo.width,62/sponsorLogo.height);ctx.drawImage(sponsorLogo,830,1228,sponsorLogo.width*scale,sponsorLogo.height*scale)}else{ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='900 22px Arial';ctx.fillText(sponsor.name.toUpperCase(),905,1269);ctx.textAlign='left'}}
  setGenerated(true);setMessage('Team selection graphic generated. Review it before saving.')
 }catch(reason){setError(reason instanceof Error?reason.message:'Graphic could not be generated')}finally{setBusy(false)}}
 function download(){if(!canvas.current||!generated)return;const anchor=document.createElement('a');anchor.download=`${club?.clubName||'club'}-${sheet?.roundLabel||'team-selection'}.png`.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');anchor.href=canvas.current.toDataURL('image/png');anchor.click()}
 async function save(){if(!canvas.current||!generated||!sheet)return;setBusy(true);setError('');try{const dataUrl=canvas.current.toDataURL('image/png');const payload=await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl,contentType:'image/png',title:`${sheet.roundLabel} team selection`,description:`${club?.clubName||'Club'} team selection${sheet.opponentName?` v ${sheet.opponentName}`:''}`,mediaType:'TEAM_SELECTION',status:'READY',width:1080,height:1350,tags:['team selection',sheet.roundLabel,sheet.opponentName||''].filter(Boolean),sponsorId:sponsor?.id||null,sourceEntityType:'TEAM_SHEET',sourceEntityId:sheet.id})});setMessage(payload.message||'Graphic saved to the Media Centre.')}catch(reason){setError(reason instanceof Error?reason.message:'Graphic could not be saved')}finally{setBusy(false)}}
 if(error&&!club)return <><Nav/><main className="tg-state"><ShieldCheck/><h1>Team graphic unavailable</h1><p>{error}</p><Link to={`/club-portal/${clubId}/team-selection`}>Return to team selection</Link></main><Footer/></>
 return <><Nav/><main className="tg"><header><Link to={`/club-portal/${clubId}/team-selection`}><ArrowLeft size={17}/>Team selection</Link><span>MEDIA CENTRE</span><h1>Team graphic</h1><p>Create an accurate social graphic from the club’s existing team sheet.</p></header>{error&&<div className="tg-alert error">{error}</div>}{message&&<div className="tg-alert success">{message}</div>}<section className="tg-layout"><aside><label>Team sheet<select value={sheetId} onChange={event=>{setSheetId(event.target.value);setGenerated(false)}}><option value="">Select team</option>{sheets.map(item=><option key={item.id} value={item.id}>{item.roundLabel} · {item.status}</option>)}</select></label><label>Sponsor<select value={sponsorId} onChange={event=>{setSponsorId(event.target.value);setGenerated(false)}}><option value="">No sponsor</option>{deals.map(deal=><option value={deal.id} key={deal.id}>{deal.sponsor?.name||'Sponsor'}</option>)}</select></label><button className="generate" disabled={!sheet||!club||busy} onClick={()=>void generate()}><ImageIcon size={17}/>{busy?'Working…':'Generate graphic'}</button><button disabled={!generated||busy} onClick={download}><Download size={17}/>Download PNG</button><button disabled={!generated||busy} onClick={()=>void save()}><Save size={17}/>Save to Media Centre</button><small>The graphic uses structured team data. Player names and positions are not generated by AI.</small></aside><article><canvas ref={canvas} aria-label="Team selection graphic preview"/><div className={!generated?'placeholder':''}>{!generated&&'Choose a team sheet and generate the preview.'}</div></article></section></main><Footer/><style>{styles}</style></>
}
function drawPlayer(ctx:CanvasRenderingContext2D,player:Player|null,x:number,y:number,accent:string){ctx.textAlign='center';if(!player){ctx.fillStyle='rgba(255,255,255,.35)';ctx.font='700 22px Arial';ctx.fillText('—',x,y+30);ctx.textAlign='left';return}const lines=shortName(player.playerName).split('\n');ctx.fillStyle='rgba(255,255,255,.88)';ctx.font='500 22px Arial';ctx.fillText(lines[0].toUpperCase(),x,y+20);ctx.fillStyle='#fff';ctx.font='900 25px Arial';ctx.fillText((lines[1]||lines[0]).toUpperCase(),x,y+50);if(player.jumperNumber){ctx.fillStyle=accent;ctx.font='900 17px Arial';ctx.fillText(`#${player.jumperNumber}`,x,y+74)}ctx.textAlign='left'}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
const styles=`.tg,.tg-state{min-height:78vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 110px;color:#111318}.tg>*{max-width:1220px;margin-left:auto;margin-right:auto}.tg header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.tg header>span{display:block;margin-top:20px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.tg h1,.tg-state h1{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.tg h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.tg header p{color:#687385}.tg-layout{display:grid;grid-template-columns:290px minmax(0,1fr);gap:16px;margin-top:20px}.tg-layout aside,.tg-layout article{border:1px solid #dce4ea;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.05)}.tg-layout aside{padding:18px;align-self:start;display:grid;gap:11px}.tg label{display:grid;gap:6px;color:#687385;font-size:10px;font-weight:900;text-transform:uppercase}.tg select{width:100%;padding:11px;border:1px solid #ccd6df;border-radius:9px;background:#fff}.tg button{display:flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:9px;padding:12px;background:#111318;color:#fff;font-weight:900;text-transform:uppercase;cursor:pointer}.tg button.generate{background:#2daaf5;color:#061019}.tg button:disabled{opacity:.42;cursor:not-allowed}.tg aside small{color:#74808d;line-height:1.45}.tg-layout article{position:relative;padding:14px;min-height:520px;display:grid;place-items:center}.tg canvas{display:block;width:min(100%,520px);height:auto;background:#07172b;box-shadow:0 15px 34px rgba(0,0,0,.2)}.tg-layout article>div.placeholder{position:absolute;color:#687385;text-align:center}.tg-alert{margin-top:14px;padding:12px 14px;border-radius:10px;font-weight:800}.tg-alert.error{background:#ffe9e9;color:#a51d16}.tg-alert.success{background:#e2f8ec;color:#126c40}.tg-state{display:grid;place-items:center;align-content:center;text-align:center}.tg-state a{color:#111;font-weight:900}@media(max-width:820px){.tg-layout{grid-template-columns:1fr}.tg-layout aside{grid-template-columns:1fr 1fr}.tg-layout aside small{grid-column:1/-1}}@media(max-width:560px){.tg{padding:18px 9px 105px}.tg-layout aside{grid-template-columns:1fr}.tg-layout article{padding:8px;min-height:420px}}`
