import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, Clipboard, Newspaper, Send, Save } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Session={access_token:string}
type Prepared={asset:{id:string;title:string;mediaType:string;fileUrl:string;sponsorId:string|null};club:{id:string;name:string};suggestion:{title:string;summary:string;body:string;caption:string}}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}

export default function ClubPortalMediaPublish(){
 const{clubId=''}=useParams();const[params]=useSearchParams();const assetId=params.get('asset')||'';const[current]=useState(()=>session());const[data,setData]=useState<Prepared|null>(null);const[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[body,setBody]=useState(''),[caption,setCaption]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[articleId,setArticleId]=useState('')
 const headers=useMemo(()=>current?{authorization:`Bearer ${current.access_token}`}:{authorization:''},[current])
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 useEffect(()=>{if(!current){setError('Sign in through the Club Portal to continue.');setLoading(false);return}if(!assetId){setError('Choose a Media Centre asset first.');setLoading(false);return}let active=true;request(`/api/club-portal/media-publishing/clubs/${encodeURIComponent(clubId)}/assets/${encodeURIComponent(assetId)}`).then(payload=>{if(!active)return;const prepared=payload.data as Prepared;setData(prepared);setTitle(prepared.suggestion.title);setSummary(prepared.suggestion.summary);setBody(prepared.suggestion.body);setCaption(prepared.suggestion.caption)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to prepare news post')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[assetId,clubId,current])
 async function publish(status:'DRAFT'|'APPROVED'){if(!data)return;setBusy(true);setError('');setMessage('');try{const payload=await request(`/api/club-portal/media-publishing/clubs/${encodeURIComponent(clubId)}/assets/${encodeURIComponent(assetId)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,summary,body,caption,status})});setArticleId(payload.data?.articleId||'');setMessage(payload.message||'News article created')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create news article')}finally{setBusy(false)}}
 async function copyCaption(){try{await navigator.clipboard.writeText(caption);setMessage('Social caption copied')}catch{setError('Unable to copy caption on this device')}}
 if(loading)return <><Nav/><main className="mp-state">Preparing news post…</main><Footer/></>
 if(error&&!data)return <><Nav/><main className="mp-state"><Newspaper size={40}/><h1>Publishing unavailable</h1><p>{error}</p><Link to={`/club-portal/${clubId}/media`}>Return to Media Centre</Link></main><Footer/></>
 return <><Nav/><main className="mp"><header><Link to={`/club-portal/${clubId}/media`}><ArrowLeft size={17}/>Media Centre</Link><span>NEWS PUBLISHING</span><h1>Publish graphic</h1><p>Turn the saved graphic into a club news story and an editable social caption.</p></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success"><CheckCircle2 size={17}/>{message}</div>}<section className="layout"><aside>{data&&<><img src={data.asset.fileUrl} alt={data.asset.title}/><span>{data.asset.mediaType.replaceAll('_',' ')}</span><h2>{data.asset.title}</h2><p>The original Media Centre asset remains unchanged.</p></>}</aside><article><label>Headline<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={220}/></label><label>Summary<textarea value={summary} onChange={event=>setSummary(event.target.value)} maxLength={1000}/></label><label>Article body<textarea className="body" value={body} onChange={event=>setBody(event.target.value)} maxLength={20000}/></label><label>Social caption<textarea className="caption" value={caption} onChange={event=>setCaption(event.target.value)} maxLength={4000}/></label><div className="actions"><button onClick={()=>void copyCaption()} disabled={busy}><Clipboard size={17}/>Copy caption</button><button onClick={()=>void publish('DRAFT')} disabled={busy||!title.trim()||!summary.trim()||!body.trim()}><Save size={17}/>Save news draft</button><button className="submit" onClick={()=>void publish('APPROVED')} disabled={busy||!title.trim()||!summary.trim()||!body.trim()}><Send size={17}/>Submit to news feed</button></div>{articleId&&<Link className="news-link" to={`/club-portal/${clubId}/news`}>Open club newsroom</Link>}<small>Submitted stories use the existing PlayFooty approval workflow. This does not bypass news moderation.</small></article></section></main><Footer/><style>{styles}</style></>
}
const styles=`.mp,.mp-state{min-height:78vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 110px;color:#111318}.mp>*{max-width:1180px;margin-left:auto;margin-right:auto}.mp header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.mp header>span{display:block;margin-top:21px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.mp h1,.mp h2,.mp-state h1{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mp h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.mp header p{color:#687385}.layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:15px;margin-top:20px}.layout>aside,.layout>article{background:#fff;border:1px solid #dce4ea;border-radius:16px;box-shadow:0 8px 24px rgba(15,23,42,.05)}.layout>aside{padding:14px;align-self:start}.layout>aside img{display:block;width:100%;border-radius:11px;background:#e6ebef}.layout>aside span{display:block;margin-top:13px;color:#0783c9;font-size:9px;font-weight:950;letter-spacing:.13em}.layout>aside h2{font-size:31px;margin:5px 0}.layout>aside p{color:#687385}.layout>article{padding:20px;display:grid;gap:13px}.layout label{display:grid;gap:6px;color:#687385;font-size:10px;font-weight:950;text-transform:uppercase}.layout input,.layout textarea{width:100%;box-sizing:border-box;border:1px solid #ccd6df;border-radius:9px;padding:12px;background:#fff;color:#111;font:inherit}.layout textarea{min-height:90px;resize:vertical}.layout textarea.body{min-height:190px}.layout textarea.caption{min-height:130px}.actions{display:flex;flex-wrap:wrap;gap:8px}.actions button{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:9px;padding:12px 14px;background:#e5edf2;color:#111;font-weight:950;text-transform:uppercase;cursor:pointer}.actions button:nth-child(2){background:#2daaf5}.actions button.submit{background:#21c879}.actions button:disabled{opacity:.45}.news-link{width:max-content;color:#111;font-weight:900}.layout article small{color:#78828c;line-height:1.45}.alert{display:flex;align-items:center;gap:8px;margin-top:14px;padding:12px 14px;border-radius:10px;font-weight:850}.alert.error{background:#ffe7e7;color:#a21f1f}.alert.success{background:#e0f8eb;color:#126f40}.mp-state{display:grid;place-items:center;align-content:center;text-align:center}.mp-state a{color:#111;font-weight:900}@media(max-width:780px){.layout{grid-template-columns:1fr}.layout>aside img{max-height:520px;object-fit:contain}}@media(max-width:560px){.mp{padding:18px 9px 105px}.actions{display:grid}.actions button{width:100%}}`
