import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Download, Image as ImageIcon, Save, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'
import { ensureFreshPortalSession, type PortalAuthSession } from '../lib/portalAuth'

type Player={clubPlayerId:string;positionCode:string;playerName:string;jumperNumber:number|null}
type Sheet={id:string;roundLabel:string;opponentName:string|null;matchDate:string|null;status:string;grade:string;players:Player[]}
type Club={clubId:string;clubName:string;logoUrl:string|null;primaryColour:string|null;secondaryColour:string|null;leagueName:string|null}
type Deal={id:string;status:string;sponsor:{id:string;name:string;logoUrl:string|null}|null}
const SESSION_KEY='playfooty.clubPortal.session.v1'
const ROWS=[['BP_LEFT','FB','BP_RIGHT'],['HBF_LEFT','CHB','HBF_RIGHT'],['WING_LEFT','CENTRE','WING_RIGHT'],['RUCK','RUCK_ROVER','ROVER'],['HFF_LEFT','CHF','HFF_RIGHT'],['FP_LEFT','FF','FP_RIGHT']]
const ROW_LABELS=['B','HB','C','R','HF','F']
const BENCH=['INTERCHANGE_1','INTERCHANGE_2','INTERCHANGE_3','INTERCHANGE_4']
const EMG=['EMERGENCY_1','EMERGENCY_2','EMERGENCY_3']
function readSession():PortalAuthSession|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function saveSession(value:PortalAuthSession){localStorage.setItem(SESSION_KEY,JSON.stringify(value))}
function safeColour(value:string|null|undefined,fallback:string){return /^#[0-9a-f]{6}$/i.test(value||'')?value!:fallback}
function playerAt(sheet:Sheet,code:string){return sheet.players.find(player=>player.positionCode===code)||null}
function dateLabel(value:string|null){if(!value)return'DATE TBC';const date=new Date(value);return Number.isNaN(date.getTime())?'DATE TBC':date.toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).toUpperCase()}
async function loadImage(url:string|null){if(!url)return null;return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url})}
function fitImage(ctx:CanvasRenderingContext2D,image:HTMLImageElement,w:number,h:number){const scale=Math.max(w/image.width,h/image.height),dw=image.width*scale,dh=image.height*scale;ctx.drawImage(image,(w-dw)/2,(h-dh)/2,dw,dh)}

export default function ClubPortalAiTeamGraphic(){
 const{clubId=''}=useParams();const canvas=useRef<HTMLCanvasElement>(null)
 const[session,setSession]=useState<PortalAuthSession|null>(null),[club,setClub]=useState<Club|null>(null),[sheets,setSheets]=useState<Sheet[]>([]),[deals,setDeals]=useState<Deal[]>([])
 const[sheetId,setSheetId]=useState(''),[sponsorId,setSponsorId]=useState(''),[style,setStyle]=useState('premium broadcast'),[generated,setGenerated]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const sheet=sheets.find(item=>item.id===sheetId)||null,sponsor=deals.find(item=>item.id===sponsorId)?.sponsor||null
 const headers=useMemo(()=>session?{authorization:`Bearer ${session.access_token}`}:{authorization:''},[session])
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...(options.headers||{}),...headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 useEffect(()=>{let active=true;(async()=>{try{const stored=readSession();const fresh=await ensureFreshPortalSession(stored);if(!fresh)throw new Error('Sign in through the Club Portal to continue.');if(!fresh.club_accounts?.some(account=>account.clubId===clubId))throw new Error('Your login is not linked to this club. Return to the Club Portal and choose the correct club.');saveSession(fresh);if(active)setSession(fresh)}catch(reason){if(active)setError(reason instanceof Error?reason.message:'Unable to verify club access')}})();return()=>{active=false}},[clubId])
 useEffect(()=>{if(!session)return;let active=true;Promise.all([request(`/api/club-portal/team-sheets/clubs/${encodeURIComponent(clubId)}/sheets`),fetch(`/api/clubs/${encodeURIComponent(clubId)}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load club');return p}),request(`/api/club-portal/clubs/${encodeURIComponent(clubId)}/sponsors`).catch(()=>({data:[]}))]).then(([sheetPayload,clubPayload,sponsorPayload])=>{if(!active)return;const list=(Array.isArray(sheetPayload.data)?sheetPayload.data:[]) as Sheet[];setSheets(list);setSheetId(list.find(item=>item.status==='PUBLISHED')?.id||list[0]?.id||'');setClub(clubPayload.data||null);const activeDeals=((Array.isArray(sponsorPayload.data)?sponsorPayload.data:[]) as Deal[]).filter(deal=>['ACTIVE','APPROVED','PAYMENT_COMPLETE'].includes(deal.status));setDeals(activeDeals);setSponsorId(activeDeals[0]?.id||'')}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load team graphic')});return()=>{active=false}},[session,clubId])
 async function generate(){if(!sheet||!club||!canvas.current)return;setBusy(true);setError('');setMessage('Generating AI design…');try{const bgPayload=await request(`/api/club-portal/ai-graphics/clubs/${encodeURIComponent(clubId)}/team-background`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clubName:club.clubName,opponentName:sheet.opponentName,primaryColour:club.primaryColour,secondaryColour:club.secondaryColour,style})});const background=await loadImage(bgPayload.data?.dataUrl||null);if(!background)throw new Error('The AI background could not be loaded');const ctx=canvas.current.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable');const W=1080,H=1350,primary=safeColour(club.primaryColour,'#082f6d'),secondary=safeColour(club.secondaryColour,'#f4b000');canvas.current.width=W;canvas.current.height=H;fitImage(ctx,background,W,H);ctx.fillStyle='rgba(2,10,24,.58)';ctx.fillRect(0,0,W,H);const gradient=ctx.createLinearGradient(0,0,0,H);gradient.addColorStop(0,'rgba(0,0,0,.05)');gradient.addColorStop(.32,'rgba(0,0,0,.38)');gradient.addColorStop(1,'rgba(0,0,0,.78)');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H)
 const[logo,sponsorLogo]=await Promise.all([loadImage(club.logoUrl),loadImage(sponsor?.logoUrl||null)]);if(logo){const s=Math.min(130/logo.width,130/logo.height);ctx.drawImage(logo,72,55,logo.width*s,logo.height*s)}ctx.textAlign='left';ctx.fillStyle='#fff';ctx.font='900 58px Arial';ctx.fillText('TEAM',72,245);ctx.fillStyle=secondary;ctx.font='900 102px Arial';ctx.fillText('SELECTION',72,325);ctx.fillStyle='#fff';ctx.textAlign='right';ctx.font='800 27px Arial';ctx.fillText(sheet.roundLabel.toUpperCase(),1000,88);ctx.font='900 32px Arial';ctx.fillText(`V ${sheet.opponentName||'OPPONENT TBC'}`.toUpperCase(),1000,132);ctx.textAlign='left';ctx.strokeStyle='rgba(255,255,255,.4)';ctx.beginPath();ctx.moveTo(72,360);ctx.lineTo(1008,360);ctx.stroke();const startY=405,rowH=118,colX=[265,545,825];ROWS.forEach((row,index)=>{const y=startY+index*rowH;ctx.fillStyle=secondary;ctx.font='900 24px Arial';ctx.fillText(ROW_LABELS[index],72,y+38);row.forEach((code,col)=>drawPlayer(ctx,playerAt(sheet,code),colX[col],y));ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.moveTo(145,y+82);ctx.lineTo(1008,y+82);ctx.stroke()});let y=startY+ROWS.length*rowH+8;ctx.fillStyle=secondary;ctx.font='900 22px Arial';ctx.fillText('INT',72,y+30);BENCH.forEach((code,index)=>drawPlayer(ctx,playerAt(sheet,code),245+(index%3)*285,y+Math.floor(index/3)*72));y+=155;ctx.fillStyle=secondary;ctx.fillText('EMG',72,y+30);EMG.forEach((code,index)=>drawPlayer(ctx,playerAt(sheet,code),245+index*285,y));ctx.fillStyle=secondary;ctx.font='900 23px Arial';ctx.fillText(dateLabel(sheet.matchDate),72,1284);ctx.fillStyle='#fff';ctx.font='700 19px Arial';ctx.fillText((club.leagueName||sheet.grade||'COMMUNITY FOOTBALL').toUpperCase(),72,1318);if(sponsor){ctx.fillStyle='rgba(255,255,255,.96)';ctx.roundRect(810,1210,198,105,14);ctx.fill();if(sponsorLogo){const s=Math.min(150/sponsorLogo.width,62/sponsorLogo.height);ctx.drawImage(sponsorLogo,834,1229,sponsorLogo.width*s,sponsorLogo.height*s)}else{ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='900 20px Arial';ctx.fillText(sponsor.name.toUpperCase(),909,1268);ctx.textAlign='left'}}setGenerated(true);setMessage('AI team graphic generated. Review it before saving.') }catch(reason){setError(reason instanceof Error?reason.message:'Unable to generate AI graphic');setMessage('')}finally{setBusy(false)}}
 function download(){if(!canvas.current||!generated)return;const a=document.createElement('a');a.download=`${club?.clubName||'club'}-${sheet?.roundLabel||'team-selection'}.png`.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');a.href=canvas.current.toDataURL('image/png');a.click()}
 async function save(){if(!canvas.current||!generated||!sheet)return;setBusy(true);setError('');try{await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl:canvas.current.toDataURL('image/png'),contentType:'image/png',title:`${sheet.roundLabel} AI team selection`,description:`${club?.clubName||'Club'} team selection${sheet.opponentName?` v ${sheet.opponentName}`:''}`,mediaType:'TEAM_SELECTION',status:'READY',width:1080,height:1350,tags:['team selection','AI design',sheet.roundLabel,sheet.opponentName||''].filter(Boolean),sponsorId:sponsor?.id||null,sourceEntityType:'TEAM_SHEET',sourceEntityId:sheet.id})});setMessage('Graphic saved to the Media Centre.')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save graphic')}finally{setBusy(false)}}
 if(error&&!club)return <><Nav/><main className="aitg-state"><ShieldCheck/><h1>Team graphic unavailable</h1><p>{error}</p><Link to="/club-portal">Return to Club Portal</Link></main><Footer/></>
 return <><Nav/><main className="aitg"><header><Link to={`/club-portal/${clubId}/team-selection`}><ArrowLeft size={17}/>Team selection</Link><span>AI MEDIA STUDIO</span><h1>Team graphic</h1><p>AI creates the visual design. PlayFooty adds the exact team data, logos and sponsor details.</p></header>{error&&<div className="aitg-alert error">{error}</div>}{message&&<div className="aitg-alert success">{message}</div>}<section className="aitg-layout"><aside><label>Team sheet<select value={sheetId} onChange={e=>{setSheetId(e.target.value);setGenerated(false)}}><option value="">Select team</option>{sheets.map(item=><option key={item.id} value={item.id}>{item.roundLabel} · {item.status}</option>)}</select></label><label>Design style<select value={style} onChange={e=>{setStyle(e.target.value);setGenerated(false)}}><option value="premium broadcast">Premium broadcast</option><option value="dramatic stadium">Dramatic stadium</option><option value="modern geometric">Modern geometric</option><option value="heritage football poster">Heritage football poster</option></select></label><label>Sponsor<select value={sponsorId} onChange={e=>{setSponsorId(e.target.value);setGenerated(false)}}><option value="">No sponsor</option>{deals.map(deal=><option key={deal.id} value={deal.id}>{deal.sponsor?.name||'Sponsor'}</option>)}</select></label><button className="generate" disabled={!sheet||!club||busy} onClick={()=>void generate()}><ImageIcon size={17}/>{busy?'Generating…':'Generate with AI'}</button><button disabled={!generated||busy} onClick={download}><Download size={17}/>Download PNG</button><button disabled={!generated||busy} onClick={()=>void save()}><Save size={17}/>Save to Media Centre</button><small>AI designs the background only. Player names and positions are rendered from the saved team sheet.</small></aside><article><canvas ref={canvas}/>{!generated&&<div>Choose a team and press Generate with AI.</div>}</article></section></main><Footer/><style>{styles}</style></>
}
function drawPlayer(ctx:CanvasRenderingContext2D,player:Player|null,x:number,y:number){ctx.textAlign='center';if(!player){ctx.fillStyle='rgba(255,255,255,.4)';ctx.font='700 21px Arial';ctx.fillText('—',x,y+28);ctx.textAlign='left';return}const parts=player.playerName.trim().split(/\s+/);ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='600 20px Arial';ctx.fillText((parts[0]||'').toUpperCase(),x,y+18);ctx.fillStyle='#fff';ctx.font='900 24px Arial';ctx.fillText((parts.slice(1).join(' ')||parts[0]||'').toUpperCase(),x,y+46);ctx.textAlign='left'}
const styles=`.aitg,.aitg-state{min-height:78vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 110px;color:#111318}.aitg>*{max-width:1220px;margin-left:auto;margin-right:auto}.aitg header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.aitg header>span{display:block;margin-top:20px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.aitg h1,.aitg-state h1{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.aitg h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.aitg header p{color:#687385}.aitg-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:16px;margin-top:20px}.aitg-layout aside,.aitg-layout article{border:1px solid #dce4ea;border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.05)}.aitg-layout aside{padding:18px;align-self:start;display:grid;gap:11px}.aitg label{display:grid;gap:6px;color:#687385;font-size:10px;font-weight:900;text-transform:uppercase}.aitg select{width:100%;padding:11px;border:1px solid #ccd6df;border-radius:9px;background:#fff}.aitg button{display:flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:9px;padding:12px;background:#111318;color:#fff;font-weight:900;text-transform:uppercase}.aitg button.generate{background:#2daaf5;color:#061019}.aitg button:disabled{opacity:.42}.aitg aside small{color:#74808d;line-height:1.45}.aitg-layout article{position:relative;padding:14px;min-height:520px;display:grid;place-items:center}.aitg canvas{display:block;width:min(100%,520px);height:auto;background:#07172b;box-shadow:0 15px 34px rgba(0,0,0,.2)}.aitg-layout article>div{position:absolute;color:#687385;text-align:center}.aitg-alert{margin-top:14px;padding:12px 14px;border-radius:10px;font-weight:800}.aitg-alert.error{background:#ffe9e9;color:#a51d16}.aitg-alert.success{background:#e2f8ec;color:#126c40}.aitg-state{display:grid;place-items:center;align-content:center;text-align:center}.aitg-state a{font-weight:900;color:#111}@media(max-width:820px){.aitg-layout{grid-template-columns:1fr}.aitg-layout aside{grid-template-columns:1fr 1fr}.aitg-layout aside small{grid-column:1/-1}}@media(max-width:560px){.aitg{padding:18px 9px 105px}.aitg-layout aside{grid-template-columns:1fr}.aitg-layout article{padding:8px;min-height:420px}}`
