import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ShieldCheck } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'
import ClubCoachingCommandCentre from '../components/club/ClubCoachingCommandCentre'
import { TeamLogo } from '../components/rankings/bits'

type Session={access_token:string}
type TeamSelection={id:string;roundLabel:string;opponentName:string|null;matchDate:string|null;status:string;playerCount?:number;players?:Array<unknown>}
type Dashboard={club:{id:string;name:string;logoUrl:string|null;primaryColour:string|null;leagueName:string|null;season:string|null;grade:string|null};membership:{role:string};teamSelection:TeamSelection|null}
type Availability={players:Array<{status:string|null;reason:string|null}>}
type Fixture={id:string;round?:string|number|null;matchDate?:string|null;venue?:string|null;homeClubId?:string|null;awayClubId?:string|null;homeClubName?:string|null;awayClubName?:string|null;homeName?:string|null;awayName?:string|null}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw):null}catch{return null}}
function dateLabel(value:string|null|undefined){if(!value)return 'Date to be confirmed';const date=new Date(value);return Number.isNaN(date.getTime())?'Date to be confirmed':date.toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short'})}
function timeLabel(value:string|null|undefined){if(!value)return 'Time to be confirmed';const date=new Date(value);return Number.isNaN(date.getTime())?'Time to be confirmed':date.toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}
function roundLabel(value:string|number|null|undefined){if(value==null||String(value).trim()==='')return 'Round not set';const label=String(value).trim();return /^round\b/i.test(label)?label:`Round ${label}`}
function normalise(value:string|null|undefined){return String(value??'').trim().toLowerCase().replace(/^round\s+/,'').replace(/[^a-z0-9]+/g,' ')}
function dayKey(value:string|null|undefined){if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10)}
function roleLabel(value:string){return value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}

export default function CoachingAppHome(){
 const{clubId=''}=useParams();const[data,setData]=useState<Dashboard|null>(null);const[availability,setAvailability]=useState<Availability|null>(null);const[fixtures,setFixtures]=useState<Fixture[]>([]);const[sheets,setSheets]=useState<TeamSelection[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{const current=session();if(!current){setError('Sign in through the Club Portal to continue.');setLoading(false);return}let live=true;Promise.all([
  fetch(`/api/club-portal/clubs/${encodeURIComponent(clubId)}/dashboard`,{headers:{authorization:`Bearer ${current.access_token}`}}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load coaching home');return p.data as Dashboard}),
  fetch(`/api/club-portal/availability/clubs/${encodeURIComponent(clubId)}/overview`,{headers:{authorization:`Bearer ${current.access_token}`}}).then(r=>r.ok?r.json():{data:null}).then(p=>p.data as Availability|null).catch(()=>null),
  fetch(`/api/clubs/${encodeURIComponent(clubId)}/fixtures?upcoming=true`).then(r=>r.ok?r.json():{data:[]}).then(p=>Array.isArray(p.data)?p.data as Fixture[]:[]).catch(()=>[]),
  fetch(`/api/club-portal/team-sheets/clubs/${encodeURIComponent(clubId)}/sheets`,{headers:{authorization:`Bearer ${current.access_token}`}}).then(r=>r.ok?r.json():{data:[]}).then(p=>Array.isArray(p.data)?p.data as TeamSelection[]:[]).catch(()=>[])
 ]).then(([dashboard,availabilityData,fixtureData,sheetData])=>{if(!live)return;setData(dashboard);setAvailability(availabilityData);setFixtures(fixtureData);setSheets(sheetData)}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Unable to load coaching home')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[clubId])
 const counts=useMemo(()=>{const rows=availability?.players||[];return{available:rows.filter(p=>p.status==='AVAILABLE').length,total:rows.length}},[availability])
 if(loading)return <><Nav/><main className="cah-state">Loading coaching…</main><Footer/></>
 if(error||!data)return <><Nav/><main className="cah-state"><ShieldCheck size={42}/><h1>Coaching unavailable</h1><p>{error||'This workspace is unavailable.'}</p><Link to="/club-portal">Return to Club Portal</Link></main><Footer/></>
 const accent=data.club.primaryColour||'#42b8ff';const nextFixture=[...fixtures].filter(row=>{if(!row.matchDate)return true;const time=new Date(row.matchDate).getTime();return Number.isNaN(time)||time>=Date.now()-21600000}).sort((a,b)=>{const av=a.matchDate?new Date(a.matchDate).getTime():Number.MAX_SAFE_INTEGER;const bv=b.matchDate?new Date(b.matchDate).getTime():Number.MAX_SAFE_INTEGER;return av-bv})[0]||null;const homeName=nextFixture?.homeClubName||nextFixture?.homeName||'Home';const awayName=nextFixture?.awayClubName||nextFixture?.awayName||'Away';const isHome=nextFixture?.homeClubId===clubId||homeName.toLowerCase()===data.club.name.toLowerCase();const fixtureOpponent=nextFixture?(isHome?awayName:homeName):null;const fixtureRound=normalise(nextFixture?.round==null?null:String(nextFixture.round));const fixtureDate=dayKey(nextFixture?.matchDate);const sheet=nextFixture?sheets.find(item=>{
  const sameRound=fixtureRound&&normalise(item.roundLabel)===fixtureRound
  const sameDate=fixtureDate&&dayKey(item.matchDate)===fixtureDate
  const sameOpponent=fixtureOpponent&&normalise(item.opponentName)===normalise(fixtureOpponent)
  return Boolean((sameRound&&sameOpponent)||(sameDate&&sameOpponent)||(sameRound&&sameDate))
 })||null:data.teamSelection;const opponentName=fixtureOpponent||sheet?.opponentName||null;const playerCount=sheet?.playerCount??sheet?.players?.length??0
 return <><Nav/><main className="cah" style={{'--accent':accent} as React.CSSProperties}>
  <header className="cah-head"><div className="cah-identity"><TeamLogo name={data.club.name} src={data.club.logoUrl||undefined} size={62}/><div><span>Coaching</span><h1>{data.club.name}</h1><p>{[data.club.leagueName,data.club.season,data.club.grade,roleLabel(data.membership.role)].filter(Boolean).join(' · ')}</p></div></div><Link to={`/club-portal/${clubId}`} aria-label="Club dashboard"><ShieldCheck size={22}/></Link></header>
  <section className="cah-week"><div className="cah-week-copy"><span>This week</span><h2>{opponentName?`v ${opponentName}`:'Next match'}</h2><p>{roundLabel(nextFixture?.round||sheet?.roundLabel)} · {dateLabel(nextFixture?.matchDate||sheet?.matchDate)} · {timeLabel(nextFixture?.matchDate||sheet?.matchDate)}</p>{nextFixture?.venue&&<p className="cah-venue">{nextFixture.venue}</p>}<div className="cah-status"><b>{sheet?.status==='PUBLISHED'?'Team published':sheet?'Team in progress':'Team not started'}</b><small>{sheet?`${playerCount} players selected`:'Open Team to get started'}</small></div></div><div className="cah-ring"><strong>{counts.total?Math.round((counts.available/counts.total)*100):0}%</strong><span>available</span></div></section>
  <ClubCoachingCommandCentre clubId={clubId}/>
 </main><Footer/><style>{styles}</style></>
}
const styles=`
.cah{min-height:82vh;background:#f7f8fa;color:#0b0d10;padding:18px max(16px,calc((100vw - 760px)/2)) 110px;font-family:Barlow,Inter,Arial,sans-serif}.cah-head{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:12px 2px 20px}.cah-identity{display:flex;align-items:center;gap:13px;min-width:0}.cah-identity span,.cah-week-copy>span{color:var(--accent);font-size:10px;font-weight:950;letter-spacing:.14em;text-transform:uppercase}.cah-identity h1{margin:3px 0 2px;font-family:'Bebas Neue',Impact,sans-serif;font-size:32px;line-height:1;text-transform:uppercase}.cah-identity p{margin:0;color:#7a828b;font-size:11px}.cah-head>a{width:46px;height:46px;border-radius:50%;display:grid;place-items:center;background:#e8ebee;color:#111;text-decoration:none}.cah-week{display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;padding:23px;border-radius:22px;background:linear-gradient(135deg,#080b10,#15354b);color:#fff;box-shadow:0 12px 30px rgba(10,22,34,.18)}.cah-week h2{margin:7px 0 4px;font-family:'Bebas Neue',Impact,sans-serif;font-size:42px;line-height:.9;text-transform:uppercase}.cah-week p{margin:0;color:#c3ced7}.cah-week .cah-venue{margin-top:7px;color:#fff;font-size:13px;font-weight:800}.cah-status{margin-top:18px}.cah-status b,.cah-status small{display:block}.cah-status b{font-size:13px}.cah-status small{margin-top:3px;color:#9fb0bd}.cah-ring{width:104px;height:104px;border-radius:50%;display:grid;place-content:center;text-align:center;background:radial-gradient(circle,#0c1620 50%,transparent 52%),conic-gradient(var(--accent) 0 72%,rgba(255,255,255,.18) 72%)}.cah-ring strong{font-family:'Bebas Neue',Impact,sans-serif;font-size:30px}.cah-ring span{font-size:9px;text-transform:uppercase;color:#aebcc8}.cah-state{min-height:70vh;display:grid;place-content:center;text-align:center;background:#f7f8fa;padding:30px}.cah-state h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:42px;margin:10px 0}.cah-state a{color:#111;font-weight:900}@media(max-width:560px){.cah{padding:12px 13px 105px}.cah-week{padding:20px}.cah-ring{width:88px;height:88px}.cah-identity p{max-width:240px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
`
