import { useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, LoaderCircle, LockKeyhole } from 'lucide-react'

type Invite={email:string;clubName:string;clubLogoUrl:string|null;preset:string|null;permissions:string[];expiresAt:string}
type Session={access_token:string;refresh_token:string;expires_at?:number;expires_in?:number;user?:{id?:string;email?:string|null};club_accounts?:unknown[]}
const SESSION_KEY='playfooty.clubPortal.session.v1',CLUB_KEY='playfooty.coachApp.club.v1'
export default function CoachAppJoin(){
 const token=new URLSearchParams(location.search).get('invite')??''
 const[invite,setInvite]=useState<Invite|null>(null),[mode,setMode]=useState<'signup'|'signin'>('signup'),[password,setPassword]=useState(''),[loading,setLoading]=useState(true),[joining,setJoining]=useState(false),[error,setError]=useState('')
 useEffect(()=>{void fetch(`/api/portal-auth/club-invite/${encodeURIComponent(token)}`).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to open invitation');setInvite(p.data)}).catch(e=>setError(e instanceof Error?e.message:'Unable to open invitation')).finally(()=>setLoading(false))},[token])
 async function join(e:React.FormEvent){e.preventDefault();if(!invite)return;setJoining(true);setError('');try{const r=await fetch(`/api/portal-auth/club-invite/${encodeURIComponent(token)}/accept`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:invite.email,password,mode})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to join club');const session=p as Session;localStorage.setItem(SESSION_KEY,JSON.stringify(session));if(p.accepted_club?.clubId)localStorage.setItem(CLUB_KEY,p.accepted_club.clubId);location.replace('/coach-app')}catch(e){setError(e instanceof Error?e.message:'Unable to join club')}finally{setJoining(false)}}
 if(loading)return <main className="join-load"><LoaderCircle/><b>Opening your invitation…</b><style>{styles}</style></main>
 return <main className="join"><style>{styles}</style><section className="join-card">{invite?.clubLogoUrl?<img src={invite.clubLogoUrl} alt=""/>:<div className="join-logo">PF</div>}<span>PlayFooty Club App</span><h1>{invite?`Join ${invite.clubName}`:'Invitation unavailable'}</h1>{invite&&<><p>You have been invited as <b>{(invite.preset??'Custom access').replaceAll('_',' ')}</b>. Create or use your PlayFooty login and you’ll go straight to the pages you are allowed to use.</p><div className="join-email"><LockKeyhole/><span><small>Invited email</small><b>{invite.email}</b></span></div><div className="join-tabs"><button className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Create account</button><button className={mode==='signin'?'active':''} onClick={()=>setMode('signin')}>I already have an account</button></div><form onSubmit={join}><label>{mode==='signup'?'Create a password':'Your password'}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete={mode==='signup'?'new-password':'current-password'} required/></label>{error&&<div className="join-error">{error}</div>}<button disabled={joining}>{joining?<><LoaderCircle/> Joining…</>:<>{mode==='signup'?'Create account and join':'Sign in and join'} <ArrowRight/></>}</button></form><ul><li><CheckCircle2/> One secure step</li><li><CheckCircle2/> Automatic sign-in</li><li><CheckCircle2/> Only your approved access</li></ul></>}{!invite&&<div className="join-error">{error||'This invitation is invalid or has expired.'}</div>}</section></main>
}
const styles=`.join,.join *{box-sizing:border-box}.join,.join-load{min-height:100dvh;background:#07131d;color:#fff;font-family:Barlow,Inter,Arial,sans-serif;display:grid;place-items:center;padding:22px}.join-load{gap:14px;align-content:center}.join-load svg,.join form button svg{animation:spin .8s linear infinite;color:#42b8ff}.join-load b{font-size:20px}.join-card{width:min(520px,100%);padding:28px;border:1px solid #234252;border-radius:24px;background:#0d2130;box-shadow:0 28px 80px rgba(0,0,0,.35)}.join-card>img,.join-logo{width:82px;height:82px;display:grid;place-items:center;margin:0 auto 18px;border-radius:18px;background:#fff;object-fit:contain;color:#07131d;font-weight:1000}.join-card>span{display:block;color:#42b8ff;text-align:center;text-transform:uppercase;font-size:11px;font-weight:950;letter-spacing:.16em}.join h1{margin:7px 0 10px;text-align:center;font-family:'Bebas Neue',Impact,sans-serif;font-size:48px;line-height:.95;text-transform:uppercase}.join-card>p{margin:0 auto 20px;text-align:center;color:#b9cbd7;line-height:1.5}.join-email{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid #28495d;border-radius:14px;background:#081923}.join-email svg{color:#42b8ff}.join-email span,.join-email small,.join-email b{display:block}.join-email small{color:#7893a4;text-transform:uppercase;font-weight:900}.join-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0}.join-tabs button{min-height:45px;border:1px solid #31566c;border-radius:11px;background:transparent;color:#a9bfcc;font-weight:900}.join-tabs button.active{background:#42b8ff;color:#07131d;border-color:#42b8ff}.join form{display:grid;gap:12px}.join label{display:grid;gap:7px;font-size:12px;font-weight:900;text-transform:uppercase}.join input{min-height:52px;padding:0 14px;border:1px solid #41657a;border-radius:12px;background:#06111a;color:#fff;font:inherit;font-size:17px}.join form>button{min-height:54px;display:flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:12px;background:#42b8ff;color:#07131d;font-weight:1000;font-size:16px}.join form>button svg{width:19px;color:inherit}.join-error{padding:12px;border-radius:11px;background:#401923;color:#ffbec8}.join ul{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0 0;padding:0;list-style:none}.join li{display:flex;align-items:center;justify-content:center;gap:5px;color:#96afbd;text-align:center;font-size:11px}.join li svg{width:15px;color:#37d58a}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:560px){.join{padding:12px}.join-card{padding:22px 17px}.join h1{font-size:41px}.join ul{grid-template-columns:1fr}}`
