import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Archive, ImagePlus, Save, ShieldCheck } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Item={id:string;url:string;caption:string|null;credit:string|null;altText:string|null;usage:string;sortOrder:number;archivedAt:string|null}
type Payload={items:Item[];membership:{role:string}}
type Session={access_token:string}
const KEY='playfooty.leaguePortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function LeaguePortalMedia(){
 const{leagueId=''}=useParams();const[data,setData]=useState<Payload|null>(null);const[selected,setSelected]=useState<Item|null>(null);const[caption,setCaption]=useState('');const[credit,setCredit]=useState('');const[altText,setAltText]=useState('');const[usage,setUsage]=useState('GALLERY');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 async function request(path:string,options:RequestInit={}){const current=session();if(!current)throw new Error('Sign in through the League Portal to continue.');const response=await fetch(path,{...options,headers:{...(options.headers??{}),authorization:`Bearer ${current.access_token}`}});const payload=await response.json().catch(()=>({})) as{data?:unknown;message?:string;error?:string};if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 async function load(){setLoading(true);try{const payload=await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/media`);setData(payload.data as Payload)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load media')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[leagueId])
 function choose(item:Item|null){setSelected(item);setCaption(item?.caption??'');setCredit(item?.credit??'');setAltText(item?.altText??'');setUsage(item?.usage??'GALLERY');setMessage('');setError('')}
 async function upload(file:File){if(file.size>10*1024*1024)return setError('Image must be 10 MB or smaller.');setSaving(true);setError('');try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read image'));reader.readAsDataURL(file)});const payload=await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/media`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl,contentType:file.type,caption,credit,altText,usage})});setMessage(payload.message||'Media uploaded');await load();choose(null)}catch(reason){setError(reason instanceof Error?reason.message:'Upload failed')}finally{setSaving(false)}}
 async function save(){if(!selected)return;setSaving(true);setError('');try{await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/media/${encodeURIComponent(selected.id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({caption,credit,altText,sortOrder:selected.sortOrder})});if(usage!==selected.usage)await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/media/${encodeURIComponent(selected.id)}/use`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({usage})});setMessage('Media details saved');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save media')}finally{setSaving(false)}}
 async function archive(){if(!selected||!confirm('Archive this image from the league media library?'))return;setSaving(true);try{await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/media/${encodeURIComponent(selected.id)}`,{method:'DELETE'});setSelected(null);setMessage('Media archived');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to archive media')}finally{setSaving(false)}}
 const canManage=data&&['OWNER','ADMIN','MEDIA_MANAGER'].includes(data.membership.role)
 return <><Nav/><main className="lpm"><header><Link to={`/league-portal/${leagueId}`}><ArrowLeft size={16}/> Dashboard</Link><span>LEAGUE PORTAL</span><h1>Photos and media</h1><p>Manage one connected media library for league galleries and profile imagery.</p></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}{loading?<div className="state">Loading league media…</div>:data?<div className="layout"><aside><button className="new" onClick={()=>choose(null)}>+ Upload media</button>{data.items.map(item=><button key={item.id} className={selected?.id===item.id?'active':''} onClick={()=>choose(item)}><img src={item.url} alt=""/><span><strong>{item.caption||'Untitled image'}</strong><small>{item.usage.replaceAll('_',' ')}{item.archivedAt?' · Archived':''}</small></span></button>)}</aside><section className="editor">{selected?<img className="preview" src={selected.url} alt={selected.altText||''}/>:<div className="upload"><ImagePlus size={36}/><strong>Upload league image</strong><span>PNG, JPG or WEBP · maximum 10 MB</span></div>}<div className="fields"><label>Caption<input disabled={!canManage} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>Credit<input disabled={!canManage} value={credit} onChange={e=>setCredit(e.target.value)}/></label><label>Image description<textarea disabled={!canManage} value={altText} onChange={e=>setAltText(e.target.value)}/></label><label>Use<select disabled={!canManage} value={usage} onChange={e=>setUsage(e.target.value)}><option value="GALLERY">League gallery</option><option value="PROFILE">League profile image</option><option value="HEADER">League header image</option></select></label></div>{canManage&&!selected&&<label className="picker"><ImagePlus size={16}/> Choose image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label>}{canManage&&selected&&<div className="actions"><button onClick={()=>void save()} disabled={saving}><Save size={16}/> Save changes</button><button className="danger" onClick={()=>void archive()} disabled={saving}><Archive size={16}/> Archive</button></div>}{!canManage&&<div className="locked"><ShieldCheck size={20}/> Your role has view-only access to league media.</div>}</section></div>:null}</main><Footer/><style>{styles}</style></>
}
const styles=`.lpm{min-height:75vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 60px;color:#111318}.lpm>*{max-width:1180px;margin-left:auto;margin-right:auto}.lpm header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.lpm header span{display:block;color:#0783c9;font-size:10px;font-weight:900;letter-spacing:.15em;margin-top:24px}.lpm h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:clamp(4rem,8vw,7rem);line-height:.84;text-transform:uppercase;margin:7px 0}.lpm header p{color:#687385}.layout{display:grid;grid-template-columns:310px 1fr;gap:16px;margin-top:22px}.layout aside,.editor{background:#fff;border:1px solid #dce3e9;border-radius:16px;padding:16px}.layout aside{display:grid;gap:8px;align-self:start}.layout aside button{display:grid;grid-template-columns:52px 1fr;gap:10px;align-items:center;border:0;border-radius:10px;padding:9px;text-align:left;background:#f4f7f9}.layout aside button.active{outline:2px solid #35aef2;background:#e8f7ff}.layout aside button.new{display:block;background:#111;color:#fff;text-align:center;font-weight:900}.layout aside img{width:52px;height:52px;object-fit:cover;border-radius:8px}.layout aside strong,.layout aside small{display:block}.layout aside small{color:#687385;margin-top:3px}.preview{width:100%;max-height:420px;object-fit:contain;background:#f5f7f8;border-radius:12px}.upload{display:grid;place-items:center;gap:7px;padding:60px 20px;background:#f5f7f8;border-radius:12px;color:#687385}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.fields label{display:grid;gap:6px;font-size:10px;font-weight:900;text-transform:uppercase}.fields textarea{min-height:90px}.fields input,.fields textarea,.fields select{box-sizing:border-box;width:100%;padding:11px;border:1px solid #ccd6df;border-radius:8px;font:inherit}.picker,.actions button{display:inline-flex;align-items:center;gap:7px;margin-top:16px;background:#111;color:#fff;border-radius:9px;padding:11px 14px;font-weight:900}.picker input{display:none}.actions{display:flex;gap:8px}.actions button{border:0;margin-top:16px}.actions .danger{background:#ffe4e4;color:#992626}.locked{display:flex;gap:8px;margin-top:16px;padding:12px;background:#edf4f8;border-radius:9px}.alert{padding:12px;border-radius:9px;margin-top:12px}.alert.error{background:#ffe8e8;color:#922}.alert.success{background:#e2f8e9;color:#176b3d}.state{padding:70px;text-align:center;color:#687385}@media(max-width:780px){.layout{grid-template-columns:1fr}.fields{grid-template-columns:1fr}}`
