import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ExternalLink, Save, ShieldCheck } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Session={access_token:string}
type LeagueProfile={id:string;name:string;shortName?:string|null;logoUrl?:string|null;description?:string|null;websiteUrl?:string|null;facebookUrl?:string|null;instagramUrl?:string|null;contactEmail?:string|null;contactPhone?:string|null;state:string}
type Membership={role:string;status:string}
const SESSION_KEY='playfooty.leaguePortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function LeaguePortalProfile(){
 const{leagueId=''}=useParams();const[league,setLeague]=useState<LeagueProfile|null>(null);const[membership,setMembership]=useState<Membership|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 const request=async(path:string,options:RequestInit={})=>{const current=session();if(!current)throw new Error('Sign in through the League Portal to continue');const response=await fetch(path,{...options,headers:{...(options.headers??{}),authorization:`Bearer ${current.access_token}`}});const payload=await response.json().catch(()=>({})) as {data?:any;message?:string;error?:string};if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 const load=async()=>{setLoading(true);setError('');try{const payload=await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/profile`);setLeague(payload.data.league);setMembership(payload.data.membership)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load league profile')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[leagueId])
 const set=(field:keyof LeagueProfile,value:string)=>setLeague(current=>current?{...current,[field]:value}:current)
 const canEdit=membership?.role==='OWNER'||membership?.role==='ADMIN'||membership?.role==='MEDIA_MANAGER'
 const save=async()=>{if(!league||!canEdit)return;setSaving(true);setMessage('');setError('');try{const payload=await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/profile`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({description:league.description??'',websiteUrl:league.websiteUrl??'',facebookUrl:league.facebookUrl??'',instagramUrl:league.instagramUrl??'',contactEmail:league.contactEmail??'',contactPhone:league.contactPhone??'',logoUrl:league.logoUrl??''})});setMessage(payload.message||'League profile saved')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save league profile')}finally{setSaving(false)}}
 if(loading)return <><Nav/><main className="lpp-state">Loading league profile…</main><Footer/></>
 if(error&&!league)return <><Nav/><main className="lpp-state"><ShieldCheck size={38}/><h1>Profile access required</h1><p>{error}</p><Link to="/league-portal">Return to League Portal</Link></main><Footer/></>
 return <><Nav/><main className="lpp"><header><div><Link to={`/league-portal/${leagueId}`}><ArrowLeft size={16}/> Dashboard</Link><span>League profile</span><h1>{league?.name}</h1><p>{league?.state} · {membership?.role.replaceAll('_',' ')}</p></div><div className="brand">{league?.logoUrl?<img src={league.logoUrl} alt={`${league.name} logo`}/>:<ShieldCheck size={42}/>}<Link to={`/league/${leagueId}`}>Preview public profile <ExternalLink size={15}/></Link></div></header>{message&&<div className="message">{message}</div>}{error&&<div className="error">{error}</div>}<section className="locked"><ShieldCheck size={22}/><div><strong>Protected league identity</strong><p>League name, state, canonical IDs, PlayHQ connections, rankings, ladders, results and statistics remain controlled by PlayFooty Admin.</p></div></section>{league&&<><div className="grid"><Panel title="Public profile"><TextArea label="League description" value={league.description} onChange={value=>set('description',value)} disabled={!canEdit}/><Input label="League logo URL" value={league.logoUrl} onChange={value=>set('logoUrl',value)} disabled={!canEdit}/></Panel><Panel title="Contact details"><Input label="Public contact email" value={league.contactEmail} onChange={value=>set('contactEmail',value)} disabled={!canEdit}/><Input label="Public contact phone" value={league.contactPhone} onChange={value=>set('contactPhone',value)} disabled={!canEdit}/></Panel><Panel title="Website and social links"><Input label="Website" value={league.websiteUrl} onChange={value=>set('websiteUrl',value)} disabled={!canEdit}/><Input label="Facebook" value={league.facebookUrl} onChange={value=>set('facebookUrl',value)} disabled={!canEdit}/><Input label="Instagram" value={league.instagramUrl} onChange={value=>set('instagramUrl',value)} disabled={!canEdit}/></Panel><section className="panel access"><h2>Your access</h2><dl><div><dt>Role</dt><dd>{membership?.role.replaceAll('_',' ')}</dd></div><div><dt>Status</dt><dd>{membership?.status}</dd></div><div><dt>Editing</dt><dd>{canEdit?'Profile editing enabled':'View only'}</dd></div></dl><p>Only Owners, Admins and Media Managers can update public league profile fields.</p></section></div>{canEdit&&<button className="save" disabled={saving} onClick={()=>void save()}><Save size={18}/>{saving?'Saving…':'Save league profile'}</button>}</>}</main><Footer/><style>{styles}</style></>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Input({label,value,onChange,disabled}:{label:string;value?:string|null;onChange:(value:string)=>void;disabled:boolean}){return <label>{label}<input value={value??''} onChange={event=>onChange(event.target.value)} disabled={disabled}/></label>}
function TextArea({label,value,onChange,disabled}:{label:string;value?:string|null;onChange:(value:string)=>void;disabled:boolean}){return <label>{label}<textarea value={value??''} onChange={event=>onChange(event.target.value)} disabled={disabled}/></label>}
const styles=`.lpp,.lpp-state{min-height:75vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 60px;color:#111318}.lpp>*{max-width:1180px;margin-left:auto;margin-right:auto}.lpp>header{display:flex;justify-content:space-between;align-items:center;gap:20px;background:#050505;color:#fff;border-radius:18px;padding:25px}.lpp header a{color:#8dd7ff;text-decoration:none;display:inline-flex;align-items:center;gap:6px;font-weight:850}.lpp header span{display:block;color:#42b8ff;font-size:10px;font-weight:950;text-transform:uppercase;letter-spacing:.15em;margin-top:12px}.lpp h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:clamp(3rem,7vw,5rem);text-transform:uppercase;line-height:.85;margin:5px 0}.lpp header p{color:#cbd5df;margin:0}.brand{display:grid;justify-items:end;gap:10px}.brand>img,.brand>svg{width:82px;height:82px;object-fit:contain;border-radius:16px;background:#fff;padding:7px;box-sizing:border-box;color:#111}.locked,.panel{background:#fff;border:1px solid #dce4ea;border-radius:14px;padding:19px}.locked{display:flex;gap:12px;align-items:start;margin-top:15px}.locked p,.access p{margin:4px 0;color:#687385;line-height:1.55}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:14px}.panel{display:grid;gap:12px;align-content:start}.panel h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase;font-size:32px;margin:0 0 4px}.panel label{display:grid;gap:6px;font-size:11px;font-weight:900;text-transform:uppercase;color:#687385}.panel input,.panel textarea{width:100%;box-sizing:border-box;border:1px solid #cdd7df;border-radius:9px;padding:12px;font:inherit;color:#111}.panel textarea{min-height:170px;resize:vertical}.panel input:disabled,.panel textarea:disabled{background:#f2f4f6;color:#687385}.access dl{display:grid;gap:10px;margin:0}.access dl>div{display:flex;justify-content:space-between;gap:12px;padding:10px;background:#f6f8fa;border-radius:9px}.access dt{color:#687385;font-size:10px;font-weight:900;text-transform:uppercase}.access dd{margin:0;font-weight:900}.save{display:flex;align-items:center;justify-content:center;gap:8px;width:min(340px,100%);margin:18px auto;border:0;border-radius:10px;padding:14px;background:#21c879;color:#092116;font-weight:950;text-transform:uppercase}.message,.error{padding:12px;border-radius:10px;margin-top:12px}.message{background:#ddf7e9;color:#12643a}.error{background:#fff0f0;color:#a51c1c}.lpp-state{display:grid;place-content:center;text-align:center}.lpp-state h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:52px;margin:10px}.lpp-state a{color:#111;font-weight:900}@media(max-width:760px){.lpp>header{align-items:flex-start;flex-direction:column}.brand{justify-items:start}.grid{grid-template-columns:1fr}}`
