import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ExternalLink, ShieldCheck } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type AuthSession={access_token:string;user?:{email?:string|null}}
type DashboardData={league:{id:string;name:string;logoUrl?:string|null;state:string};membership:{role:string;status:string}}
const SESSION_KEY='playfooty.leaguePortal.session.v1'
function readSession():AuthSession|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as AuthSession:null}catch{return null}}

export default function LeaguePortalDashboard(){
 const{leagueId=''}=useParams();const[data,setData]=useState<DashboardData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{const session=readSession();if(!session){setError('Sign in through the League Portal to access this league.');setLoading(false);return}let live=true;void fetch(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}`,{headers:{authorization:`Bearer ${session.access_token}`}}).then(async response=>{const payload=await response.json().catch(()=>({})) as {data?:DashboardData;error?:string};if(!response.ok)throw new Error(payload.error||'Unable to load league access');if(live)setData(payload.data??null)}).catch(reason=>{if(live)setError(reason instanceof Error?reason.message:'Unable to load league access')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[leagueId])
 const canManageMedia=data&&['OWNER','ADMIN','MEDIA_MANAGER'].includes(data.membership.role)
 const canManageSponsors=data&&['OWNER','ADMIN','SPONSOR_MANAGER'].includes(data.membership.role)
 const canManageUsers=data?.membership.role==='OWNER'
 return <><Nav/><main className="league-dashboard"><div className="league-dashboard-shell"><Link className="back" to="/league-portal"><ArrowLeft size={16}/> Back to League Portal</Link>{loading&&<section className="card"><p>Checking your league access…</p></section>}{error&&<section className="card error"><h1>League access unavailable</h1><p>{error}</p><Link to="/league-portal">Open League Portal</Link></section>}{data&&<><header className="hero"><div className="logo">{data.league.logoUrl?<img src={data.league.logoUrl} alt={`${data.league.name} logo`}/>:<ShieldCheck size={42}/>}</div><div><span>{data.membership.role.replaceAll('_',' ')} · {data.membership.status}</span><h1>{data.league.name}</h1><p>{data.league.state}</p></div></header><section className="card"><h2>League Portal access is active</h2><p>This protected dashboard confirms your membership and league connection. Official rankings, league strength ratings, ladders, match results, player statistics, goal-kicker totals, MVP totals and records remain controlled by PlayFooty Admin.</p><div className="actions"><Link className="manage" to={`/league-portal/${data.league.id}/profile`}>Manage league profile</Link><Link className="contacts" to={`/league-portal/${data.league.id}/contacts`}>League contacts</Link>{canManageMedia&&<Link className="news" to={`/league-portal/${data.league.id}/news`}>Manage league news</Link>}{canManageMedia&&<Link className="media" to={`/league-portal/${data.league.id}/media`}>Photos and media</Link>}{canManageSponsors&&<Link className="sponsors" to={`/league-portal/${data.league.id}/sponsors`}>Manage league sponsors</Link>}{canManageUsers&&<Link className="users" to={`/league-portal/${data.league.id}/users`}>Manage league users</Link>}<Link className="notifications" to={`/league-portal/${data.league.id}/notifications`}>League notifications</Link><Link className="activity" to={`/league-portal/${data.league.id}/activity`}>Recent activity</Link><Link className="public" to={`/league/${data.league.id}`}>Open public league profile <ExternalLink size={16}/></Link></div></section></>}</div></main><Footer/><style>{styles}</style></>
}
const styles=`.league-dashboard{min-height:72vh;background:#eef3f7;padding:38px 18px 60px;color:#111318}.league-dashboard-shell{width:min(980px,100%);margin:0 auto}.back{display:inline-flex;align-items:center;gap:7px;color:#111318;text-decoration:none;font-weight:900;margin-bottom:18px}.hero{display:flex;align-items:center;gap:20px;background:#050505;color:#fff;border-radius:18px;padding:28px;box-shadow:0 18px 45px rgba(5,5,5,.16)}.logo{width:92px;height:92px;border-radius:18px;background:#fff;display:grid;place-items:center;overflow:hidden;color:#111}.logo img{width:100%;height:100%;object-fit:contain}.hero span{color:#42b8ff;font-size:11px;font-weight:950;text-transform:uppercase;letter-spacing:.12em}.hero h1{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase;font-size:clamp(3rem,7vw,5.6rem);line-height:.85;margin:8px 0}.hero p{margin:0;color:#d7dde3}.card{margin-top:18px;background:#fff;border:1px solid #dce3e9;border-radius:16px;padding:24px;box-shadow:0 12px 32px rgba(17,24,39,.07)}.card h1,.card h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase;font-size:38px;margin:0 0 10px}.card p{color:#526070;line-height:1.65}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:8px}.public,.manage,.contacts,.news,.media,.sponsors,.users,.notifications,.activity,.error a{display:inline-flex;align-items:center;gap:7px;padding:12px 16px;border-radius:999px;color:#050505;text-decoration:none;font-weight:950}.public,.error a{background:#42b8ff}.manage{background:#21c879}.contacts{background:#c8e8ff}.news{background:#f2d24b}.media{background:#b9f0dc}.sponsors{background:#dfb9ff}.users{background:#ffb4a2}.notifications{background:#b9e6ff}.activity{background:#d8e1e8}.error{border-color:#fecaca;background:#fff7f7}@media(max-width:560px){.hero{align-items:flex-start;flex-direction:column}.logo{width:76px;height:76px}.actions{flex-direction:column}.actions a{justify-content:center}}`
