import { useState } from 'react'
import { ArrowRight, LogOut, ShieldCheck, UserPlus } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type AuthSession={access_token:string;refresh_token:string;user?:{id:string;email?:string|null}}
const SESSION_KEY='playfooty.leaguePortal.session.v1'
function config(){const url=String(import.meta.env.VITE_SUPABASE_URL??'').replace(/\/$/,'');const key=String(import.meta.env.VITE_SUPABASE_ANON_KEY??'');return{url,key,ready:Boolean(url&&key)}}
function readSession():AuthSession|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as AuthSession:null}catch{return null}}
async function authRequest(path:string,body:Record<string,unknown>){const auth=config();if(!auth.ready)throw new Error('League login is not configured yet');const response=await fetch(`${auth.url}/auth/v1/${path}`,{method:'POST',headers:{apikey:auth.key,'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json() as AuthSession&{error_description?:string;msg?:string};if(!response.ok)throw new Error(payload.error_description||payload.msg||'Authentication failed');return payload}

export default function LeaguePortal(){
 const[session,setSession]=useState<AuthSession|null>(()=>readSession());const[mode,setMode]=useState<'signin'|'signup'>('signin');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError('');setMessage('');try{const result=mode==='signup'?await authRequest('signup',{email:email.trim(),password}):await authRequest('token?grant_type=password',{email:email.trim(),password});if(!result.access_token){setMessage('Account created. Confirm your email, then sign in.');setMode('signin');return}localStorage.setItem(SESSION_KEY,JSON.stringify(result));setSession(result);setPassword('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to sign in')}finally{setLoading(false)}}
 function signOut(){localStorage.removeItem(SESSION_KEY);setSession(null);setMessage('You have signed out.')}
 return <><Nav/><main className="league-login"><section className="league-intro"><span>PlayFooty League Portal</span><h1>Manage your league</h1><p>Secure access for approved league representatives. Official statistics, rankings and canonical competition data remain controlled by PlayFooty Admin.</p><b><ShieldCheck size={18}/> Every league account is verified before profile access is granted</b></section><section className="league-panel">{!session?<><h2>{mode==='signin'?'League sign in':'Create league account'}</h2><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}<button disabled={loading}>{loading?'Please wait…':mode==='signin'?'Sign in securely':'Create account'} <ArrowRight size={16}/></button></form><button className="switch" onClick={()=>setMode(mode==='signin'?'signup':'signin')}><UserPlus size={16}/>{mode==='signin'?'Create a league account':'Already have an account? Sign in'}</button></>:<><div className="account"><div><span>Signed in as</span><strong>{session.user?.email||email}</strong></div><button onClick={signOut}><LogOut size={16}/> Sign out</button></div><div className="pending"><ShieldCheck size={34}/><h2>Account ready</h2><p>Your account is secure. League profile access will appear here after PlayFooty Admin approves or invites your league membership.</p><p>You will never be able to alter rankings, official statistics, results or canonical league data through this login.</p></div></>}</section></main><Footer/><style>{styles}</style></>
}
const styles=`.league-login{min-height:72vh;background:#eef3f7;padding:50px 20px;display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,540px);gap:60px;align-items:start}.league-intro>span{color:#0783c9;font-size:11px;font-weight:900;letter-spacing:.18em;text-transform:uppercase}.league-intro h1{font-family:'Bebas Neue',Impact,sans-serif;font-size:clamp(4rem,9vw,8rem);line-height:.82;text-transform:uppercase;margin:12px 0}.league-intro p{color:#526070;font-size:17px;max-width:720px;line-height:1.6}.league-intro b{display:inline-flex;align-items:center;gap:8px;margin-top:18px;padding:10px 14px;border-radius:999px;background:#fff;border:1px solid #d8e0e7}.league-panel{background:#fff;border:1px solid #dce3e9;border-radius:18px;box-shadow:0 18px 50px rgba(17,24,39,.1);padding:28px}.league-panel h2{font-family:'Bebas Neue',Impact,sans-serif;font-size:40px;text-transform:uppercase;margin:8px 0}.league-panel form{display:grid;gap:13px}.league-panel label{display:grid;gap:6px;font-size:12px;font-weight:900;text-transform:uppercase}.league-panel input{width:100%;box-sizing:border-box;border:1px solid #ccd5de;border-radius:10px;padding:13px;font:inherit}.league-panel form>button{min-height:48px;border:0;border-radius:10px;background:#111318;color:#fff;font-weight:900;text-transform:uppercase;display:flex;align-items:center;justify-content:center;gap:8px}.switch{display:flex;align-items:center;justify-content:center;gap:7px;width:100%;margin-top:12px;border:0;background:none;font-weight:900;padding:10px}.error,.notice{padding:11px;border-radius:9px}.error{background:#fee2e2;color:#991b1b}.notice{background:#e0f2fe;color:#075985}.account{display:flex;justify-content:space-between;align-items:center;gap:12px}.account span,.account strong{display:block}.account span{font-size:10px;text-transform:uppercase;color:#687385;font-weight:900}.account button{display:flex;align-items:center;gap:6px;border:0;background:#eef3f7;border-radius:999px;padding:9px 12px;font-weight:900}.pending{text-align:center;padding:38px 8px 18px}.pending p{color:#5f6b78;line-height:1.6}@media(max-width:850px){.league-login{grid-template-columns:1fr;gap:24px;padding:28px 14px}.league-intro h1{font-size:4.4rem}}`