import { useEffect,useMemo,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { ArrowLeft,ArrowRight,Newspaper,Save,Send,ShieldCheck } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Article={id:string;slug:string;title:string;subtitle:string|null;summary:string;body:string;status:string;author:string;updatedAt:string}
type Session={access_token:string}
const KEY='playfooty.leaguePortal.session.v1'
const session=():Session|null=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
const empty={title:'',subtitle:'',summary:'',body:'',author:''}

export default function LeaguePortalNews(){
 const{leagueId=''}=useParams();const[current,setCurrent]=useState<Article|null>(null);const[rows,setRows]=useState<Article[]>([]);const[form,setForm]=useState(empty);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const token=session()?.access_token??''
 const headers=useMemo(()=>({authorization:`Bearer ${token}`}),[token]);const json=useMemo(()=>({'content-type':'application/json',authorization:`Bearer ${token}`}),[token])
 const load=async()=>{if(!token)throw new Error('Sign in through the League Portal to continue.');const r=await fetch(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/news`,{headers});const p=await r.json() as{data?:Article[];error?:string};if(!r.ok)throw new Error(p.error||'Unable to load league news');setRows(p.data??[])}
 useEffect(()=>{let live=true;setLoading(true);void load().catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[leagueId])
 const choose=(article:Article|null)=>{setCurrent(article);setForm(article?{title:article.title,subtitle:article.subtitle??'',summary:article.summary,body:article.body,author:article.author}:empty);setMessage('');setError('')}
 const save=async(status:'DRAFT'|'APPROVED')=>{setSaving(true);setError('');setMessage('');try{const path=current?`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/news/${current.id}`:`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/news`;const r=await fetch(path,{method:current?'PATCH':'POST',headers:json,body:JSON.stringify({...form,status})});const p=await r.json() as{data?:Article;message?:string;error?:string};if(!r.ok||!p.data)throw new Error(p.error||'Article could not be saved');setCurrent(p.data);setForm({title:p.data.title,subtitle:p.data.subtitle??'',summary:p.data.summary,body:p.data.body,author:p.data.author});await load();setMessage(status==='APPROVED'?'Article submitted for PlayFooty approval':'Draft saved')}catch(e){setError(e instanceof Error?e.message:'Article could not be saved')}finally{setSaving(false)}}
 const editable=!current||current.status!=='PUBLISHED'
 return <><Nav/><main className="league-newsroom"><header><div><Link to={`/league-portal/${leagueId}`}><ArrowLeft size={16}/> Dashboard</Link><span>League newsroom</span><h1>News and media</h1><p>Create league stories for the public league profile and PlayFooty News.</p></div><button onClick={()=>choose(null)}>+ New article</button></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}{loading?<div className="state">Loading league stories…</div>:<div className="layout"><aside><h2>Your articles</h2>{rows.length?rows.map(article=><button key={article.id} className={current?.id===article.id?'active':''} onClick={()=>choose(article)}><span>{article.status==='APPROVED'?'AWAITING APPROVAL':article.status}</span><strong>{article.title}</strong><small>{new Date(article.updatedAt).toLocaleDateString('en-AU')}</small></button>):<div className="empty"><Newspaper size={28}/><p>No league articles yet.</p></div>}</aside><section className="editor"><div className="editor-head"><div><span>{current?current.status:'NEW DRAFT'}</span><h2>{current?'Edit article':'Create article'}</h2></div>{current?.status==='PUBLISHED'&&<Link to={`/news/${current.slug}`}>View story <ArrowRight size={15}/></Link>}</div><div className="fields"><label>Headline<input disabled={!editable} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Subheadline<input disabled={!editable} value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Short summary<textarea disabled={!editable} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Full article<textarea className="article-body" disabled={!editable} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Author<input disabled={!editable} value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></label></div>{editable?<footer><button className="secondary" disabled={saving} onClick={()=>void save('DRAFT')}><Save size={16}/> Save draft</button><button disabled={saving||!current} onClick={()=>void save('APPROVED')}><Send size={16}/> Submit for approval</button></footer>:<div className="published"><ShieldCheck size={22}/><div><strong>Published by PlayFooty</strong><span>Published stories are read-only in the League Portal.</span></div></div>}</section></div>}</main><Footer/><style>{styles}</style></>
}
const styles=`.league-newsroom{min-height:75vh;background:#eef3f7;padding:28px clamp(12px,4vw,40px) 60px;color:#111318}.league-newsroom>header,.league-newsroom>.layout,.league-newsroom>.alert,.league-newsroom>.state{max-width:1240px;margin-left:auto;margin-right:auto}.league-newsroom>header{display:flex;justify-content:space-between;align-items:end;gap:20px}.league-newsroom header a{display:inline-flex;align-items:center;gap:6px;color:#111;text-decoration:none;font-weight:850}.league-newsroom header span,.editor-head span,aside button span{display:block;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.13em;text-transform:uppercase}.league-newsroom h1,.league-newsroom h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.league-newsroom h1{font-size:clamp(3.5rem,8vw,6.5rem);line-height:.85;margin:10px 0}.league-newsroom button{border:0;border-radius:10px;background:#111318;color:#fff;padding:12px 15px;font-weight:900}.layout{display:grid;grid-template-columns:320px minmax(0,1fr);gap:16px;margin-top:20px}.layout aside,.editor{background:#fff;border:1px solid #dde4ea;border-radius:16px;padding:18px}.layout aside>button{display:block;width:100%;background:#f6f8fa;color:#111;text-align:left;margin-top:8px}.layout aside>button.active{outline:2px solid #2daaf5}.layout aside strong,.layout aside small{display:block}.editor-head{display:flex;justify-content:space-between}.editor-head a{color:#111;text-decoration:none;font-weight:900}.fields{display:grid;gap:13px}.fields label{display:grid;gap:6px;font-size:11px;font-weight:900;text-transform:uppercase}.fields input,.fields textarea{width:100%;box-sizing:border-box;border:1px solid #cfd8e1;border-radius:9px;padding:12px;font:inherit}.fields textarea{min-height:90px}.fields .article-body{min-height:300px}.editor footer{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.editor footer button{display:flex;align-items:center;gap:7px;background:#21c879}.editor footer .secondary{background:#e7edf2;color:#111}.published{display:flex;gap:11px;margin-top:16px;padding:14px;background:#e8f8ef}.alert,.state{margin-top:16px;padding:12px;border-radius:10px}.error{background:#fff0f0;color:#a51d17}.success{background:#e8f8ef;color:#12663c}.empty{text-align:center;padding:30px;color:#687385}@media(max-width:850px){.layout{grid-template-columns:1fr}.league-newsroom>header{align-items:flex-start;flex-direction:column}}@media(max-width:520px){.editor footer{flex-direction:column}.editor footer button{justify-content:center}}`
