import { useEffect,useMemo,useState } from 'react'
import { Link,useLocation,useParams } from 'react-router-dom'
import { ArrowLeft,Bell,Building2,CheckCheck,Clock3,Newspaper,ShieldCheck,Users } from 'lucide-react'
import Nav from '../components/layout/Nav'
import Footer from '../components/layout/Footer'

type Notice={id:string;category:string|null;severity:string;title:string;body:string|null;createdAt:string;isRead:boolean}
type Activity={id:string;source:'ACCESS'|'NEWS'|'SPONSOR';title:string;detail?:string;createdAt:string}
type Payload={membership:{role:string};notifications:Notice[];unread:number;activity:Activity[]}
type Session={access_token:string}
const KEY='playfooty.leaguePortal.session.v1'
function session():Session|null{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
function date(value:string){return new Date(value).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})}
function icon(source:string){return source==='NEWS'?Newspaper:source==='SPONSOR'?Building2:Users}
function activityLink(leagueId:string,item:Activity){if(item.source==='NEWS')return `/league-portal/${leagueId}/news`;if(item.source==='SPONSOR')return `/league-portal/${leagueId}/sponsors`;return `/league-portal/${leagueId}/users`}
export default function LeaguePortalActivity(){const{leagueId=''}=useParams();const{pathname}=useLocation();const initial=pathname.endsWith('/notifications')?'alerts':'activity';const[tab,setTab]=useState<'alerts'|'activity'>(initial);const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[unreadOnly,setUnreadOnly]=useState(false)
 const request=async(path:string,options:RequestInit={})=>{const s=session();if(!s)throw new Error('Sign in through the League Portal to continue.');const response=await fetch(path,{...options,headers:{...(options.headers??{}),authorization:`Bearer ${s.access_token}`}});const payload=await response.json().catch(()=>({})) as{data?:Payload;error?:string};if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 const load=async()=>{setLoading(true);setError('');try{const payload=await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/activity`);setData(payload.data??null)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load league activity')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[leagueId])
 const notices=useMemo(()=>unreadOnly?(data?.notifications??[]).filter(item=>!item.isRead):(data?.notifications??[]),[data,unreadOnly])
 const markRead=async(id:string)=>{try{await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/notifications/${encodeURIComponent(id)}/read`,{method:'POST'});setData(current=>current?{...current,unread:Math.max(0,current.unread-1),notifications:current.notifications.map(item=>item.id===id?{...item,isRead:true}:item)}:current)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to mark notification read')}}
 const readAll=async()=>{try{await request(`/api/league-portal/leagues/${encodeURIComponent(leagueId)}/notifications/read-all`,{method:'POST'});setData(current=>current?{...current,unread:0,notifications:current.notifications.map(item=>({...item,isRead:true}))}:current)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to mark notifications read')}}
 return <><Nav/><main className="lpa"><header><Link to={`/league-portal/${leagueId}`}><ArrowLeft size={16}/> Dashboard</Link><span>LEAGUE PORTAL</span><h1>Notifications & activity</h1><p>See what needs attention and what has changed across your league.</p></header>{loading?<div className="state">Loading league activity…</div>:error&&!data?<div className="state"><ShieldCheck/><h2>Activity unavailable</h2><p>{error}</p></div>:data?<><section className="summary"><article><Bell/><div><strong>{data.unread}</strong><span>Unread alerts</span></div></article><article><Clock3/><div><strong>{data.activity.length}</strong><span>Recent actions</span></div></article><article><ShieldCheck/><div><strong>{data.membership.role.replaceAll('_',' ')}</strong><span>Your access role</span></div></article></section><nav className="tabs"><button className={tab==='alerts'?'active':''} onClick={()=>setTab('alerts')}>Notifications {data.unread>0&&<b>{data.unread}</b>}</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Recent activity</button></nav>{error&&<div className="error">{error}</div>}{tab==='alerts'?<section className="panel"><div className="tools"><label><input type="checkbox" checked={unreadOnly} onChange={event=>setUnreadOnly(event.target.checked)}/> Unread only</label>{data.unread>0&&<button onClick={()=>void readAll()}><CheckCheck size={16}/> Mark all read</button>}</div>{notices.length?<div className="notices">{notices.map(item=><article key={item.id} className={item.isRead?'read':'unread'}><i/><div><span>{[item.category,item.severity].filter(Boolean).join(' · ')}</span><strong>{item.title}</strong>{item.body&&<p>{item.body}</p>}<small>{date(item.createdAt)}</small></div>{!item.isRead&&<button onClick={()=>void markRead(item.id)}>Mark read</button>}</article>)}</div>:<p className="empty">No notifications match this view.</p>}</section>:<section className="panel">{data.activity.length?<div className="timeline">{data.activity.map((item,index)=>{const Icon=icon(item.source);return <Link key={`${item.source}-${item.id}-${index}`} to={activityLink(leagueId,item)}><Icon/><div><span>{item.source}</span><strong>{item.title}</strong>{item.detail&&<p>{item.detail}</p>}<small>{date(item.createdAt)}</small></div></Link>})}</div>:<p className="empty">No recent league activity is available yet.</p>}</section>}</>:null}</main><Footer/><style>{styles}</style></>}
const styles=`.lpa{min-height:75vh;background:#eef3f7;padding:28px clamp(12px,4vw,42px) 60px;color:#111318}.lpa>*{max-width:1120px;margin-left:auto;margin-right:auto}.lpa header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.lpa header>span{display:block;color:#0783c9;font-size:10px;font-weight:900;letter-spacing:.15em;margin-top:25px}.lpa h1,.lpa h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.lpa h1{font-size:clamp(3.5rem,8vw,6.5rem);line-height:.85;margin:8px 0}.lpa header p,.empty{color:#687385}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:24px}.summary article,.panel{background:#fff;border:1px solid #dce4ea;border-radius:15px;box-shadow:0 8px 24px rgba(15,23,42,.045)}.summary article{display:flex;align-items:center;gap:13px;padding:17px}.summary strong,.summary span{display:block}.summary strong{font-family:'Bebas Neue',Impact,sans-serif;font-size:31px}.summary span{font-size:11px;color:#687385}.tabs{display:flex;gap:8px;margin-top:18px}.tabs button{border:1px solid #d5dde4;background:#fff;border-radius:999px;padding:10px 14px;font-weight:900}.tabs button.active{background:#111318;color:#fff}.tabs b{margin-left:5px;background:#42b8ff;color:#071018;border-radius:999px;padding:2px 6px}.panel{padding:20px;margin-top:12px}.tools{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.tools label{display:flex;gap:8px;font-weight:800}.tools button,.notices button{border:0;border-radius:8px;background:#111318;color:#fff;padding:9px 11px;font-weight:900}.notices,.timeline{display:grid;gap:9px}.notices article{display:grid;grid-template-columns:auto 1fr auto;gap:12px;padding:14px;border:1px solid #e1e7ec;border-radius:11px}.notices article.unread{background:#f2faff;border-color:#b9e3fa}.notices i{width:9px;height:9px;border-radius:50%;background:#c5ced6;margin-top:6px}.notices .unread i{background:#0783c9}.notices span,.timeline span{color:#0783c9;font-size:9px;font-weight:900}.notices strong,.notices small,.timeline strong,.timeline small{display:block}.notices p,.timeline p{color:#566270}.timeline a{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:14px;border:1px solid #e1e7ec;border-radius:11px;color:#111;text-decoration:none}.state,.empty{text-align:center;padding:50px}.error{padding:12px;border-radius:9px;background:#fff0f0;color:#9b2424;margin-top:12px}@media(max-width:650px){.lpa{padding:18px 10px 45px}.summary{grid-template-columns:1fr}.tools{align-items:flex-start;flex-direction:column;gap:10px}.notices article{grid-template-columns:auto 1fr}.notices article>button{grid-column:2;width:max-content}.tabs{overflow-x:auto}}`
