import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { Link, useLocation } from 'react-router-dom'
import { ArrowRight, Medal } from 'lucide-react'
import { TeamLogo } from '../rankings/bits'
import type { MvpEntry } from '../../pages/MvpLeaderboard'

export default function HomeMvpPortal(){
 const{pathname}=useLocation(),[target,setTarget]=useState<HTMLElement|null>(null),[rows,setRows]=useState<MvpEntry[]>([])
 useEffect(()=>{if(pathname!=='/'){setTarget(null);document.getElementById('pf-home-mvp-slot')?.remove();return}let active=true;const attach=()=>{if(!active)return;const host=document.querySelector<HTMLElement>('.pf-home');if(!host)return;let slot=document.getElementById('pf-home-mvp-slot');if(!slot){slot=document.createElement('div');slot.id='pf-home-mvp-slot';const dataGrid=host.querySelector('.pf-data-grid');if(dataGrid)dataGrid.insertAdjacentElement('afterend',slot);else host.append(slot)}setTarget(slot)};attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{active=false;observer.disconnect();setTarget(null);document.getElementById('pf-home-mvp-slot')?.remove()}},[pathname])
 useEffect(()=>{if(pathname!=='/')return;fetch('/api/mvp?limit=5').then(r=>r.ok?r.json():Promise.reject(new Error(`HTTP ${r.status}`))).then((p:{data?:MvpEntry[]})=>setRows(Array.isArray(p.data)?p.data:[])).catch(()=>setRows([]))},[pathname])
 if(!target||rows.length===0)return null
 return createPortal(<section className="hmvp"><div className="hmvp-head"><div><small>PLAYFOOTY NATIONAL AWARD</small><h2>Most Valuable Players</h2></div><Link to="/mvp">View full leaderboard <ArrowRight size={17}/></Link></div><div className="hmvp-grid">{rows.map(row=><article key={row.id} className="hmvp-card"><span className={`hmvp-rank r${row.rank}`}>{row.rank<=3?<Medal size={15}/>:null}{row.rank}</span><TeamLogo name={row.clubName} src={row.clubLogoUrl??undefined} size={64}/><strong>{row.playerId?<Link to={`/player/${row.playerId}`}>{row.playerName}</Link>:row.playerName}</strong><small>{row.clubId?<Link to={`/team/${row.clubId}`}>{row.clubName}</Link>:row.clubName}</small><span className="hmvp-meta">{row.bp} BP · {'★'.repeat(row.leagueStars)}</span><b>{row.mvpPoints}</b><em>MVP points</em></article>)}</div><style>{styles}</style></section>,target)
}

const styles=`.hmvp{width:min(1440px,calc(100% - 48px));margin:0 auto;padding:0 0 48px;font-family:Barlow,Inter,Arial,sans-serif}.hmvp-head{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:17px}.hmvp-head small{color:#148fd2;font-weight:900;letter-spacing:.15em}.hmvp-head h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase;font-size:clamp(2.8rem,5vw,5rem);line-height:.88;margin:5px 0 0}.hmvp-head>a{display:inline-flex;align-items:center;gap:8px;color:#42b8ff;text-decoration:none;text-transform:uppercase;font-size:12px;font-weight:800}.hmvp-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.hmvp-card{position:relative;display:flex;flex-direction:column;align-items:center;text-align:center;background:#050505;color:#fff;border-radius:12px;padding:25px 13px 20px;min-width:0}.hmvp-rank{position:absolute;left:0;top:0;width:42px;height:42px;border-radius:10px 0 10px 0;background:#42b8ff;color:#050505;display:flex;align-items:center;justify-content:center;gap:2px;font-family:'Bebas Neue',Impact,sans-serif;font-size:22px}.hmvp-rank.r1{background:#f0c84f}.hmvp-rank.r2{background:#d8dee5}.hmvp-rank.r3{background:#c78c52}.hmvp-card>strong{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase;font-size:22px;line-height:1;margin-top:12px}.hmvp-card a{color:inherit;text-decoration:none}.hmvp-card a:hover{color:#42b8ff}.hmvp-card>small{color:#aab4bf;margin-top:6px}.hmvp-meta{font-size:11px;color:#f3c94f;margin-top:10px}.hmvp-card>b{font-family:'Bebas Neue',Impact,sans-serif;font-size:42px;line-height:1;color:#42b8ff;margin-top:8px}.hmvp-card>em{font-style:normal;text-transform:uppercase;font-size:9px;letter-spacing:.12em;color:#aab4bf}@media(max-width:900px){.hmvp-grid{display:flex;overflow-x:auto;padding-bottom:8px;scroll-snap-type:x mandatory}.hmvp-card{min-width:220px;scroll-snap-align:start}}@media(max-width:620px){.hmvp{width:calc(100% - 24px)}.hmvp-head{align-items:start}.hmvp-head>a{max-width:120px;text-align:right}.hmvp-card{min-width:195px}}`
