import{Router}from'express'
import{prisma}from'../db/client.js'
import{requireAdminKey}from'../api/middleware/auth.js'
import{parseProfileImage,type ProfileImageKind}from'../ocr/parse-profile-image.js'
import{similarity}from'../ocr/fuzzy-match.js'
const router=Router();router.use(requireAdminKey)
router.post('/parse',async(req,res)=>{try{const{image,kind}=req.body as{image?:string;kind?:ProfileImageKind};if(!image||!['club','league','players'].includes(kind??''))return res.status(400).json({error:'image and valid kind required'});const data=await parseProfileImage(image,kind!);const clubs=await prisma.club.findMany({where:{archivedAt:null},select:{id:true,name:true},take:2000});const leagues=await prisma.league.findMany({where:{archivedAt:null},select:{id:true,name:true},take:500});const best=(name:string|null,rows:{id:string;name:string}[])=>{if(!name)return null;let b:{id:string;name:string;score:number}|null=null;for(const x of rows){const s=similarity(name,x.name);if(!b||s>b.score)b={...x,score:s}}return b};res.json({data:{...data,clubMatch:best(data.name,clubs),leagueMatch:best(data.name,leagues),players:data.players.map(p=>({...p,clubMatch:best(p.clubName??data.name,clubs)}))}})}catch(e){res.status(500).json({error:e instanceof Error?e.message:String(e)})}})
router.post('/commit',async(req,res)=>{try{const{kind,targetId,profile,players}=req.body as{kind?:ProfileImageKind;targetId?:string;profile?:Record<string,unknown>;players?:Array<Record<string,unknown>>};if(!kind||!targetId)return res.status(400).json({error:'kind and targetId required'});let updated=0;if(kind==='club'){const club=await prisma.club.findUnique({where:{id:targetId},select:{id:true,notes:true}});if(!club)return res.status(404).json({error:'club not found'});const officials=Array.isArray(profile?.officials)?profile!.officials:[];const notes=[String(profile?.bio??''),officials.length?`Officials: ${officials.map((x:any)=>`${x.role}: ${x.name}${x.email?` (${x.email})`:''}${x.phone?` ${x.phone}`:''}`).join('; ')}`:'',String(profile?.email??'')?`Email: ${profile?.email}`:'',String(profile?.phone??'')?`Phone: ${profile?.phone}`:''].filter(Boolean).join('\n');await prisma.club.update({where:{id:targetId},data:{websiteUrl:(profile?.websiteUrl as string)||undefined,facebookUrl:(profile?.facebookUrl as string)||undefined,instagramUrl:(profile?.instagramUrl as string)||undefined,townName:(profile?.town as string)||undefined,notes:notes||club.notes,manualOverride:true}});updated++}else if(kind==='league'){const league=await prisma.league.findUnique({where:{id:targetId},select:{id:true}});if(!league)return res.status(404).json({error:'league not found'});await prisma.league.update({where:{id:targetId},data:{websiteUrl:(profile?.websiteUrl as string)||undefined,facebookUrl:(profile?.facebookUrl as string)||undefined,regionName:(profile?.town as string)||undefined,lastManualUpdateAt:new Date(),manualOverride:true}});updated++}else{for(const row of players??[]){if(row.skip)continue;const playerName=String(row.playerName??'').trim(),clubName=String(row.clubName??'').trim(),leagueName=String(row.leagueName??'').trim(),season=String(row.season??new Date().getFullYear()),grade=String(row.grade??'Senior Football');if(!playerName||!clubName||!leagueName)continue;await prisma.footballGoalKicker.upsert({where:{season_grade_playerName_clubName_leagueName:{season,grade,playerName,clubName,leagueName}},create:{playerName,clubId:(row.clubId as string)||null,clubName,leagueId:(row.leagueId as string)||null,leagueName,season,grade,goals:Number(row.goals??0),matches:row.matches==null?null:Number(row.matches),sourceType:'OCR_UPLOAD',importedAt:new Date()},update:{clubId:(row.clubId as string)||null,leagueId:(row.leagueId as string)||null,goals:Number(row.goals??0),matches:row.matches==null?null:Number(row.matches),sourceType:'OCR_UPLOAD',importedAt:new Date()}});updated++}}res.json({data:{updated}})}catch(e){res.status(500).json({error:e instanceof Error?e.message:String(e)})}})
export{router as adminProfileImageImportsRouter}
