import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { Link, useLocation } from 'react-router-dom'

type ClubPayload = { data?: { clubId:string; clubName:string; leagueId?:string|null } }
type FixtureRow = { id:string; sourceId?:string; round?:string|number|null; grade?:string|null; matchDate?:string|null; venue?:string|null; homeClubId?:string|null; awayClubId?:string|null; homeClubName?:string; awayClubName?:string; homeName?:string; awayName?:string }
type LeaguePayload = { data?: { fixtures?: FixtureRow[] } }
type ClubFixturesPayload = { data?: FixtureRow[] }

const normalise=(value:string|null|undefined)=>(value??'').toLowerCase().replace(/&/g,'and').replace(/\b(seniors?|senior men|a grade|football club|fc)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim()
function belongsToClub(row:FixtureRow,clubId:string,clubName:string){if(row.homeClubId===clubId||row.awayClubId===clubId)return true;const target=normalise(clubName);return normalise(row.homeClubName??row.homeName)===target||normalise(row.awayClubName??row.awayName)===target}
function isUpcoming(row:FixtureRow){if(!row.matchDate)return true;const time=Date.parse(row.matchDate);return Number.isNaN(time)||time>=Date.now()-86400000}

export default function ClubFixtureBridge(){
 const{pathname}=useLocation();const match=pathname.match(/^\/team\/([^/]+)$/);const clubId=match?decodeURIComponent(match[1]):''
 const[clubName,setClubName]=useState('');const[rows,setRows]=useState<FixtureRow[]>([]);const[target,setTarget]=useState<HTMLElement|null>(null)
 useEffect(()=>{setRows([]);setClubName('');if(!clubId)return;let active=true;void Promise.allSettled([
  fetch(`/api/clubs/${encodeURIComponent(clubId)}`).then(r=>r.ok?r.json() as Promise<ClubPayload>:Promise.reject(new Error(`HTTP ${r.status}`))),
  fetch(`/api/clubs/${encodeURIComponent(clubId)}/fixtures?upcoming=true`).then(r=>r.ok?r.json() as Promise<ClubFixturesPayload>:Promise.reject(new Error(`HTTP ${r.status}`))),
 ]).then(async results=>{if(!active)return;const club=results[0].status==='fulfilled'?results[0].value.data:undefined;const direct=results[1].status==='fulfilled'&&Array.isArray(results[1].value.data)?results[1].value.data:[];if(!club)return;setClubName(club.clubName);if(direct.length>0){setRows(direct.filter(isUpcoming).slice(0,5));return}if(!club.leagueId)return;const response=await fetch(`/api/leagues/${encodeURIComponent(club.leagueId)}`);if(!response.ok)return;const league=await response.json() as LeaguePayload;if(!active)return;const fixtures=Array.isArray(league.data?.fixtures)?league.data.fixtures:[];setRows(fixtures.filter(row=>belongsToClub(row,club.clubId,club.clubName)&&isUpcoming(row)).slice(0,5))}).catch(()=>undefined);return()=>{active=false}},[clubId])
 useEffect(()=>{if(!clubId||rows.length===0){setTarget(null);return}let stopped=false;const attach=()=>{if(stopped)return;const cards=Array.from(document.querySelectorAll<HTMLElement>('.club-live-card'));const card=cards.find(element=>element.querySelector('h2')?.textContent?.trim().toLowerCase()==='upcoming fixtures');if(!card)return;card.classList.add('club-fixture-bridge-active');let node=card.querySelector<HTMLElement>(':scope > .club-fixture-bridge-slot');if(!node){node=document.createElement('div');node.className='club-fixture-bridge-slot';card.appendChild(node)}setTarget(node)};attach();const observer=new MutationObserver(attach);observer.observe(document.getElementById('root')??document.body,{childList:true,subtree:true});return()=>{stopped=true;observer.disconnect();document.querySelectorAll('.club-fixture-bridge-active').forEach(element=>element.classList.remove('club-fixture-bridge-active'));setTarget(null)}},[clubId,rows])
 if(!target||rows.length===0)return null
 return createPortal(<><div className="club-match-list club-fixture-bridge-list">{rows.map(row=>{const id=row.sourceId??row.id.replace(/^football:/,'');const home=row.homeClubName??row.homeName??'Home';const away=row.awayClubName??row.awayName??'Away';const isHome=row.homeClubId===clubId||normalise(home)===normalise(clubName);const params=new URLSearchParams({tab:'team-selection'});if(row.round!=null)params.set('round',String(row.round));if(row.grade)params.set('grade',row.grade);return <article key={row.id} className="club-fixture-bridge-row"><Link className="club-fixture-match-link" to={`/match/fixture/${encodeURIComponent(id)}?source=football`}><span className={isHome?'this-club':''}>{home}</span><span className={!isHome?'this-club':''}>{away}</span><small>{[row.round??row.grade,row.matchDate?formatDate(row.matchDate):null,row.venue].filter(Boolean).join(' · ')}</small></Link><Link className="club-fixture-team-link" to={`/team/${encodeURIComponent(clubId)}?${params.toString()}`}>Team selection</Link></article>})}</div><style>{`
 .club-fixture-bridge-active>.club-live-empty{display:none!important}.club-fixture-bridge-list{display:grid}.club-fixture-bridge-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:11px 0;border-top:1px solid #edf1f4}.club-fixture-match-link{display:grid;grid-template-columns:minmax(0,1fr);gap:3px;color:#111318;text-decoration:none}.club-fixture-match-link>span{font-size:13px;font-weight:800}.club-fixture-match-link>span.this-club{font-weight:950}.club-fixture-match-link>small{color:#687385;font-size:10px;margin-top:3px}.club-fixture-team-link{display:inline-flex;align-items:center;justify-content:center;border:1px solid #9fd6f5;border-radius:999px;padding:7px 10px;color:#0783c9;text-decoration:none;text-transform:uppercase;font-size:9px;font-weight:900;letter-spacing:.06em;white-space:nowrap}.club-fixture-team-link:hover{background:#eef8ff}@media(max-width:620px){.club-fixture-bridge-row{grid-template-columns:1fr}.club-fixture-team-link{justify-self:start}}
 `}</style></>,target)
}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short'}).format(date)}