import { ArrowLeft, ImagePlus, Search, Trash2, Upload } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import MediaTeamGraphicGenerator from './MediaTeamGraphicGenerator'

type Session={access_token:string}
type Asset={id:string;title:string;description:string|null;mediaType:string;status:string;fileUrl:string;createdAt:string}
const SESSION_KEY='playfooty.clubPortal.session.v1'
const TYPES=['ALL','PLAYER','MATCH','MILESTONE','TEAM_SELECTION','SPONSOR','CLUB','GENERATED','OTHER']
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read image'));reader.readAsDataURL(file)})}

export default function ClubMediaPortalOverlay({clubId}:{clubId:string}){
 const[current]=useState(()=>session());const[tab,setTab]=useState<'studio'|'library'>('studio');const[assets,setAssets]=useState<Asset[]>([]);const[loading,setLoading]=useState(false);const[uploading,setUploading]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[query,setQuery]=useState('');const[type,setType]=useState('ALL')
 const headers=useMemo<Record<string,string>>(()=>current?{authorization:`Bearer ${current.access_token}`}:{},[current])
 async function request(path:string,options:RequestInit={}){const response=await fetch(path,{...options,headers:{...headers,...(options.headers as Record<string,string>|undefined)}});const payload=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
 async function load(){if(!current)return setError('Sign in through the Club Portal to continue.');setLoading(true);setError('');try{const params=new URLSearchParams();if(type!=='ALL')params.set('type',type);if(query.trim())params.set('q',query.trim());const payload=await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}?${params}`);setAssets(Array.isArray(payload.data)?payload.data:[])}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load media')}finally{setLoading(false)}}
 useEffect(()=>{if(tab==='library')void load()},[tab,type,clubId])
 async function upload(file:File){if(file.size>10*1024*1024)return setError('Image must be 10 MB or smaller');setUploading(true);setError('');try{const dataUrl=await fileData(file);const image=new Image();const size=await new Promise<{width:number;height:number}>(resolve=>{image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>resolve({width:0,height:0});image.src=dataUrl});await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl,contentType:file.type,title:file.name.replace(/\.[^.]+$/,''),mediaType:type==='ALL'?'OTHER':type,status:'READY',width:size.width,height:size.height,tags:[]})});setMessage('Media uploaded');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to upload media')}finally{setUploading(false)}}
 async function archive(asset:Asset){if(!confirm(`Archive ${asset.title}?`))return;try{await request(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/${encodeURIComponent(asset.id)}`,{method:'DELETE'});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to archive media')}}
 return <div className="cmp-overlay"><main className="cmp"><header><Link to={`/club-portal/${clubId}`}><ArrowLeft size={18}/> Club portal</Link><span>CLUB MEDIA PORTAL</span><h1>Media Centre</h1><p>Create branded club graphics, manage shared assets and prepare content without entering the coaching workflow.</p></header><nav className="cmp-tabs"><button className={tab==='studio'?'active':''} onClick={()=>setTab('studio')}>Graphic studio</button><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}>Media library</button></nav>{error&&<div className="cmp-alert error">{error}</div>}{message&&<div className="cmp-alert success">{message}</div>}{tab==='studio'?<MediaTeamGraphicGenerator clubId={clubId}/>:<><section className="cmp-tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}} placeholder="Search media"/></label><select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><button onClick={()=>void load()}>Search</button><label className="cmp-upload"><Upload size={17}/>{uploading?'Uploading…':'Upload'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.currentTarget.value=''}}/></label></section>{loading?<div className="cmp-state">Loading media…</div>:assets.length?<section className="cmp-grid">{assets.map(asset=><article key={asset.id}><img src={asset.fileUrl} alt={asset.title}/><div><span>{asset.mediaType.replaceAll('_',' ')}</span><h2>{asset.title}</h2><small>{new Date(asset.createdAt).toLocaleDateString('en-AU')} · {asset.status}</small><button onClick={()=>void archive(asset)}><Trash2 size={15}/> Archive</button></div></article>)}</section>:<section className="cmp-state"><ImagePlus size={40}/><h2>No media found</h2><p>Upload club assets or generate the first team graphic.</p></section>}</>}</main><style>{styles}</style></div>
}
const styles=`.cmp-overlay{position:fixed;inset:0;z-index:100100;overflow:auto;background:#eef3f7}.cmp{min-height:100%;box-sizing:border-box;padding:26px clamp(12px,4vw,42px) 120px;color:#111318}.cmp>*{max-width:1240px;margin-left:auto;margin-right:auto}.cmp header>a{display:inline-flex;align-items:center;gap:7px;color:#111;text-decoration:none;font-weight:900}.cmp header>span{display:block;margin-top:22px;color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.cmp h1,.cmp h2{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.cmp h1{font-size:clamp(4rem,9vw,7rem);line-height:.84;margin:8px 0}.cmp header p{max-width:760px;color:#687385}.cmp-tabs{display:flex;gap:8px;margin-top:22px}.cmp-tabs button{border:1px solid #d6e0e7;border-radius:999px;padding:11px 17px;background:#fff;font-weight:950;text-transform:uppercase}.cmp-tabs button.active{background:#111318;color:#fff}.cmp-tools{display:grid;grid-template-columns:1fr 210px auto auto;gap:9px;margin-top:20px}.cmp-tools label:first-child{display:flex;align-items:center;gap:8px;padding:0 13px;border:1px solid #dce4ea;border-radius:12px;background:#fff}.cmp-tools input,.cmp-tools select,.cmp-tools button{width:100%;box-sizing:border-box;padding:12px;border:1px solid #dce4ea;border-radius:12px;background:#fff}.cmp-tools label:first-child input{border:0;outline:0;padding-left:0}.cmp-tools button{width:auto;background:#35b6ff;font-weight:950}.cmp-upload{display:flex;align-items:center;gap:7px;padding:11px 14px;border-radius:12px;background:#111318;color:#fff;font-weight:950;text-transform:uppercase}.cmp-upload input{display:none}.cmp-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-top:16px}.cmp-grid article{overflow:hidden;border:1px solid #dce4ea;border-radius:16px;background:#fff}.cmp-grid img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.cmp-grid article>div{padding:14px}.cmp-grid span{color:#0783c9;font-size:9px;font-weight:950}.cmp-grid h2{margin:5px 0;font-size:28px}.cmp-grid small{color:#75808b}.cmp-grid button{display:flex;align-items:center;gap:5px;margin-top:12px;border:0;border-radius:999px;padding:8px 11px;background:#ffe7e7;color:#9c2020;font-weight:900}.cmp-state,.cmp-alert{margin-top:18px;padding:34px;border:1px solid #dce4ea;border-radius:15px;background:#fff;text-align:center}.cmp-alert{padding:12px;text-align:left}.cmp-alert.error{background:#ffe8e8;color:#9f2020}.cmp-alert.success{background:#e3f8ec;color:#167343}@media(max-width:760px){.cmp-tools{grid-template-columns:1fr}.cmp-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.cmp{padding:18px 9px 100px}.cmp-grid{grid-template-columns:1fr}}`