import { BarChart3, ClipboardList, Home, Image, Settings2, UserRound } from 'lucide-react'
import { createPortal } from 'react-dom'
import { Link, useLocation } from 'react-router-dom'
import ClubHqCommandCentre from './ClubHqCommandCentre'

const COACHING_SECTIONS=new Set(['coaching','availability','team-selection','whiteboard'])

export default function ClubPortalAppNav(){
 const{pathname}=useLocation()
 const match=pathname.match(/^\/club-portal\/([^/]+)(?:\/([^/?#]+))?(?:\/|$)/)
 const clubId=match?.[1]??''
 const section=match?.[2]??''
 const whiteboard=section==='whiteboard'
 if(!clubId||whiteboard)return <ClubHqCommandCentre/>
 const items=[
  {label:'Home',description:'Today and club activity',href:`/club-portal/${clubId}`,icon:Home,active:!section},
  {label:'Coaching',description:'Team, training and match day',href:`/club-portal/${clubId}/coaching`,icon:ClipboardList,active:COACHING_SECTIONS.has(section)},
  {label:'Operations',description:'Volunteers and equipment',href:`/club-portal/${clubId}/volunteers`,icon:Settings2,active:section==='volunteers'||section==='equipment'},
  {label:'Media',description:'News, creatives and live content',href:`/club-portal/${clubId}/media`,icon:Image,active:section==='media'||section==='news'||section==='milestones'},
  {label:'Analytics',description:'Club and sponsor performance',href:`/club-portal/${clubId}/analytics`,icon:BarChart3,active:section==='analytics'},
  {label:'Profile',description:'Club details, sponsors and users',href:`/club-portal/${clubId}/profile`,icon:UserRound,active:section==='profile'||section==='sponsors'||section==='users'||section==='plans'},
 ]
 const navigation=<><aside className="club-hq-sidebar"><Link className="club-hq-brand" to={`/club-portal/${clubId}`}><span>PLAYFOOTY</span><strong>Club HQ</strong></Link><nav>{items.map(item=><Link key={item.label} to={item.href} className={item.active?'active':''} aria-current={item.active?'page':undefined}><item.icon size={20}/><span><strong>{item.label}</strong><small>{item.description}</small></span></Link>)}</nav><footer>One connected workspace for your whole football club.</footer></aside><nav className="club-hq-mobile" aria-label="Club HQ navigation">{items.map(item=><Link key={item.label} to={item.href} className={item.active?'active':''} aria-current={item.active?'page':undefined}><item.icon size={21}/><span>{item.label}</span></Link>)}</nav><style>{styles}</style></>
 return <><ClubHqCommandCentre/>{createPortal(navigation,document.body)}</>
}

const styles=`
.club-hq-sidebar{position:fixed;inset:0 auto 0 0;z-index:100300;width:248px;box-sizing:border-box;padding:24px 14px;background:#101317;color:#fff;box-shadow:12px 0 34px rgba(15,23,42,.12)}.club-hq-brand{display:grid;gap:3px;margin:2px 10px 30px;color:#fff;text-decoration:none}.club-hq-brand span{color:#52c0ff;font-size:9px;font-weight:950;letter-spacing:.18em}.club-hq-brand strong{font:38px/1 'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.club-hq-sidebar nav{display:grid;gap:6px}.club-hq-sidebar nav a{display:grid;grid-template-columns:38px 1fr;align-items:center;gap:8px;padding:11px;border-radius:14px;color:#aeb7bf;text-decoration:none;transition:background .16s ease,color .16s ease,transform .16s ease}.club-hq-sidebar nav a:hover{background:#171d23;color:#fff}.club-hq-sidebar nav a:active{transform:scale(.985)}.club-hq-sidebar nav a>svg{justify-self:center}.club-hq-sidebar nav a>span{display:grid;gap:2px}.club-hq-sidebar nav a strong{font-size:13px}.club-hq-sidebar nav a small{color:#75818b;font-size:9px;line-height:1.35}.club-hq-sidebar nav a.active{background:#1f2a33;color:#fff}.club-hq-sidebar nav a.active svg{color:#52c0ff;stroke-width:2.8}.club-hq-sidebar nav a.active small{color:#a7cce1}.club-hq-sidebar footer{position:absolute;left:24px;right:24px;bottom:24px;color:#68747e;font-size:10px;line-height:1.5}.club-hq-mobile{display:none}.pf-menu-open .club-hq-sidebar{transform:translateX(-100%)}
body:has(.club-hq-sidebar) .cp-dashboard,body:has(.club-hq-sidebar) .club-portal-page,body:has(.club-hq-sidebar) .club-portal-profile,body:has(.club-hq-sidebar) .club-portal-page-wrap{margin-left:248px!important;width:auto!important;max-width:none!important;box-sizing:border-box!important}body:has(.club-hq-sidebar) #root>nav,body:has(.club-hq-sidebar) #root>footer{margin-left:248px}body:has(.club-hq-sidebar) .coach-workspace-layer{left:248px!important}body:has(.club-hq-sidebar) .cmp-sidebar{display:none!important}body:has(.club-hq-sidebar) .cmp-shell{margin-left:248px!important;padding-top:24px!important}body:has(.club-hq-sidebar) .cmp-mobile-nav{position:sticky!important;top:0!important;bottom:auto!important;z-index:5!important;display:grid!important;grid-template-columns:repeat(6,minmax(105px,1fr))!important;overflow-x:auto!important;margin:-24px -34px 22px!important;padding:9px 34px!important;border-top:0!important;border-bottom:1px solid #dfe4e8!important;box-shadow:0 8px 22px rgba(15,23,42,.05)!important}body:has(.club-hq-sidebar) .cmp-mobile-nav button{min-height:48px!important;flex-direction:row!important;font-size:10px!important}.pf-menu-open .club-hq-sidebar{opacity:0;pointer-events:none}
@media(max-width:760px){.club-hq-sidebar{display:none}.club-hq-mobile{position:fixed;left:0;right:0;bottom:0;z-index:100300;display:grid;grid-template-columns:repeat(6,1fr);gap:3px;padding:7px 6px calc(7px + env(safe-area-inset-bottom));background:rgba(250,251,252,.97);border-top:1px solid #dfe4e8;box-shadow:0 -8px 28px rgba(15,23,42,.09);backdrop-filter:blur(18px)}.club-hq-mobile a{display:flex;min-width:0;min-height:54px;flex-direction:column;align-items:center;justify-content:center;gap:4px;border-radius:12px;color:#8b949d;text-decoration:none;font-size:8px;font-weight:900}.club-hq-mobile a.active{background:#e6f5fe;color:#087bbf}.club-hq-mobile a.active svg{stroke-width:2.8}.pf-menu-open .club-hq-mobile{transform:translateY(calc(100% + 24px));opacity:0;pointer-events:none}body:has(.club-hq-mobile) .cp-dashboard,body:has(.club-hq-mobile) .club-portal-page,body:has(.club-hq-mobile) .club-portal-profile,body:has(.club-hq-mobile) .club-portal-page-wrap{margin-left:0!important;padding-bottom:96px!important}body:has(.club-hq-mobile) #root>nav,body:has(.club-hq-mobile) #root>footer{margin-left:0}body:has(.club-hq-mobile) .coach-workspace-layer{left:0!important;padding-bottom:96px!important}body:has(.club-hq-mobile) .cmp-sidebar{display:none!important}body:has(.club-hq-mobile) .cmp-shell{margin-left:0!important;padding-bottom:110px!important}body:has(.club-hq-mobile) .cmp-mobile-nav{position:sticky!important;top:0!important;bottom:auto!important;z-index:5!important;display:grid!important;grid-template-columns:repeat(6,86px)!important;overflow-x:auto!important;margin:-18px -10px 18px!important;padding:8px 10px!important;border-top:0!important;border-bottom:1px solid #dfe4e8!important;box-shadow:0 7px 18px rgba(15,23,42,.05)!important}.club-hq-mobile a span{white-space:nowrap}}
@media(max-width:430px){.club-hq-mobile a{font-size:7px;gap:3px}.club-hq-mobile a svg{width:19px;height:19px}}
`
