import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, ListTodo, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

type Session={access_token:string}
type Task={id:string;title:string;detail:string|null;status:string;actionUrl:string|null;dueAt:string|null;priority:string}
type Approval={id:string;title:string;status:string;mediaType:string}
type Coordination={tasks:Task[];approvals:Approval[]}
type Dashboard={teamSelection:null|{status:string;roundLabel:string;opponentName:string|null;matchDate?:string|null}}
type ScheduleItem={id:string;title:string;detail:string;time:string;to:string;kind:'MATCH'|'TASK'|'APPROVAL';date:Date}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function readSession():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
function startOfDay(value:Date){const date=new Date(value);date.setHours(0,0,0,0);return date}
function dayDiff(value:Date){return Math.round((startOfDay(value).getTime()-startOfDay(new Date()).getTime())/86400000)}
function timeLabel(value:Date){return value.toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'})}

export default function ClubHqUpcomingSchedule({clubId}:{clubId:string}){
 const[current]=useState(()=>readSession())
 const[dashboard,setDashboard]=useState<Dashboard|null>(null)
 const[coordination,setCoordination]=useState<Coordination|null>(null)
 const[error,setError]=useState('')
 useEffect(()=>{if(!current||!clubId)return;let active=true;const headers={authorization:`Bearer ${current.access_token}`};const load=async()=>{try{const[dashResponse,coordResponse]=await Promise.all([fetch(`/api/club-portal/clubs/${encodeURIComponent(clubId)}/dashboard`,{headers}),fetch(`/api/club-portal/coordination/clubs/${encodeURIComponent(clubId)}`,{headers})]);const dashPayload=await dashResponse.json().catch(()=>({})) as {data?:Dashboard};const coordPayload=await coordResponse.json().catch(()=>({})) as {data?:Coordination};if(!dashResponse.ok||!coordResponse.ok)throw new Error('Unable to load schedule');if(active){setDashboard(dashPayload.data||null);setCoordination(coordPayload.data||null);setError('')}}catch{if(active)setError('Upcoming schedule is temporarily unavailable.')}};void load();const timer=window.setInterval(()=>void load(),60000);return()=>{active=false;window.clearInterval(timer)}},[clubId,current])
 const groups=useMemo(()=>{const items:ScheduleItem[]=[];const selection=dashboard?.teamSelection;if(selection?.matchDate){const date=new Date(selection.matchDate);if(Number.isFinite(date.getTime())&&dayDiff(date)>=0&&dayDiff(date)<=7)items.push({id:'match',title:`${selection.roundLabel}${selection.opponentName?` · v ${selection.opponentName}`:''}`,detail:selection.status==='PUBLISHED'?'Team published · match preparation ready':'Team selection still needs attention',time:timeLabel(date),to:`/club-portal/${clubId}/coaching?view=match-day`,kind:'MATCH',date})}
 for(const task of coordination?.tasks||[]){if(task.status!=='OPEN'||!task.dueAt)continue;const date=new Date(task.dueAt);if(!Number.isFinite(date.getTime())||dayDiff(date)<0||dayDiff(date)>7)continue;items.push({id:`task-${task.id}`,title:task.title,detail:task.detail||`${task.priority} priority club task`,time:timeLabel(date),to:task.actionUrl||`/club-portal/${clubId}`,kind:'TASK',date})}
 const pending=(coordination?.approvals||[]).filter(item=>item.status==='PENDING');pending.forEach((approval,index)=>{const date=new Date();date.setMinutes(date.getMinutes()+index);items.push({id:`approval-${approval.id}`,title:approval.title,detail:`${approval.mediaType.replaceAll('_',' ')} approval awaiting review`,time:'Today',to:`/club-portal/${clubId}`,kind:'APPROVAL',date})})
 const sorted=items.sort((a,b)=>a.date.getTime()-b.date.getTime());return{today:sorted.filter(item=>dayDiff(item.date)===0),tomorrow:sorted.filter(item=>dayDiff(item.date)===1),week:sorted.filter(item=>dayDiff(item.date)>=2&&dayDiff(item.date)<=7)}} ,[dashboard,coordination,clubId])
 const total=groups.today.length+groups.tomorrow.length+groups.week.length
 return <section className="hq-schedule"><header><div><span>UPCOMING SCHEDULE</span><h2>What’s ahead</h2><p>Matches, due tasks and approvals across the next seven days.</p></div><CalendarDays size={29}/></header>{error&&<div className="hq-schedule-error">{error}</div>}{!error&&total===0?<div className="hq-schedule-empty"><CheckCircle2 size={24}/><strong>No scheduled items in the next seven days.</strong><span>New match dates and task deadlines will appear here automatically.</span></div>:<div className="hq-schedule-grid"><ScheduleGroup title="Today" items={groups.today}/><ScheduleGroup title="Tomorrow" items={groups.tomorrow}/><ScheduleGroup title="This week" items={groups.week}/></div>}<style>{styles}</style></section>
}
function ScheduleGroup({title,items}:{title:string;items:ScheduleItem[]}){return <section><h3>{title}<b>{items.length}</b></h3>{items.length?items.map(item=><Link key={item.id} to={item.to}><i>{item.kind==='MATCH'?<ShieldCheck size={18}/>:item.kind==='APPROVAL'?<ClipboardCheck size={18}/>:<ListTodo size={18}/>}</i><span><strong>{item.title}</strong><small>{item.detail}</small></span><em>{item.time}</em><ChevronRight size={16}/></Link>):<p>Nothing scheduled.</p>}</section>}
const styles=`.hq-schedule{padding:22px;border:1px solid #d8e2ea;border-radius:18px;background:#fff;box-shadow:0 10px 28px rgba(15,23,42,.06)}.hq-schedule>header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.hq-schedule>header span{color:#0783c9;font-size:9px;font-weight:950;letter-spacing:.15em}.hq-schedule h2,.hq-schedule h3{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.hq-schedule h2{margin:5px 0 3px;font-size:42px}.hq-schedule header p{margin:0;color:#687385}.hq-schedule>header>svg{color:#0783c9}.hq-schedule-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:18px}.hq-schedule-grid>section{min-width:0;padding:14px;border-radius:13px;background:#f6f8fa}.hq-schedule h3{display:flex;align-items:center;justify-content:space-between;margin:0 0 8px;font-size:24px}.hq-schedule h3 b{display:grid;min-width:25px;height:25px;place-items:center;border-radius:999px;background:#dff3ff;color:#087bbf;font:900 11px/1 Arial,sans-serif}.hq-schedule a{display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;align-items:center;gap:9px;padding:11px 0;border-bottom:1px solid #e1e7ec;color:#111;text-decoration:none}.hq-schedule a:last-child{border-bottom:0}.hq-schedule a i{display:grid;width:34px;height:34px;place-items:center;border-radius:10px;background:#fff;color:#087bbf}.hq-schedule a strong,.hq-schedule a small{display:block}.hq-schedule a small{margin-top:3px;color:#687385;font-size:10px}.hq-schedule a em{font-style:normal;color:#087bbf;font-size:9px;font-weight:950;white-space:nowrap}.hq-schedule-grid p{margin:0;padding:16px 0;color:#7a858f;font-size:11px}.hq-schedule-empty{display:grid;gap:5px;place-items:center;margin-top:18px;padding:24px;border-radius:13px;background:#f6f8fa;text-align:center}.hq-schedule-empty svg{color:#16824c}.hq-schedule-empty span{color:#687385;font-size:11px}.hq-schedule-error{margin-top:16px;padding:11px;border-radius:10px;background:#ffe8e8;color:#9f2020;font-weight:800}@media(max-width:900px){.hq-schedule-grid{grid-template-columns:1fr}}@media(max-width:560px){.hq-schedule{padding:16px}.hq-schedule h2{font-size:36px}.hq-schedule a{grid-template-columns:auto minmax(0,1fr) auto}.hq-schedule a>svg{display:none}}`
