import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

type Session={access_token:string}
type Draft={title:string;subtitle:string;summary:string;body:string;socialCaption:string}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function readSession():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}

export default function MediaAiNewsStudio({clubId}:{clubId:string}){
 const[current]=useState(()=>readSession());const[type,setType]=useState('MATCH_PREVIEW');const[tone,setTone]=useState('PROFESSIONAL');const[details,setDetails]=useState('');const[author,setAuthor]=useState('');const[draft,setDraft]=useState<Draft|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[copied,setCopied]=useState('')
 const headers=useMemo<Record<string,string>>(()=>{const next:Record<string,string>={'content-type':'application/json'};if(current)next.authorization=`Bearer ${current.access_token}`;return next},[current])
 async function generate(){setBusy(true);setError('');setCopied('');try{const response=await fetch(`/api/club-portal/ai-graphics/clubs/${encodeURIComponent(clubId)}/news-draft`,{method:'POST',headers,body:JSON.stringify({type,tone,details,author})});const payload=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(payload.error||'Unable to generate article');setDraft(payload.data as Draft)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to generate article')}finally{setBusy(false)}}
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setCopied(label)}
 return <section className="mans"><header><span>AI NEWS STUDIO</span><h2>Create club news</h2><p>Choose the story, add the facts, and PlayFooty will prepare the headline, summary, article and social caption.</p></header><div className="mans-grid"><div className="mans-controls"><label>Story type<select value={type} onChange={e=>setType(e.target.value)}><option value="MATCH_PREVIEW">Match preview</option><option value="MATCH_REPORT">Match report</option><option value="TEAM_SELECTION">Team selection announcement</option><option value="MILESTONE">Milestone</option><option value="SPONSOR">Sponsor announcement</option><option value="SIGNING">Player signing</option><option value="CLUB_UPDATE">General club update</option></select></label><label>Tone<select value={tone} onChange={e=>setTone(e.target.value)}><option value="PROFESSIONAL">Professional</option><option value="ENERGETIC">Energetic</option><option value="COMMUNITY">Community</option><option value="CONCISE">Concise</option></select></label><label>Key facts<textarea rows={9} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Opponent, score, player names, milestone, sponsor details, quotes or anything the article must include."/></label><label>Author<input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Club name or media manager"/></label><button disabled={busy||!details.trim()} onClick={()=>void generate()}>{busy?'Writing…':'Generate AI article'}</button>{error&&<p className="mans-error">{error}</p>}</div><div className="mans-output">{draft?<><label>Headline<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Subheadline<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})}/></label><label>Summary<textarea rows={3} value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><label>Article<textarea rows={14} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><label>Social caption<textarea rows={5} value={draft.socialCaption} onChange={e=>setDraft({...draft,socialCaption:e.target.value})}/></label><div className="mans-actions"><button onClick={()=>void copy(`${draft.title}\n\n${draft.body}`,'Article copied')}>Copy article</button><button onClick={()=>void copy(draft.socialCaption,'Caption copied')}>Copy caption</button><Link to={`/club-portal/${clubId}/news`}>Open publisher</Link></div>{copied&&<p className="mans-success">{copied}</p>}</>:<div className="mans-empty">Your AI-generated article will appear here.</div>}</div></div><style>{styles}</style></section>
}
const styles=`.mans{padding:20px;border:1px solid #dce4ea;border-radius:18px;background:#fff}.mans header span{color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.mans h2{margin:5px 0;font:52px/1 'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mans header p{color:#687385}.mans-grid{display:grid;grid-template-columns:360px 1fr;gap:20px}.mans-controls,.mans-output{display:grid;align-content:start;gap:12px}.mans label{display:grid;gap:6px;color:#687385;font-size:10px;font-weight:900;text-transform:uppercase}.mans input,.mans select,.mans textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #ccd7df;border-radius:10px;background:#fff;font:inherit}.mans-controls>button,.mans-actions button,.mans-actions a{border:0;border-radius:10px;padding:13px;background:#35b6ff;color:#071019;text-align:center;text-decoration:none;font-weight:950;text-transform:uppercase}.mans-output{min-height:430px;padding:16px;border-radius:14px;background:#eef3f7}.mans-actions{display:flex;gap:8px;flex-wrap:wrap}.mans-actions button,.mans-actions a{flex:1;background:#111318;color:#fff}.mans-empty{align-self:center;text-align:center;color:#7b8791;font-weight:800}.mans-error{color:#a51d16;font-weight:800}.mans-success{color:#167343;font-weight:800}@media(max-width:800px){.mans-grid{grid-template-columns:1fr}}`