import { useMemo, useState } from 'react'
import { MediaCreationWorkflow, MediaReviewActions, MediaWorkflowPanel } from './MediaCreationWorkflow'

type Session={access_token:string}
type Graphic={dataUrl:string;filename:string}
type Club={clubName:string;logoUrl:string|null;primaryColour:string|null;secondaryColour:string|null}
const SESSION_KEY='playfooty.clubPortal.session.v1'
const TYPES=['DEBUT','50 GAMES','100 GAMES','150 GAMES','200 GAMES','250 GAMES','300 GAMES','FIRST GOAL','50 GOALS','100 GOALS','AWARD','PREMIERSHIP']
function session():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read player image'));reader.readAsDataURL(file)})}
function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Image could not be loaded'));image.src=url})}
function cover(ctx:CanvasRenderingContext2D,image:HTMLImageElement,w:number,h:number){const scale=Math.max(w/image.width,h/image.height);const dw=image.width*scale,dh=image.height*scale;ctx.drawImage(image,(w-dw)/2,(h-dh)/2,dw,dh)}

export default function MediaMilestoneStudio({clubId}:{clubId:string}){
 const[current]=useState(()=>session());const[type,setType]=useState('100 GAMES');const[player,setPlayer]=useState('');const[note,setNote]=useState('');const[photo,setPhoto]=useState('');const[graphic,setGraphic]=useState<Graphic|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[status,setStatus]=useState('')
 const headers=useMemo<Record<string,string>>(()=>{const next:Record<string,string>={};if(current)next.authorization=`Bearer ${current.access_token}`;return next},[current])
 const currentStep=busy?4:graphic?(status.includes('Saved')?6:5):photo&&player.trim()?3:player.trim()?2:1
 async function generate(){if(!player.trim())return setError('Enter the player name.');if(!photo)return setError('Upload a player photo.');setBusy(true);setError('');setStatus('Building milestone graphic…');try{const clubResponse=await fetch(`/api/clubs/${encodeURIComponent(clubId)}`);const clubPayload=await clubResponse.json().catch(()=>({})) as{data?:Club};const club=clubPayload.data;if(!club)throw new Error('Club details could not be loaded');const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image canvas unavailable');const image=await loadImage(photo);cover(ctx,image,1080,1350);const fade=ctx.createLinearGradient(0,430,0,1350);fade.addColorStop(0,'rgba(0,0,0,0)');fade.addColorStop(.48,'rgba(0,0,0,.38)');fade.addColorStop(1,'rgba(0,0,0,.94)');ctx.fillStyle=fade;ctx.fillRect(0,350,1080,1000);const accent=club.secondaryColour||'#ffffff';let logo:HTMLImageElement|null=null;if(club.logoUrl){try{logo=await loadImage(club.logoUrl)}catch{logo=null}}if(logo){const scale=Math.min(125/logo.width,125/logo.height);ctx.drawImage(logo,62,55,logo.width*scale,logo.height*scale)}ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=12;ctx.fillStyle=accent;ctx.font='900 32px Arial';ctx.fillText('MILESTONE',62,930);ctx.fillStyle='#fff';ctx.font='900 118px Arial';ctx.fillText(type,62,1060);ctx.font='900 58px Arial';ctx.fillText(player.trim().toUpperCase(),62,1145);ctx.fillStyle='rgba(255,255,255,.86)';ctx.font='700 25px Arial';const detail=note.trim()||`Congratulations from everyone at ${club.clubName}.`;ctx.fillText(detail.slice(0,70),62,1210);ctx.font='800 22px Arial';ctx.fillText(club.clubName.toUpperCase(),62,1285);ctx.shadowColor='transparent';const filename=`${club.clubName}-${player}-${type}.png`.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');setGraphic({dataUrl:canvas.toDataURL('image/png'),filename});setStatus('Milestone graphic ready')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to generate milestone graphic')}finally{setBusy(false)}}
 async function save(){if(!graphic)return;setBusy(true);setError('');setStatus('Saving to Media Library…');try{const response=await fetch(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({dataUrl:graphic.dataUrl,contentType:'image/png',title:graphic.filename.replace(/\.png$/,''),mediaType:'MILESTONE',status:'READY',width:1080,height:1350,tags:['generated','milestone',type.toLowerCase()]})});if(!response.ok)throw new Error('Unable to save milestone graphic');setStatus('Saved to Media Library')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save milestone graphic')}finally{setBusy(false)}}
 function download(){if(!graphic)return;const a=document.createElement('a');a.href=graphic.dataUrl;a.download=graphic.filename;a.click()}
 return <section className="mms"><header><span>MILESTONE STUDIO</span><h2>Player milestone</h2><p>Upload a real player image and turn it into a club-branded milestone post.</p></header><MediaCreationWorkflow currentStep={currentStep} busy={busy} status={status}><div className="mms-grid"><div className="mms-controls"><MediaWorkflowPanel step={1} title="Choose the achievement" description="Select the milestone the club is celebrating."><label>Milestone<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(value=><option key={value}>{value}</option>)}</select></label></MediaWorkflowPanel><MediaWorkflowPanel step={2} title="Add player details" description="Use the real player name, photo and optional club message."><label>Player name<input value={player} onChange={e=>setPlayer(e.target.value)} placeholder="Player name"/></label><label>Optional message<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Short congratulatory line"/></label><label>Player photo<input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void fileData(file).then(setPhoto)}}/></label>{photo&&<img className="mms-thumb" src={photo} alt="Player upload"/>}</MediaWorkflowPanel><MediaWorkflowPanel step={3} title="Confirm club style" description="The graphic uses the club logo and saved club colours automatically."><div className="mms-brand-note">Club branding will be applied from the club profile.</div></MediaWorkflowPanel><button className="mms-generate" disabled={busy} onClick={()=>void generate()}>{busy?'Generating…':'Generate milestone graphic'}</button>{error&&<p className="mms-error">{error}</p>}</div><MediaWorkflowPanel step={5} title="Review and use" description="Check the completed image before saving or sharing it." className="mms-review"><div className="mms-preview">{graphic?<><img src={graphic.dataUrl} alt="Generated milestone graphic"/><MediaReviewActions><button onClick={download}>Download</button><button disabled={busy} onClick={()=>void save()}>Save to library</button></MediaReviewActions></>:<div>Your milestone graphic will appear here.</div>}</div></MediaWorkflowPanel></div></MediaCreationWorkflow><style>{styles}</style></section>
}
const styles=`.mms{padding:20px;border:1px solid #dce4ea;border-radius:18px;background:#fff}.mms>header span{color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.mms h2{margin:5px 0;font:52px/1 'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mms>header p{color:#687385}.mms-grid{display:grid;grid-template-columns:380px 1fr;gap:18px}.mms-controls{display:grid;align-content:start;gap:12px}.mms label{display:grid;gap:6px;margin-top:10px;font-size:10px;font-weight:900;text-transform:uppercase;color:#687385}.mms select,.mms input{box-sizing:border-box;width:100%;padding:11px;border:1px solid #ccd7df;border-radius:10px;background:#fff}.mms-thumb{width:100%;max-height:210px;object-fit:cover;border-radius:12px}.mms-generate,.mms-preview button{border:0;border-radius:10px;padding:13px;background:#35b6ff;font-weight:950;text-transform:uppercase}.mms-brand-note{padding:12px;border-radius:10px;background:#eef7fc;color:#406070;font-size:12px;font-weight:750}.mms-review{align-self:start}.mms-preview{min-height:430px;display:grid;place-items:center;overflow:hidden;border-radius:14px;background:#eef3f7;color:#7b8791;font-weight:800}.mms-preview img{display:block;width:min(100%,520px)}.mms-preview .mcw-actions{width:100%;padding:12px;box-sizing:border-box;background:#fff}.mms-preview button{background:#111318;color:#fff}.mms-error{padding:10px 12px;border-radius:10px;background:#ffe8e8;color:#a51d16;font-weight:800}@media(max-width:800px){.mms-grid{grid-template-columns:1fr}}`
