import { useEffect, useMemo, useState } from 'react'

type Session={access_token:string}
type LiveMatch={roundLabel?:string;opponentName?:string;quarter?:number;elapsedSeconds?:number;homeGoals?:number;homeBehinds?:number;awayGoals?:number;awayBehinds?:number;status?:string}
type Club={clubName:string;logoUrl:string|null;primaryColour:string|null;secondaryColour:string|null}
type Graphic={dataUrl:string;filename:string}
const SESSION_KEY='playfooty.clubPortal.session.v1'
function readSession():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null}catch{return null}}
function readFile(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read image'));reader.readAsDataURL(file)})}
function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Image could not be loaded'));image.src=url})}
function total(goals:number,behinds:number){return goals*6+behinds}
function quarterLabel(value:number){return value===1?'QUARTER TIME':value===2?'HALF TIME':value===3?'THREE QUARTER TIME':value===4?'FULL TIME':'LIVE SCORE'}

export default function MediaLiveMatchStudio({clubId}:{clubId:string}){
 const[current]=useState(()=>readSession());const[live,setLive]=useState<LiveMatch|null>(null);const[club,setClub]=useState<Club|null>(null);const[photo,setPhoto]=useState('');const[graphic,setGraphic]=useState<Graphic|null>(null);const[caption,setCaption]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[updateType,setUpdateType]=useState('AUTO')
 const headers=useMemo<Record<string,string>>(()=>{const next:Record<string,string>={};if(current)next.authorization=`Bearer ${current.access_token}`;return next},[current])
 useEffect(()=>{let active=true;Promise.all([fetch(`/api/live-match/clubs/${encodeURIComponent(clubId)}`,{headers}).then(async r=>{const p=await r.json().catch(()=>({}));return r.ok?(p.data||p):null}),fetch(`/api/clubs/${encodeURIComponent(clubId)}`).then(async r=>{const p=await r.json().catch(()=>({}));return r.ok?(p.data||null):null})]).then(([match,nextClub])=>{if(!active)return;setLive(match as LiveMatch|null);setClub(nextClub as Club|null)}).catch(()=>{if(active)setError('Unable to load live match data')});return()=>{active=false}},[clubId,headers])
 async function generate(){if(!live||!club)return setError('No live match is available.');setBusy(true);setError('');try{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image canvas unavailable');if(photo){const image=await loadImage(photo);const scale=Math.max(1080/image.width,1350/image.height);const w=image.width*scale,h=image.height*scale;ctx.drawImage(image,(1080-w)/2,(1350-h)/2,w,h)}else{const gradient=ctx.createLinearGradient(0,0,0,1350);gradient.addColorStop(0,club.primaryColour||'#101820');gradient.addColorStop(1,'#050608');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350)}const fade=ctx.createLinearGradient(0,760,0,1350);fade.addColorStop(0,'rgba(0,0,0,0)');fade.addColorStop(.35,'rgba(0,0,0,.58)');fade.addColorStop(1,'rgba(0,0,0,.94)');ctx.fillStyle=fade;ctx.fillRect(0,700,1080,650);const accent=club.secondaryColour||'#ffffff';let logo:HTMLImageElement|null=null;if(club.logoUrl){try{logo=await loadImage(club.logoUrl)}catch{logo=null}}if(logo){const scale=Math.min(125/logo.width,125/logo.height);ctx.drawImage(logo,62,58,logo.width*scale,logo.height*scale)}const homeGoals=live.homeGoals||0,homeBehinds=live.homeBehinds||0,awayGoals=live.awayGoals||0,awayBehinds=live.awayBehinds||0;const label=updateType==='AUTO'?quarterLabel(live.quarter||0):updateType;ctx.shadowColor='rgba(0,0,0,.85)';ctx.shadowBlur=10;ctx.fillStyle=accent;ctx.font='900 28px Arial';ctx.fillText(label,62,930);ctx.fillStyle='#fff';ctx.font='900 52px Arial';ctx.fillText(club.clubName.toUpperCase(),62,1005);ctx.font='900 30px Arial';ctx.fillText(`V ${(live.opponentName||'OPPOSITION').toUpperCase()}`,62,1052);ctx.font='900 96px Arial';ctx.fillText(`${homeGoals}.${homeBehinds}`,62,1160);ctx.textAlign='right';ctx.fillText(`${awayGoals}.${awayBehinds}`,1018,1160);ctx.font='900 42px Arial';ctx.fillText(String(total(awayGoals,awayBehinds)),1018,1220);ctx.textAlign='left';ctx.fillText(String(total(homeGoals,homeBehinds)),62,1220);ctx.fillStyle='rgba(255,255,255,.82)';ctx.font='800 22px Arial';ctx.fillText(`${live.roundLabel||''} · Q${live.quarter||'-'}`,62,1288);ctx.shadowColor='transparent';const filename=`${club.clubName}-${label}-score.png`.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');setGraphic({dataUrl:canvas.toDataURL('image/png'),filename});setCaption(`${label}: ${club.clubName} ${homeGoals}.${homeBehinds} (${total(homeGoals,homeBehinds)}) – ${(live.opponentName||'Opposition')} ${awayGoals}.${awayBehinds} (${total(awayGoals,awayBehinds)}).`)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to generate score graphic')}finally{setBusy(false)}}
 async function saveLibrary(){if(!graphic)return;const response=await fetch(`/api/club-portal/media/clubs/${encodeURIComponent(clubId)}/upload`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({dataUrl:graphic.dataUrl,contentType:'image/png',title:graphic.filename.replace(/\.png$/,''),mediaType:'MATCH',status:'READY',width:1080,height:1350,tags:['generated','live-match']})});if(!response.ok)setError('Unable to save graphic to the library')}
 function download(){if(!graphic)return;const a=document.createElement('a');a.href=graphic.dataUrl;a.download=graphic.filename;a.click()}
 return <section className="mlm"><header><span>LIVE MATCH STUDIO</span><h2>Score update</h2><p>Use the current PlayFooty score or place it over a real match photo.</p></header><div className="mlm-grid"><div className="mlm-controls"><div className="mlm-score"><strong>{club?.clubName||'Your club'}</strong><b>{live?.homeGoals||0}.{live?.homeBehinds||0}</b><span>{total(live?.homeGoals||0,live?.homeBehinds||0)}</span><em>v</em><strong>{live?.opponentName||'Opposition'}</strong><b>{live?.awayGoals||0}.{live?.awayBehinds||0}</b><span>{total(live?.awayGoals||0,live?.awayBehinds||0)}</span></div><label>Update type<select value={updateType} onChange={e=>setUpdateType(e.target.value)}><option value="AUTO">Use current quarter</option><option>QUARTER TIME</option><option>HALF TIME</option><option>THREE QUARTER TIME</option><option>FULL TIME</option><option>LIVE SCORE</option></select></label><label className="mlm-upload">Match photo<input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void readFile(file).then(setPhoto)}}/></label>{photo&&<img className="mlm-thumb" src={photo} alt="Uploaded match"/>}<button disabled={busy||!live} onClick={()=>void generate()}>{busy?'Generating…':'Generate score graphic'}</button>{caption&&<textarea value={caption} onChange={e=>setCaption(e.target.value)} rows={4}/>} {error&&<p className="mlm-error">{error}</p>}</div><div className="mlm-preview">{graphic?<><img src={graphic.dataUrl} alt="Generated live score graphic"/><div><button onClick={download}>Download</button><button onClick={()=>void saveLibrary()}>Save to library</button></div></>:<div>Generated score graphic will appear here.</div>}</div></div><style>{styles}</style></section>
}
const styles=`.mlm{padding:20px;border:1px solid #dce4ea;border-radius:18px;background:#fff}.mlm header span{color:#0783c9;font-size:10px;font-weight:950;letter-spacing:.16em}.mlm h2{margin:5px 0;font:52px/1 'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mlm header p{color:#687385}.mlm-grid{display:grid;grid-template-columns:360px 1fr;gap:20px}.mlm-controls{display:grid;align-content:start;gap:12px}.mlm-score{display:grid;grid-template-columns:1fr auto auto;gap:5px 10px;padding:14px;border-radius:13px;background:#111820;color:#fff}.mlm-score em{grid-column:1/-1;text-align:center;color:#7dd5ff}.mlm-score b{font-size:25px}.mlm-score span{color:#7dd5ff;font-weight:900}.mlm label{display:grid;gap:6px;font-size:10px;font-weight:900;text-transform:uppercase;color:#687385}.mlm select,.mlm textarea,.mlm input{box-sizing:border-box;width:100%;padding:11px;border:1px solid #ccd7df;border-radius:10px;background:#fff}.mlm-controls>button,.mlm-preview button{border:0;border-radius:10px;padding:13px;background:#35b6ff;font-weight:950;text-transform:uppercase}.mlm-thumb{width:100%;max-height:180px;object-fit:cover;border-radius:12px}.mlm-preview{min-height:430px;display:grid;place-items:center;overflow:hidden;border-radius:14px;background:#eef3f7;color:#7b8791;font-weight:800}.mlm-preview img{display:block;width:min(100%,520px)}.mlm-preview>div:not(:only-child){display:flex}.mlm-preview>div:last-child{width:100%;display:flex;gap:8px;padding:12px;box-sizing:border-box;background:#fff}.mlm-preview button{flex:1;background:#111318;color:#fff}.mlm-error{color:#a51d16;font-weight:800}@media(max-width:800px){.mlm-grid{grid-template-columns:1fr}}`