import { useEffect, useMemo, useState } from 'react'
import { BarChart3, ChevronDown, X } from 'lucide-react'

type SessionAuth = { access_token?: string }
type Status = 'ATTENDED'|'LATE'|'MODIFIED'|'EXCUSED'|'ABSENT'|'INJURED'
type Player = { id:string; playerName:string; jumperNumber:number|null }
type TrainingSession = { id:string; sessionDate:string; finishedAt:string|null }
type Attendance = { sessionId:string; clubPlayerId:string; status:Status; leftEarly:boolean; missedPercentage:number|null }
type RecordRow = Player & { attendance:number; timeAttendance:number; sessions:number; attended:number; late:number; modified:number; absent:number; excused:number; injured:number; leftEarly:number; totalMissed:number }

const SESSION_KEY='playfooty.clubPortal.session.v1'
function token(){try{const raw=localStorage.getItem(SESSION_KEY);return raw?(JSON.parse(raw) as SessionAuth).access_token||'':''}catch{return ''}}

export default function TrainingRecordsPanel({clubId}:{clubId:string}){
 const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[players,setPlayers]=useState<Player[]>([]);const[sessions,setSessions]=useState<TrainingSession[]>([]);const[attendance,setAttendance]=useState<Attendance[]>([]);const[sort,setSort]=useState<'attendance'|'name'>('attendance')
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);setError('');fetch(`/api/club-portal/training/clubs/${encodeURIComponent(clubId)}`,{headers:{authorization:`Bearer ${token()}`}}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load training records');return p}).then(p=>{if(!active)return;const d=p.data||{};setPlayers(Array.isArray(d.players)?d.players:[]);setSessions(Array.isArray(d.sessions)?d.sessions:[]);setAttendance(Array.isArray(d.attendance)?d.attendance:[])}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load training records')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[open,clubId])
 const rows=useMemo<RecordRow[]>(()=>{const finished=new Set(sessions.filter(s=>s.finishedAt).map(s=>s.id));const total=finished.size;return players.map(player=>{const records=attendance.filter(a=>a.clubPlayerId===player.id&&finished.has(a.sessionId));const count=(status:Status)=>records.filter(a=>a.status===status).length;const attended=count('ATTENDED'),late=count('LATE'),modified=count('MODIFIED'),absent=count('ABSENT'),excused=count('EXCUSED'),injured=count('INJURED');const participated=attended+late+modified;const missed=records.reduce((sum,a)=>sum+(a.leftEarly?Number(a.missedPercentage||0):0),0);const timeCredit=records.reduce((sum,a)=>sum+(['ATTENDED','LATE','MODIFIED'].includes(a.status)?Math.max(0,100-(a.leftEarly?Number(a.missedPercentage||0):0)):0),0);return{...player,sessions:total,attendance:total?Math.round(participated/total*100):0,timeAttendance:total?Math.round(timeCredit/total):0,attended,late,modified,absent,excused,injured,leftEarly:records.filter(a=>a.leftEarly).length,totalMissed:missed}}).sort((a,b)=>sort==='name'?a.playerName.localeCompare(b.playerName):b.attendance-a.attendance||b.timeAttendance-a.timeAttendance||a.playerName.localeCompare(b.playerName))},[players,sessions,attendance,sort])
 return <><button className="training-records-launch" onClick={()=>setOpen(true)}><BarChart3 size={18}/>Training records</button>{open&&<div className="training-records-backdrop" role="dialog" aria-modal="true" aria-label="Training records"><section className="training-records-panel"><header><div><span>Coaching Portal</span><h2>Training records</h2><p>Only finished training sessions count toward season records.</p></div><button onClick={()=>setOpen(false)} aria-label="Close training records"><X size={22}/></button></header><div className="training-records-tools"><strong>{sessions.filter(s=>s.finishedAt).length} finished sessions</strong><label>Sort<select value={sort} onChange={e=>setSort(e.target.value as 'attendance'|'name')}><option value="attendance">Attendance %</option><option value="name">Player name</option></select><ChevronDown size={15}/></label></div>{loading?<div className="training-records-state">Loading records…</div>:error?<div className="training-records-state error">{error}</div>:<div className="training-records-list">{rows.map(row=><article key={row.id}><div className="training-records-player"><strong>{row.jumperNumber?`${row.jumperNumber}. `:''}{row.playerName}</strong><span>{row.sessions} finished session{row.sessions===1?'':'s'}</span></div><div className="training-records-rate"><b>{row.attendance}%</b><span>Attendance</span></div><div className="training-records-rate"><b>{row.timeAttendance}%</b><span>Time attended</span></div><div className="training-records-detail"><span>Attended <b>{row.attended}</b></span><span>Late <b>{row.late}</b></span><span>Modified <b>{row.modified}</b></span><span>Absent <b>{row.absent}</b></span><span>Excused <b>{row.excused}</b></span><span>Injured <b>{row.injured}</b></span><span>Left early <b>{row.leftEarly}</b></span><span>Training missed <b>{row.totalMissed}%</b></span></div></article>)}</div>}</section></div>}<style>{styles}</style></>
}

const styles=`
.training-records-launch{position:fixed;right:18px;top:92px;z-index:100020;display:flex;align-items:center;gap:7px;border:0;border-radius:999px;background:#071018;color:#fff;padding:11px 15px;font-weight:900;text-transform:uppercase;box-shadow:0 8px 22px rgba(0,0,0,.22)}
.training-records-backdrop{position:fixed;inset:0;z-index:100050;background:rgba(4,10,15,.7);display:grid;place-items:center;padding:18px}
.training-records-panel{width:min(980px,100%);max-height:90vh;overflow:auto;background:#eef3f7;border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.35)}
.training-records-panel>header{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:16px;padding:20px;background:#071018;color:#fff}
.training-records-panel>header span{color:#42b8ff;font-size:10px;font-weight:950;letter-spacing:.16em;text-transform:uppercase}.training-records-panel h2{margin:4px 0 2px;font-family:'Bebas Neue',Impact,sans-serif;font-size:42px;line-height:1;text-transform:uppercase}.training-records-panel header p{margin:0;color:#b7c3cc;font-size:13px}.training-records-panel header button{align-self:flex-start;border:0;border-radius:50%;background:#fff;color:#111;width:40px;height:40px;display:grid;place-items:center}
.training-records-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:14px 16px}.training-records-tools label{position:relative;display:flex;align-items:center;gap:7px;font-size:11px;font-weight:900;text-transform:uppercase}.training-records-tools select{appearance:none;border:1px solid #cfd8df;border-radius:9px;background:#fff;padding:10px 34px 10px 11px;font-weight:800}.training-records-tools svg{position:absolute;right:10px;pointer-events:none}
.training-records-list{display:grid;gap:10px;padding:0 16px 18px}.training-records-list article{display:grid;grid-template-columns:minmax(190px,1.4fr) 110px 120px minmax(280px,2fr);gap:12px;align-items:center;background:#fff;border:1px solid #dce4ea;border-radius:13px;padding:14px}.training-records-player span,.training-records-rate span{display:block;color:#74818c;font-size:10px}.training-records-rate b{font-family:'Bebas Neue',Impact,sans-serif;font-size:30px}.training-records-detail{display:grid;grid-template-columns:repeat(4,minmax(80px,1fr));gap:6px}.training-records-detail span{display:flex;justify-content:space-between;gap:6px;border-radius:7px;background:#f3f6f8;padding:7px;font-size:9px;text-transform:uppercase;color:#64717c}.training-records-detail b{color:#111}.training-records-state{padding:60px 20px;text-align:center;font-weight:800}.training-records-state.error{color:#a51f28}
@media(max-width:760px){.training-records-launch{top:auto;right:12px;bottom:18px;padding:12px 14px}.training-records-backdrop{padding:0}.training-records-panel{width:100%;height:100%;max-height:none;border-radius:0}.training-records-panel h2{font-size:36px}.training-records-list article{grid-template-columns:1fr 92px 100px}.training-records-detail{grid-column:1/-1;grid-template-columns:repeat(2,1fr)}.training-records-tools{position:sticky;top:105px;z-index:1;background:#eef3f7}}
`
