import { useState } from 'react'
import { Check, FileSpreadsheet, LoaderCircle, Upload, XCircle } from 'lucide-react'

type Product={id:string;name:string;status:string;season:string|null;priceCents:number}
type Row={firstName:string;lastName:string;email:string;phone:string;membershipNumber:string;status:string;season:string;paymentMethod:string;amountCents:number|null}
const aliases:Record<keyof Omit<Row,'amountCents'>| 'amount',string[]>= {firstName:['firstname','first_name','givenname','given_name'],lastName:['lastname','last_name','surname','familyname'],email:['email','emailaddress'],phone:['phone','mobile','phonenumber'],membershipNumber:['membershipnumber','membership_number','membernumber','member_no'],status:['status'],season:['season','year'],paymentMethod:['paymentmethod','payment_method','payment','source'],amount:['amount','price','paid']}
function normal(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,'')}
function parseCsv(text:string){const records:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){row.push(cell.trim());cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))records.push(row);row=[];cell=''}else cell+=char}row.push(cell.trim());if(row.some(Boolean))records.push(row);return records}
function mapped(records:string[][]):Row[]{if(records.length<2)return[];const headers=records[0].map(normal),column=(key:keyof typeof aliases)=>headers.findIndex(header=>aliases[key].map(normal).includes(header));return records.slice(1).map(values=>{const value=(key:keyof typeof aliases)=>{const index=column(key);return index<0?'':String(values[index]||'').trim()},amount=value('amount').replace(/[$,]/g,'');return{firstName:value('firstName'),lastName:value('lastName'),email:value('email'),phone:value('phone'),membershipNumber:value('membershipNumber'),status:value('status').toUpperCase()||'ACTIVE',season:value('season'),paymentMethod:value('paymentMethod').toUpperCase().replaceAll(' ','_')||'OTHER',amountCents:amount?Math.max(0,Math.round(Number(amount)||0)*100):null}}).filter(row=>row.firstName||row.lastName)}

export default function MembershipImport({clubId,token,products,onComplete}:{clubId:string;token:string;products:Product[];onComplete:()=>Promise<void>}){
 const[rows,setRows]=useState<Row[]>([]),[productId,setProductId]=useState(products.find(product=>product.status==='ACTIVE')?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[summary,setSummary]=useState<{imported:number;skipped:number;errors:string[]}|null>(null)
 async function choose(file:File){setError('');setSummary(null);const next=mapped(parseCsv(await file.text()));if(!next.length){setRows([]);setError('No member rows were found. Include first name and/or last name columns.');return}setRows(next.slice(0,500))}
 async function commit(){if(!productId||!rows.length)return;setBusy(true);setError('');try{const response=await fetch(`/api/club-portal/memberships/clubs/${clubId}/members/import`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({productId,rows})}),payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to import members');setSummary(payload.data);await onComplete()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to import members')}finally{setBusy(false)}}
 return <section className="mi"><style>{styles}</style><header><span>CSV MEMBER IMPORT</span><h2>Bring your existing members across.</h2><p>Upload up to 500 people, preview them, then add them to the canonical Membership system.</p></header>{error&&<div className="mi-error"><XCircle/>{error}</div>}{summary?<div className="mi-summary"><Check/><h3>{summary.imported} members imported</h3><p>{summary.skipped} rows safely skipped.{summary.errors.length?` ${summary.errors.slice(0,3).join(' ')}`:''}</p><button onClick={()=>{setRows([]);setSummary(null)}}>Import another file</button></div>:<><div className="mi-steps"><label><b>1</b><span><strong>Choose membership type</strong><select value={productId} onChange={event=>setProductId(event.target.value)}><option value="">Select membership type</option>{products.filter(product=>product.status!=='ARCHIVED').map(product=><option key={product.id} value={product.id}>{product.name}{product.season?` · ${product.season}`:''}</option>)}</select></span></label><label className="mi-upload"><b>2</b><span><strong>Choose CSV file</strong><small>Recognised columns: first name, last name, email, phone, membership number, status, season, payment method and amount.</small><input type="file" accept=".csv,text/csv" onChange={event=>event.target.files?.[0]&&void choose(event.target.files[0])}/><em><Upload/>Select CSV</em></span></label></div>{rows.length>0&&<><div className="mi-preview"><header><div><span>PREVIEW</span><h3>{rows.length} member rows ready</h3></div><small>Only the first 500 rows are included.</small></header>{rows.slice(0,8).map((row,index)=><article key={`${row.email}-${index}`}><i>{row.firstName.slice(0,1)}{row.lastName.slice(0,1)}</i><span><strong>{`${row.firstName} ${row.lastName}`.trim()}</strong><small>{row.email||row.phone||'No contact details'}{row.membershipNumber?` · #${row.membershipNumber}`:''}</small></span><em>{row.status}</em></article>)}{rows.length>8&&<p>+ {rows.length-8} more rows</p>}</div><button className="mi-import" disabled={busy||!productId} onClick={()=>void commit()}>{busy?<LoaderCircle/>:<FileSpreadsheet/>}Import {rows.length} members</button></>}</>}</section>
}
const styles=`.mi{display:grid;gap:14px}.mi>header{padding:24px;border-radius:18px;background:linear-gradient(120deg,#07131c,#143247);color:#fff}.mi>header span,.mi-preview header span{color:#42b8ff;font-size:9px;font-weight:950;letter-spacing:.14em}.mi h2,.mi h3{font-family:'Bebas Neue',Impact,sans-serif;text-transform:uppercase}.mi>header h2{margin:5px 0;font-size:42px}.mi>header p{margin:0;color:#bac8d2}.mi-steps{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mi-steps>label{display:grid;grid-template-columns:48px 1fr;gap:12px;padding:20px;border:1px solid #d7e1e7;border-radius:17px;background:#fff}.mi-steps b{display:grid;place-items:center;width:44px;height:44px;border-radius:13px;background:#e5f4fc;color:#128fd0;font-size:22px}.mi-steps span{display:grid;gap:7px}.mi-steps select{min-height:48px;padding:0 10px;border:1px solid #cad7df;border-radius:9px;background:#fff}.mi-upload input{position:absolute;opacity:0;pointer-events:none}.mi-upload em,.mi-import,.mi-summary button{display:flex;align-items:center;justify-content:center;gap:7px;min-height:48px;padding:0 16px;border:0;border-radius:10px;background:#42b8ff;color:#07131c;font-style:normal;font-weight:950;text-transform:uppercase;cursor:pointer}.mi-upload small{color:#687985}.mi-preview{padding:17px;border:1px solid #d7e1e7;border-radius:17px;background:#fff}.mi-preview>header{display:flex;justify-content:space-between;align-items:end}.mi-preview h3{margin:3px 0;font-size:30px}.mi-preview article{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:10px;padding:10px 0;border-top:1px solid #e1e8ec}.mi-preview article i{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:#102432;color:#42b8ff;font-style:normal;font-weight:950}.mi-preview article span{display:grid}.mi-preview article small{color:#71808b}.mi-preview article em{font-size:9px;font-style:normal;font-weight:950}.mi-import{justify-self:end}.mi-summary{display:grid;justify-items:center;padding:38px;border-radius:17px;background:#e8f8ee;text-align:center;color:#126c3c}.mi-summary>svg{width:44px;height:44px}.mi-summary h3{margin:8px 0 0;font-size:36px}.mi-error{display:flex;align-items:center;gap:7px;padding:12px;border-radius:10px;background:#fff0f0;color:#a51d1d;font-weight:850}@media(max-width:700px){.mi-steps{grid-template-columns:1fr}.mi>header{padding:18px}.mi>header h2{font-size:34px}.mi-import{width:100%}}`
