from pathlib import Path

def once(text, old, new, label):
    if old not in text: raise SystemExit(f'Missing {label}')
    return text.replace(old,new,1)

p=Path('backend/api/index.ts');s=p.read_text()
s=once(s,"import { aiAssistantCoachRouter } from '../src/api/routes/ai-assistant-coach.js'","import { aiAssistantCoachRouter } from '../src/api/routes/ai-assistant-coach.js'\nimport { matchReportRouter } from '../src/api/routes/match-report.js'",'route import')
s=once(s,"app.use('/api/ai-assistant-coach', aiAssistantCoachRouter)","app.use('/api/ai-assistant-coach', aiAssistantCoachRouter)\napp.use('/api/match-report', matchReportRouter)",'route mount')
p.write_text(s)

p=Path('src/pages/CoachAppMatchDay.tsx');s=p.read_text()
s=once(s,"import { Minus, Pause, Play, Plus, RefreshCw, SkipForward, Wifi, WifiOff } from 'lucide-react'","import { Download, FileText, Minus, Pause, Play, Plus, RefreshCw, SkipForward, Wifi, WifiOff, X } from 'lucide-react'",'icons')
s=once(s,"type Sheet = { id:string; roundLabel:string; opponentName:string|null; matchDate:string|null; status:string; players:Player[] }","type Sheet = { id:string; roundLabel:string; opponentName:string|null; matchDate:string|null; status:string; clubName?:string|null; clubLogoUrl?:string|null; players:Player[] }",'sheet type')
s=once(s,"type Props = { clubId:string; sheetId:string; token:string; onBack:()=>void; onGamePlan?:()=>void; onWhiteboard?:()=>void; onFullStats?:()=>void }","type MatchReport={headline:string;summary:string;keyStory:string;teamPerformance:string;playerHighlights:string[];rotationInsights:string[];areasToAddress:string[];nextFocus:string[]}\ntype Props = { clubId:string; sheetId:string; token:string; onBack:()=>void; onGamePlan?:()=>void; onWhiteboard?:()=>void }",'props')
s=once(s,"export default function CoachAppMatchDay({clubId,sheetId,token,onBack,onGamePlan,onWhiteboard,onFullStats}:Props){","export default function CoachAppMatchDay({clubId,sheetId,token,onBack,onGamePlan,onWhiteboard}:Props){",'function props')
s=once(s,"  const[error,setError]=useState('')","  const[error,setError]=useState('')\n  const[report,setReport]=useState<MatchReport|null>(null)\n  const[reportOpen,setReportOpen]=useState(false)\n  const[reportLoading,setReportLoading]=useState(false)\n  const[reportError,setReportError]=useState('')\n  const[reportType,setReportType]=useState<'quarter'|'full'>('quarter')\n  const reportCanvas=useRef<HTMLCanvasElement>(null)",'report state')
insert="""
  async function generateReport(){
    if(!state||!sheet)return
    const type: 'quarter'|'full'=state.quarter>=4?'full':'quarter'
    setReportType(type);setReportLoading(true);setReportError('');setReportOpen(true)
    const tracked=accrueTracking(state)
    const trackedSeconds=Math.max(1,tracked.totalTrackedSeconds)
    const snapshot={quarter:tracked.quarter,clock:formatTime(now(tracked)),round:sheet.roundLabel,matchDate:sheet.matchDate,score:{home:{name:sheet.clubName||'Your team',goals:tracked.homeGoals,behinds:tracked.homeBehinds,total:total(tracked.homeGoals,tracked.homeBehinds)},away:{name:sheet.opponentName||'Opposition',goals:tracked.awayGoals,behinds:tracked.awayBehinds,total:total(tracked.awayGoals,tracked.awayBehinds)}},teamStats:{...EMPTY_STATS,...(tracked.teamStats||{})},players:tracked.slots.map(slot=>({name:slot.playerName,jumperNumber:slot.jumperNumber,position:slot.positionCode,onGround:slot.onGround,injured:slot.injured,goals:slot.goals,behinds:slot.behinds,plusMinus:slot.plusMinus,onGroundSeconds:slot.onGroundSeconds,timeOnGroundPercent:Math.round(slot.onGroundSeconds/trackedSeconds*100),benchSeconds:slot.benchEnteredAt?Math.floor((Date.now()-slot.benchEnteredAt)/1000):0})),events:tracked.events.slice(0,80)}
    try{const response=await fetch('/api/match-report',{method:'POST',headers:jsonHeaders,body:JSON.stringify({type,quarter:tracked.quarter,club:{name:sheet.clubName||'Your team',logoUrl:sheet.clubLogoUrl||null},match:snapshot})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Unable to generate match report');setReport(payload.report);setTimeout(()=>drawReportImage(payload.report,type,tracked),40)}catch(value){setReportError(value instanceof Error?value.message:'Unable to generate match report')}finally{setReportLoading(false)}
  }
  function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number,line=31){const words=text.split(/\s+/);let row='';let yy=y;for(const word of words){const test=row?`${row} ${word}`:word;if(ctx.measureText(test).width>max&&row){ctx.fillText(row,x,yy);row=word;yy+=line}else row=test}if(row)ctx.fillText(row,x,yy);return yy+line}
  function drawReportImage(value:MatchReport,type:'quarter'|'full',current:MatchState){const canvas=reportCanvas.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;canvas.width=1400;canvas.height=1900;ctx.fillStyle='#07121b';ctx.fillRect(0,0,1400,1900);ctx.fillStyle='#39b8ff';ctx.fillRect(0,0,1400,18);ctx.fillStyle='#fff';ctx.font='900 54px Arial';ctx.fillText((sheet?.clubName||'PLAYFOOTY').toUpperCase(),80,100);if(sheet?.clubLogoUrl){const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{ctx.drawImage(img,1180,45,130,130)};img.src=sheet.clubLogoUrl}ctx.fillStyle='#39b8ff';ctx.font='900 30px Arial';ctx.fillText(type==='full'?'FULL-TIME MATCH REPORT':`QUARTER ${current.quarter} REPORT`,80,155);ctx.fillStyle='#fff';ctx.font='900 58px Arial';let y=245;y=wrap(ctx,value.headline,80,y,1230,66);ctx.fillStyle='#b8c8d3';ctx.font='700 29px Arial';const score=`${current.homeGoals}.${current.homeBehinds} (${total(current.homeGoals,current.homeBehinds)})  —  ${current.awayGoals}.${current.awayBehinds} (${total(current.awayGoals,current.awayBehinds)})`;ctx.fillText(score,80,y+10);y+=75;const section=(title:string,body:string|string[])=>{ctx.fillStyle='#39b8ff';ctx.font='900 25px Arial';ctx.fillText(title.toUpperCase(),80,y);y+=38;ctx.fillStyle='#fff';ctx.font='500 27px Arial';for(const item of Array.isArray(body)?body:[body]){y=wrap(ctx,Array.isArray(body)?`• ${item}`:item,80,y,1230,36);if(Array.isArray(body))y+=8}y+=28};section('Match summary',value.summary);section('Key story',value.keyStory);section('Team performance',value.teamPerformance);if(value.playerHighlights.length)section('Player highlights',value.playerHighlights);if(value.rotationInsights.length)section('Time on ground & rotations',value.rotationInsights);if(value.areasToAddress.length)section('Areas to address',value.areasToAddress);if(value.nextFocus.length)section(type==='full'?'Post-match focus':'Next quarter',value.nextFocus);ctx.fillStyle='#152a38';ctx.fillRect(0,1810,1400,90);ctx.fillStyle='#9fb4c2';ctx.font='700 22px Arial';ctx.fillText('Generated from live PlayFooty Match Day statistics',80,1865)}
  function saveReport(){const canvas=reportCanvas.current;if(!canvas)return;canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${(sheet?.clubName||'team').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${reportType}-report.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')}
"""
s=once(s,"  function toggleInjury(id:string){",insert+"\n  function toggleInjury(id:string){",'report functions')
s=once(s,"<KpiPanel stats={teamStats} scoreMargin={scoreMargin} onOpen={onFullStats}/>","<KpiPanel stats={teamStats} scoreMargin={scoreMargin} onOpen={()=>void generateReport()}/>",'kpi button')
s=once(s,"<button onClick={onFullStats} disabled={!onFullStats}>Full Stats</button>","<button onClick={()=>void generateReport()}><FileText/> Match Report</button>",'tool button')
s=once(s,"    <footer><button onClick={onBack}>Return to Select Side</button></footer>","    {reportOpen&&<div className=\"camd-report-modal\"><section><header><div><span>{reportType==='full'?'Full-time':'Quarter'} report</span><h2>Match Report</h2></div><button onClick={()=>setReportOpen(false)}><X/></button></header>{reportLoading?<div className=\"camd-report-loading\"><RefreshCw className=\"spin\"/><b>Writing professional match report…</b></div>:reportError?<div className=\"camd-report-loading\"><b>{reportError}</b><button onClick={()=>void generateReport()}>Try again</button></div>:report?<><canvas ref={reportCanvas}/><button className=\"camd-save-report\" onClick={saveReport}><Download/>Save image to iPad</button><small>On iPad, the image will open through the browser download/share controls so it can be saved to Photos or Files.</small></>:null}</section></div>}\n    <footer><button onClick={onBack}>Return to Select Side</button></footer>",'modal')
s=once(s,"function KpiPanel({stats,scoreMargin,onOpen}:{stats:TeamStats;scoreMargin:number;onOpen?:()=>void}){return <section className=\"camd-kpis\"><header><span>Live KPIs</span>{onOpen&&<button onClick={onOpen}>Full stats</button>}","function KpiPanel({stats,scoreMargin,onOpen}:{stats:TeamStats;scoreMargin:number;onOpen?:()=>void}){return <section className=\"camd-kpis\"><header><span>Live KPIs</span>{onOpen&&<button onClick={onOpen}>Match report</button>}",'kpi label')
css="""
.camd-tools button svg{width:16px;height:16px;vertical-align:middle;margin-right:5px}.camd-report-modal{position:fixed;z-index:3000;inset:0;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.78);backdrop-filter:blur(8px)}.camd-report-modal>section{width:min(900px,100%);max-height:94vh;overflow:auto;padding:16px;border:1px solid #315064;border-radius:18px;background:#0b1b26;box-shadow:0 24px 80px #000}.camd-report-modal header{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.camd-report-modal header span{color:#39b8ff;font-size:10px;font-weight:950;text-transform:uppercase}.camd-report-modal h2{margin:2px 0 0;font-family:'Bebas Neue',Impact,sans-serif;font-size:36px;text-transform:uppercase}.camd-report-modal header button{display:grid;place-items:center;width:42px;height:42px;border:1px solid #385367;border-radius:10px;background:#122b3a;color:#fff}.camd-report-modal canvas{display:block;width:100%;height:auto;border-radius:10px;background:#07121b}.camd-report-loading{min-height:360px;display:grid;place-items:center;align-content:center;gap:14px;text-align:center}.camd-report-loading svg{color:#39b8ff}.camd-report-loading button,.camd-save-report{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;margin-top:12px;padding:14px;border:0;border-radius:11px;background:#39b8ff;color:#061019;font-weight:950;text-transform:uppercase}.camd-report-modal>section>small{display:block;margin-top:9px;color:#9eb1be;text-align:center}
"""
pos=s.rfind("\n`")
if pos<0: raise SystemExit('Missing style close')
s=s[:pos]+css+s[pos:]
p.write_text(s)

p=Path('backend/.env.example');s=p.read_text()
if 'OPENAI_API_KEY=' not in s:s+='\nOPENAI_API_KEY=\nOPENAI_MATCH_REPORT_MODEL=gpt-5-mini\n'
p.write_text(s)
print('Added ChatGPT match reports and branded image export')
