from pathlib import Path
p=Path('src/pages/CoachAppWhiteboardStage2.tsx')
s=p.read_text()
s=s.replace("Save, Sparkles, Trash2", "Save, Share2, Cloud, History, Download, Sparkles, Trash2")
s=s.replace("type TacticalAnalysis={headline:string;summary:string;strengths:string[];risks:string[];adjustments:string[];coachMessage:string}", "type TacticalAnalysis={headline:string;summary:string;strengths:string[];risks:string[];adjustments:string[];coachMessage:string}\ntype CloudPlay={id:string;title:string;category:string;visibility:string;notes:string|null;fixtureLabel:string|null;play:PlayState;shareToken?:string|null;updatedAt:string}")
needle="  const[analysisScope,setAnalysisScope]=useState<'frame'|'play'>('frame')"
repl=needle+"\n  const[cloudOpen,setCloudOpen]=useState(false)\n  const[cloudPlays,setCloudPlays]=useState<CloudPlay[]>([])\n  const[cloudBusy,setCloudBusy]=useState(false)\n  const[cloudError,setCloudError]=useState('')\n  const[selectedCloudId,setSelectedCloudId]=useState('')\n  const[cloudCategory,setCloudCategory]=useState('General')\n  const[cloudNotes,setCloudNotes]=useState('')"
s=s.replace(needle,repl)
needle2="  function applyAdjustment(){if(!analysis?.adjustments?.[0])return;snapshot();const id=crypto.randomUUID();const frame:Frame={id,name:'AI adjustment',state:cloneBoard(state)};setPlay(current=>({...current,frames:[...current.frames,frame],activeFrameId:id}));setAnalysisOpen(false)}"
repl2=needle2+"\n  async function loadCloud(){setCloudBusy(true);setCloudError('');try{const r=await fetch(`/api/whiteboard-platform/clubs/${encodeURIComponent(clubId)}/plays`,{headers:{authorization:`Bearer ${token}`},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load cloud tactics');setCloudPlays(j.data||[]);setCloudOpen(true)}catch(e){setCloudError(e instanceof Error?e.message:'Unable to load cloud tactics');setCloudOpen(true)}finally{setCloudBusy(false)}}\n  async function saveCloud(){const title=prompt('Cloud tactic title',activeFrame.name||'Club tactic')?.trim();if(!title)return;setCloudBusy(true);setCloudError('');try{const method=selectedCloudId?'PUT':'POST';const url=selectedCloudId?`/api/whiteboard-platform/clubs/${encodeURIComponent(clubId)}/plays/${selectedCloudId}`:`/api/whiteboard-platform/clubs/${encodeURIComponent(clubId)}/plays`;const r=await fetch(url,{method,headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({title,category:cloudCategory,visibility:'CLUB',notes:cloudNotes,fixtureLabel,play,versionNote:'Saved from Coach App'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to save cloud tactic');setSelectedCloudId(j.data?.id||selectedCloudId);await loadCloud()}catch(e){setCloudError(e instanceof Error?e.message:'Unable to save cloud tactic')}finally{setCloudBusy(false)}}\n  function loadCloudPlay(item:CloudPlay){snapshot();setPlay(clonePlay(item.play));setSelectedCloudId(item.id);setCloudCategory(item.category||'General');setCloudNotes(item.notes||'');setCloudOpen(false)}\n  async function shareCloud(item:CloudPlay){setCloudBusy(true);try{const r=await fetch(`/api/whiteboard-platform/clubs/${encodeURIComponent(clubId)}/plays/${item.id}/share`,{method:'POST',headers:{authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to share tactic');const url=`${window.location.origin}${j.data.url}`;await navigator.clipboard.writeText(url);alert('Secure view-only link copied')}catch(e){setCloudError(e instanceof Error?e.message:'Unable to share tactic')}finally{setCloudBusy(false)}}\n  function exportPlay(){const blob=new Blob([JSON.stringify({title:activeFrame.name,fixtureLabel,play},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`playfooty-${activeFrame.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'tactic'}.json`;a.click();URL.revokeObjectURL(a.href)}"
s=s.replace(needle2,repl2)
s=s.replace("<button className=\"analyse\" onClick={()=>void analyseTactic('frame')}><Sparkles/>Analyse</button><button onClick={()=>setLibraryOpen(true)}><Library/>Library</button>", "<button className=\"analyse\" onClick={()=>void analyseTactic('frame')}><Sparkles/>Analyse</button><button onClick={()=>void loadCloud()}><Cloud/>Club Cloud</button><button onClick={exportPlay}><Download/>Export</button><button onClick={()=>setLibraryOpen(true)}><Library/>Local</button>")
insert="""{cloudOpen&&<div className=\"library-modal\"><section><header><div><span>CLUB TACTICS CLOUD</span><h2>Shared coaching library</h2></div><button onClick={()=>setCloudOpen(false)}><X/></button></header><div className=\"cloud-form\"><input value={cloudCategory} onChange={e=>setCloudCategory(e.target.value)} placeholder=\"Category\"/><textarea value={cloudNotes} onChange={e=>setCloudNotes(e.target.value)} placeholder=\"Coaching notes\"/><button className=\"save\" disabled={cloudBusy} onClick={()=>void saveCloud()}><Cloud/>{selectedCloudId?'Save new version':'Save to club cloud'}</button></div>{cloudError&&<p>{cloudError}</p>}{cloudBusy?<p>Syncing…</p>:cloudPlays.length?<div>{cloudPlays.map(item=><article key={item.id}><button onClick={()=>loadCloudPlay(item)}><b>{item.title}</b><span>{item.category} · {item.visibility}</span><small>{new Date(item.updatedAt).toLocaleString()}</small></button><button title=\"Share view-only link\" onClick={()=>void shareCloud(item)}><Share2/></button></article>)}</div>:<p>No cloud tactics yet. Save this play to make it available to the coaching group.</p>}</section></div>}"""
s=s.replace("{analysisOpen&&",insert+"\n    {analysisOpen&&")
s=s.replace(".library-modal section>p{", ".cloud-form{display:grid;grid-template-columns:160px 1fr auto;gap:8px;margin-bottom:12px}.cloud-form input,.cloud-form textarea{border:1px solid #304a5a;border-radius:9px;background:#0b1c27;color:#fff;padding:10px}.cloud-form textarea{min-height:44px;resize:vertical}.cloud-form .save{border:0;border-radius:9px;background:#20b8ff;color:#04121b;font-weight:900;padding:0 14px;display:flex;align-items:center;gap:6px}.library-modal section>p{")
p.write_text(s)
print('Whiteboard Stage 4 UI added')
