from pathlib import Path

path = Path('src/pages/CoachAppMatchDay.tsx')
text = path.read_text()
old = "@media(max-width:900px) and (orientation:portrait){.camd-match-layout{grid-template-areas:\"oval\" \"bench\" \"kpis\"}.camd-kpis>div{grid-template-columns:repeat(4,minmax(0,1fr))}.camd-kpis article{display:grid;justify-items:center;padding:7px 4px}.camd-kpis article strong{font-size:23px}.camd-kpis .wide-label{display:none}.camd-kpis .short-label{display:block}.camd-interchange{grid-template-columns:1fr}.camd-interchange>b{text-align:center}.camd-interchange>small{justify-content:center}.camd-bench{grid-template-columns:repeat(4,minmax(0,1fr))}.camd-tools{position:relative;margin-bottom:2px}}"
new = "@media(max-width:900px) and (orientation:portrait){.camd-ground{padding:7px}.camd-match-layout{grid-template-columns:180px minmax(0,1fr);grid-template-areas:\"kpis oval\" \"kpis bench\";gap:9px;align-items:start}.camd-match-layout>.camd-kpis{grid-area:kpis;position:sticky;top:132px;align-self:start;min-height:650px;padding:10px 8px}.camd-kpis header{display:block;margin-bottom:10px}.camd-kpis header span{display:block;font-size:25px}.camd-kpis header button{width:100%;margin-top:7px}.camd-kpis>div{grid-template-columns:1fr;gap:7px}.camd-kpis article{display:flex;min-height:58px;padding:9px 10px}.camd-kpis article strong{font-size:28px}.camd-kpis .wide-label{display:block}.camd-kpis .short-label{display:none}.camd-match-layout>.camd-oval{grid-area:oval;width:100%;min-height:650px;margin:0;padding:27px 12px;border-radius:48% / 38%}.camd-row{gap:5px}.camd-row.edge-row{width:104%;margin-left:-2%}.camd-player{min-height:76px}.camd-match-layout>.camd-interchange{grid-area:bench;grid-template-columns:1fr;width:100%;margin:0}.camd-interchange>b{text-align:left}.camd-interchange>small{justify-content:flex-start}.camd-bench{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.camd-tools{position:relative;margin:9px 0 2px 189px;width:calc(100% - 189px)}}"
if old not in text:
    raise SystemExit('Expected portrait Match Day media rule not found')
path.write_text(text.replace(old, new, 1))
