import { useEffect, useMemo, useState } from 'react'
import { CalendarCheck, Check, ClipboardCheck, ClipboardList, Clock3, PencilRuler, RefreshCw, Shield, Target, Trophy, Users } from 'lucide-react-native'
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { apiGet } from '../api'
import { ActionTile, Donut, MetricTile, ScreenHeader, SectionHeader, StatusPill, Surface, premium } from '../components/PremiumUI'
import { connectedAwayName, connectedHomeName, connectedRoundLabel, loadClubConnections, selectConnectedSheet, sheetMatchesFixture, type CoachContext } from '../connections'
import type { AuthSession, ClubAccount } from '../types'

type Props={club:ClubAccount;session:AuthSession;onOpenTrainingPlan:(sessionNumber:1|2)=>void;onOpenTrainingReport:(sessionNumber:1|2)=>void;onOpenAvailability:()=>void;onOpenTeamSelection:()=>void;onOpenGamePlan:()=>void;onOpenMatchDay:()=>void;onOpenWhiteboard:()=>void}
type Fixture={id:string;season:string;grade:string;round:number|null;matchDate:string|null;homeClubId:string;homeClubName:string;awayClubId:string;awayClubName:string;venue?:string|null;homeClubLogoUrl?:string|null;awayClubLogoUrl?:string|null;homeLogoUrl?:string|null;awayLogoUrl?:string|null;homeLogo?:string|null;awayLogo?:string|null}
type Sheet={id:string;fixtureId:string|null;season:string;grade:string;roundLabel:string;opponentName:string|null;matchDate:string|null;status:string;players:Array<unknown>}
type AvailabilityPlayer={status:string|null;reason:string|null}
type Availability={selectedSheetId:string|null;players:AvailabilityPlayer[]}
type Plan={id:string;planDate:string;title:string;focus:string|null;status?:string|null;publishedAt?:string|null;sessionNumber?:number|null}
type ReportSession={id:string;sessionDate:string;reportCompletedAt:string|null;status?:string|null;publishedAt?:string|null}
type OppositionPlan={status?:string|null;publishedAt?:string|null;overview?:string|null;teamInstructions?:string|null;stoppagePlan?:string|null;kickInPlan?:string|null;quarterTimeReminders?:string|null}
type ClubProfile={logoUrl?:string|null}

function dateLabel(value:string|null|undefined){if(!value)return'Date to be confirmed';const date=new Date(value);return Number.isNaN(date.getTime())?'Date to be confirmed':date.toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short'})}
function isPublished(value:{status?:string|null;publishedAt?:string|null}|null|undefined){return value?.status?.toUpperCase()==='PUBLISHED'||Boolean(value?.publishedAt)}
function cleanTeamName(name:string,competition:string){const trimmed=name.trim(),grade=competition.trim();if(!grade)return trimmed;const lowerName=trimmed.toLowerCase(),lowerGrade=grade.toLowerCase();if(lowerName.endsWith(lowerGrade))return trimmed.slice(0,trimmed.length-grade.length).replace(/[\s·\-–—]+$/,'').trim()||trimmed;return trimmed}

export function CoachingScreen({club,session,onOpenTrainingPlan,onOpenTrainingReport,onOpenAvailability,onOpenTeamSelection,onOpenGamePlan,onOpenMatchDay,onOpenWhiteboard}:Props){
 const[fixtures,setFixtures]=useState<Fixture[]>([]),[sheets,setSheets]=useState<Sheet[]>([]),[availability,setAvailability]=useState<Availability|null>(null),[plans,setPlans]=useState<Plan[]>([]),[reportSessions,setReportSessions]=useState<ReportSession[]>([]),[oppositionPlan,setOppositionPlan]=useState<OppositionPlan|null>(null),[opponentClubLogo,setOpponentClubLogo]=useState<string|null>(null),[canonical,setCanonical]=useState<CoachContext|null>(null),[grade,setGrade]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const token=session.access_token
 function load(){setLoading(true);setError('');loadClubConnections(club.clubId,token).then(connections=>{const nextFixtures=connections.fixtures as Fixture[],nextSheets=connections.sheets as Sheet[];setCanonical(connections.context);setFixtures(nextFixtures);setSheets(nextSheets);const grades=[...new Set([...nextFixtures.map(item=>item.grade),...nextSheets.map(item=>item.grade)].filter(Boolean))];setGrade(current=>current&&grades.includes(current)?current:(connections.context?.team?.grade&&grades.includes(connections.context.team.grade)?connections.context.team.grade:(grades[0]??'')));setLoading(false);void apiGet<{data?:Availability}>(`/club-portal/availability/clubs/${encodeURIComponent(club.clubId)}/overview`,token,6500).then(payload=>setAvailability(payload.data??null)).catch(()=>setAvailability(null));void apiGet<{data?:{plans?:Plan[]}}>(`/club-portal/training-plans/clubs/${encodeURIComponent(club.clubId)}`,token,6500).then(payload=>setPlans(payload.data?.plans??[])).catch(()=>setPlans([]));void apiGet<{data?:{sessions?:ReportSession[]}}>(`/club-portal/training-attendance/clubs/${encodeURIComponent(club.clubId)}`,token,6500).then(payload=>setReportSessions(payload.data?.sessions??[])).catch(()=>setReportSessions([]))}).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to open Coaching')).finally(()=>setLoading(false))}
 useEffect(load,[club.clubId,token])
 const grades=useMemo(()=>[...new Set([...fixtures.map(item=>item.grade),...sheets.map(item=>item.grade)].filter(Boolean))],[fixtures,sheets]),canonicalGrade=canonical?.team?.grade
 const fixture=(canonical?.fixture&&(!grade||!canonicalGrade||grade===canonicalGrade)?canonical.fixture as unknown as Fixture:null)??fixtures.find(item=>(!grade||item.grade===grade)&&sheets.some(sheet=>sheetMatchesFixture(sheet as never,item as never)))??fixtures.find(item=>!grade||item.grade===grade)??fixtures[0]??null
 const sheet=selectConnectedSheet(canonical,sheets as never[],fixture as never) as unknown as Sheet|null
 const opponent=fixture?(fixture.homeClubId===club.clubId?(fixture.awayClubName??connectedAwayName(fixture as never)):(fixture.homeClubName??connectedHomeName(fixture as never))):(sheet?.opponentName??'Opponent to be confirmed'),opponentClubId=fixture?(fixture.homeClubId===club.clubId?fixture.awayClubId:fixture.homeClubId):null,fixtureOpponentLogo=fixture?(fixture.homeClubId===club.clubId?(fixture.awayClubLogoUrl??fixture.awayLogoUrl??fixture.awayLogo??null):(fixture.homeClubLogoUrl??fixture.homeLogoUrl??fixture.homeLogo??null)):null,opponentLogo=fixtureOpponentLogo??opponentClubLogo,competition=grade||fixture?.grade||sheet?.grade||''
 useEffect(()=>{setOpponentClubLogo(null);if(!opponentClubId||opponentClubId===club.clubId)return;apiGet<{data?:ClubProfile}>(`/clubs/${encodeURIComponent(opponentClubId)}`,undefined,6500).then(payload=>setOpponentClubLogo(payload.data?.logoUrl??null)).catch(()=>setOpponentClubLogo(null))},[club.clubId,opponentClubId])
 useEffect(()=>{if(!sheet?.id){setOppositionPlan(null);return}apiGet<{data?:{plan?:OppositionPlan|null}}>(`/club-portal/opposition/clubs/${encodeURIComponent(club.clubId)}/sheets/${encodeURIComponent(sheet.id)}`,token,6500).then(payload=>setOppositionPlan(payload.data?.plan??null)).catch(()=>setOppositionPlan(null))},[club.clubId,sheet?.id,token])
 const counts=useMemo(()=>{const players=availability?.players??[];return{available:players.filter(row=>row.status==='AVAILABLE').length,unavailable:players.filter(row=>row.status==='UNAVAILABLE').length,test:players.filter(row=>row.status==='TEST'||row.status==='UNSURE'||row.status==='UNLIKELY').length,pending:players.filter(row=>!row.status).length,total:players.length}},[availability])
 const weeklyPlans=useMemo(()=>[...plans].filter(plan=>{const time=new Date(plan.planDate).getTime();return Number.isFinite(time)&&time>=Date.now()-8*86400000&&time<=Date.now()+8*86400000}).sort((a,b)=>a.planDate.localeCompare(b.planDate)).slice(0,2),[plans]),planOne=weeklyPlans.find(item=>item.sessionNumber===1)??weeklyPlans[0]??null,planTwo=weeklyPlans.find(item=>item.sessionNumber===2)??weeklyPlans[1]??null,reportFor=(plan:Plan|null)=>plan?reportSessions.find(item=>item.sessionDate===plan.planDate)??null:null
 const planOneReady=isPublished(planOne),planTwoReady=isPublished(planTwo),reportOneReady=Boolean(reportFor(planOne)?.reportCompletedAt)||isPublished(reportFor(planOne)),reportTwoReady=Boolean(reportFor(planTwo)?.reportCompletedAt)||isPublished(reportFor(planTwo)),availabilityReady=counts.total>0&&counts.pending===0,selectionReady=sheet?.status?.toUpperCase()==='PUBLISHED',gamePlanReady=isPublished(oppositionPlan)
 const readiness=[{label:'Training Plan 1',ready:planOneReady},{label:'Training Report 1',ready:reportOneReady},{label:'Availability',ready:availabilityReady},{label:'Training Plan 2',ready:planTwoReady},{label:'Training Report 2',ready:reportTwoReady},{label:'Team Selection',ready:selectionReady},{label:'Game Plan',ready:gamePlanReady}],completed=readiness.filter(item=>item.ready).length
 const steps=[{title:'Training Plan 1',copy:'Build the first session.',icon:ClipboardList,tone:premium.blue,ready:planOneReady,onPress:()=>onOpenTrainingPlan(1)},{title:'Training Report 1',copy:'Attendance and outcomes.',icon:ClipboardCheck,tone:'#4385FF',ready:reportOneReady,onPress:()=>onOpenTrainingReport(1)},{title:'Availability',copy:'Player status before selection.',icon:Users,tone:premium.purple,ready:availabilityReady,onPress:onOpenAvailability},{title:'Training Plan 2',copy:'Final session before match day.',icon:ClipboardList,tone:premium.orange,ready:planTwoReady,onPress:()=>onOpenTrainingPlan(2)},{title:'Training Report 2',copy:'Close the training week.',icon:ClipboardCheck,tone:'#F7A142',ready:reportTwoReady,onPress:()=>onOpenTrainingReport(2)},{title:'Team Selection',copy:'Select and publish the side.',icon:Trophy,tone:premium.green,ready:selectionReady,onPress:onOpenTeamSelection},{title:'Game Plan',copy:'Opposition and match priorities.',icon:Shield,tone:'#1EA6A8',ready:gamePlanReady,onPress:onOpenGamePlan}]
 if(loading)return <View style={s.state}><ActivityIndicator size="large" color={premium.blue}/><Text style={s.stateText}>Opening coaching workspace…</Text></View>
 return <View style={s.page}><ScreenHeader eyebrow="FOOTBALL DEPARTMENT" title="Coaching" subtitle="Plan the week, select the side and run match day." right={<View style={s.headerRight}><View style={s.gradePicker}>{grades.map(item=><Pressable key={item} onPress={()=>setGrade(item)} style={[s.gradeChip,grade===item&&s.gradeChipActive]}><Text numberOfLines={1} style={[s.gradeText,grade===item&&s.gradeTextActive]}>{item}</Text></Pressable>)}</View><Pressable onPress={load} style={s.refresh}><RefreshCw size={18} color={premium.ink}/></Pressable></View>}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>{error?<View style={s.error}><Text style={s.errorTitle}>Coaching data unavailable</Text><Text style={s.errorCopy}>{error}</Text></View>:null}
  <View style={s.heroGrid}><Surface style={s.matchCard}><View style={s.cardHead}><View><Text style={s.cardEyebrow}>NEXT MATCH</Text><Text style={s.cardTitle}>{connectedRoundLabel(fixture as never,sheet as never)}</Text></View><StatusPill label={dateLabel(fixture?.matchDate??sheet?.matchDate)} tone={premium.blue}/></View><View style={s.teams}><Team logo={club.logoUrl} name={club.clubName} competition={competition}/><View style={s.versus}><View style={s.vsCircle}><Text style={s.vs}>VS</Text></View><Text numberOfLines={1} style={s.venue}>{fixture?.venue??'Venue TBC'}</Text></View><Team logo={opponentLogo} name={opponent} competition={competition}/></View></Surface>
   <Surface style={s.readiness}><View style={s.cardHead}><View><Text style={s.cardEyebrow}>CURRENT WEEK</Text><Text style={s.cardTitle}>Readiness</Text></View><StatusPill label={`${completed}/7 COMPLETE`} tone={completed===7?premium.green:premium.orange}/></View><View style={s.readinessBody}><Donut value={completed} max={7} label="READY" tone={completed===7?premium.green:premium.blue} size={142}/><View style={s.checkList}>{readiness.map(item=><View key={item.label} style={s.checkRow}><View style={[s.checkDot,item.ready&&s.checkDone]}>{item.ready?<Check size={10} color="#fff"/>:null}</View><Text numberOfLines={1} style={s.checkLabel}>{item.label}</Text><Text style={[s.checkState,item.ready&&s.checkStateDone]}>{item.ready?'Ready':'Pending'}</Text></View>)}</View></View></Surface></View>
  <View style={s.metrics}><MetricTile icon={Users} label="Available" value={counts.total?String(counts.available):'—'} meta="Ready to play" tone={premium.green}/><MetricTile icon={Clock3} label="Awaiting response" value={counts.total?String(counts.pending):'—'} meta="Needs follow-up" tone={premium.orange}/><MetricTile icon={Shield} label="Unavailable" value={counts.total?String(counts.unavailable):'—'} meta="Not available" tone={premium.red}/><MetricTile icon={CalendarCheck} label="Test / unsure" value={counts.total?String(counts.test):'—'} meta="Monitor before selection" tone={premium.purple}/></View>
  <SectionHeader eyebrow="WEEKLY WORKFLOW" title="Football operations" detail="Every tile opens the existing connected workflow. Ready status only turns on when that step is actually published or completed."/>
  <View style={s.stepGrid}>{steps.map((step,index)=><ActionTile key={step.title} icon={step.icon} title={step.title} copy={step.copy} tone={step.tone} onPress={step.onPress} badge={step.ready?'READY':`STEP ${index+1}`}/>)}</View>
  <SectionHeader eyebrow="GAME DAY" title="Coaching tools" detail="Purpose-built workspaces stay intact — including the oval, interchange and tactical board."/>
  <View style={s.tools}><ActionTile icon={Target} title="Match Day" copy="Open the live oval, interchange, scoreboard, KPIs and match controls." tone={premium.blue} onPress={onOpenMatchDay} badge="LIVE WORKSPACE"/><ActionTile icon={PencilRuler} title="Whiteboard" copy="Move players, draw structures and save tactical boards." tone={premium.purple} onPress={onOpenWhiteboard} badge="TACTICS"/></View>
 </ScrollView></View>
}

function Team({logo,name,competition}:{logo?:string|null;name:string;competition:string}){const teamName=cleanTeamName(name,competition);return <View style={s.team}>{logo?<Image source={{uri:logo}} style={s.teamLogo} resizeMode="contain"/>:<View style={s.teamFallback}><Text style={s.teamFallbackText}>{teamName.slice(0,1)}</Text></View>}<Text numberOfLines={2} style={s.teamName}>{teamName}</Text>{competition?<Text numberOfLines={1} style={s.teamCompetition}>{competition}</Text>:null}</View>}

const s=StyleSheet.create({page:{flex:1,backgroundColor:premium.canvas},state:{flex:1,alignItems:'center',justifyContent:'center',gap:10,backgroundColor:premium.canvas},stateText:{fontSize:13,color:premium.muted},headerRight:{flexDirection:'row',alignItems:'center',gap:9},gradePicker:{maxWidth:330,flexDirection:'row',gap:6},gradeChip:{maxWidth:135,height:38,borderWidth:1,borderColor:premium.border,borderRadius:11,paddingHorizontal:11,justifyContent:'center',backgroundColor:premium.surface},gradeChipActive:{backgroundColor:premium.blue,borderColor:premium.blue},gradeText:{fontSize:10.5,fontWeight:'800',color:premium.ink},gradeTextActive:{color:'#fff'},refresh:{width:40,height:40,borderWidth:1,borderColor:premium.border,borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:premium.surface},content:{padding:20,paddingBottom:40,gap:16},error:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#FFD6DD',backgroundColor:'#FFF7F8'},errorTitle:{fontSize:13,fontWeight:'900',color:premium.red},errorCopy:{fontSize:10.5,color:premium.muted,marginTop:4},heroGrid:{flexDirection:'row',gap:14},matchCard:{flex:1,minHeight:300,padding:18},readiness:{width:410,minHeight:300,padding:18},cardHead:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},cardEyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.15,color:premium.muted2},cardTitle:{fontSize:20,fontWeight:'900',color:premium.ink,marginTop:4},teams:{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:16,paddingTop:18},team:{width:150,alignItems:'center',gap:7},teamLogo:{width:78,height:78},teamFallback:{width:78,height:78,borderRadius:24,backgroundColor:premium.blueSoft,alignItems:'center',justifyContent:'center'},teamFallbackText:{fontSize:30,fontWeight:'900',color:premium.blue},teamName:{fontSize:13,fontWeight:'900',color:premium.ink,textAlign:'center'},teamCompetition:{fontSize:9.5,fontWeight:'700',color:premium.muted,textAlign:'center'},versus:{width:90,alignItems:'center',gap:10},vsCircle:{width:46,height:46,borderRadius:23,backgroundColor:'#F0F3F7',alignItems:'center',justifyContent:'center'},vs:{fontSize:12,fontWeight:'900',color:premium.ink},venue:{fontSize:9.5,color:premium.muted,maxWidth:90,textAlign:'center'},readinessBody:{flex:1,flexDirection:'row',alignItems:'center',gap:16},checkList:{flex:1,gap:7},checkRow:{height:24,flexDirection:'row',alignItems:'center',gap:7},checkDot:{width:18,height:18,borderRadius:9,borderWidth:1,borderColor:premium.border,alignItems:'center',justifyContent:'center'},checkDone:{backgroundColor:premium.green,borderColor:premium.green},checkLabel:{fontSize:10.5,color:premium.ink,flex:1},checkState:{fontSize:8.5,fontWeight:'900',color:premium.muted2},checkStateDone:{color:premium.green},metrics:{flexDirection:'row',gap:12},stepGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},tools:{flexDirection:'row',gap:12},})