import { useEffect, useState } from 'react'
import type { LucideIcon } from 'lucide-react-native'
import { CalendarDays, CircleDollarSign, Image as ImageIcon, Newspaper, Radio, RefreshCw, Sparkles, Trophy, UsersRound } from 'lucide-react-native'
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { ActionTile, Donut, MetricTile, ScreenHeader, SectionHeader, StatusPill, Surface, premium } from '../components/PremiumUI'
import { connectedPlayerCount, connectedRoundLabel, loadClubConnections, type ClubConnections } from '../connections'
import type { AuthSession, ClubAccount } from '../types'

export type StudioTool='team-selection'|'live-match'|'events'|'fundraising'|'milestones'|'news'|'broadcast'
type Props={club:ClubAccount;session:AuthSession;onOpen:(tool:StudioTool)=>void}
type Tool={key:StudioTool;eyebrow:string;title:string;copy:string;icon:LucideIcon;tone:string}
const TOOLS:Tool[]=[{key:'team-selection',eyebrow:'TEAM MEDIA',title:'Team Selection',copy:'Generate the selected side graphic and social captions.',icon:UsersRound,tone:premium.blue},{key:'live-match',eyebrow:'MATCH DAY MEDIA',title:'Live Match',copy:'Create score graphics, captions and goal-kicker updates.',icon:Trophy,tone:premium.green},{key:'events',eyebrow:'CLUB EVENTS',title:'Events',copy:'Build event plans, safety guides and promotional posters.',icon:CalendarDays,tone:premium.orange},{key:'fundraising',eyebrow:'FUNDRAISING',title:'Fundraising',copy:'Create campaign plans, promotion and compliance guides.',icon:CircleDollarSign,tone:premium.purple},{key:'milestones',eyebrow:'PLAYER & CLUB',title:'Milestones',copy:'Celebrate games, goals, debuts, awards and achievements.',icon:Sparkles,tone:'#EA4AAA'},{key:'news',eyebrow:'EDITORIAL',title:'News',copy:'Write, edit and submit club stories for publication.',icon:Newspaper,tone:'#23A9C7'},{key:'broadcast',eyebrow:'GO LIVE',title:'Live Broadcast',copy:'Broadcast with connected score and clock overlays.',icon:Radio,tone:'#E5484D'}]

export function StudioScreen({club,session,onOpen}:Props){
 const[connections,setConnections]=useState<ClubConnections|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 function load(){setLoading(true);setError('');loadClubConnections(club.clubId,session.access_token).then(setConnections).catch(reason=>setError(reason instanceof Error?reason.message:'Studio data is unavailable')).finally(()=>setLoading(false))}
 useEffect(load,[club.clubId,session.access_token])
 const selected=connectedPlayerCount(connections?.teamSheet??null),selectionReady=selected>=22,matchReady=Boolean(connections?.teamSheet),fixtureReady=Boolean(connections?.fixture),round=connectedRoundLabel(connections?.fixture??null,connections?.teamSheet??null),readyCount=[selectionReady,matchReady,fixtureReady].filter(Boolean).length
 if(loading)return <View style={s.state}><ActivityIndicator size="large" color={premium.blue}/><Text style={s.stateText}>Opening Studio workspace…</Text></View>
 return <View style={s.page}><ScreenHeader eyebrow="MEDIA DEPARTMENT" title="Studio" subtitle="Create club media, publish updates and go live." right={<Pressable onPress={load} style={s.refresh}><RefreshCw size={18} color={premium.ink}/></Pressable>}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>{error?<View style={s.alert}><Text style={s.alertTitle}>Connected status unavailable</Text><Text style={s.alertCopy}>{error}</Text></View>:null}
  <View style={s.heroGrid}><Surface style={s.brandCard}><View style={s.cardHead}><View><Text style={s.cardEyebrow}>CLUB CONTENT HUB</Text><Text style={s.cardTitle}>Create. Publish. Go live.</Text></View><ImageIcon size={22} color={premium.blue}/></View><View style={s.brandBody}>{club.logoUrl?<Image source={{uri:club.logoUrl}} resizeMode="contain" style={s.logo}/>:<View style={s.logoFallback}><Text style={s.logoText}>{club.clubName.slice(0,1)}</Text></View>}<View style={s.brandCopy}><Text style={s.clubName}>{club.clubName}</Text><Text style={s.clubMeta}>Everything your club needs to keep supporters connected — powered by the same match, team and membership data.</Text><StatusPill label={round} tone={premium.blue}/></View></View></Surface>
   <Surface style={s.readiness}><View style={s.cardHead}><View><Text style={s.cardEyebrow}>MEDIA READINESS</Text><Text style={s.cardTitle}>Current match</Text></View><StatusPill label={`${readyCount}/3 READY`} tone={readyCount===3?premium.green:premium.orange}/></View><View style={s.readinessBody}><Donut value={readyCount} max={3} label="READY" tone={readyCount===3?premium.green:premium.blue} size={140}/><View style={s.readyList}><ReadyLine label="Selected side" detail={`${selected}/22 players`} ready={selectionReady}/><ReadyLine label="Live Match" detail={matchReady?'Connected':'Waiting for selection'} ready={matchReady}/><ReadyLine label="Fixture" detail={fixtureReady?'Connected':'Not resolved'} ready={fixtureReady}/></View></View></Surface></View>
  <View style={s.metrics}><MetricTile icon={UsersRound} label="Team selection" value={selectionReady?'Ready':`${selected}/22`} meta="Connected selected side" tone={premium.blue}/><MetricTile icon={Trophy} label="Live match" value={matchReady?'Connected':'Waiting'} meta="Score graphics and captions" tone={premium.green}/><MetricTile icon={Newspaper} label="Editorial" value="Ready" meta="Club news workspace" tone={premium.orange}/><MetricTile icon={Radio} label="Broadcast" value="Go live" meta="Connected match overlays" tone={premium.red}/></View>
  <SectionHeader eyebrow="CONTENT OPERATIONS" title="Studio tools" detail="Each tool keeps the same existing workflow but now sits inside one consistent premium media dashboard."/>
  <View style={s.toolGrid}>{TOOLS.map(tool=><ActionTile key={tool.key} icon={tool.icon} title={tool.title} copy={tool.copy} tone={tool.tone} onPress={()=>onOpen(tool.key)} badge={tool.eyebrow}/>)}</View>
 </ScrollView></View>
}

function ReadyLine({label,detail,ready}:{label:string;detail:string;ready:boolean}){return <View style={s.readyRow}><View style={[s.readyDot,ready&&s.readyDotDone]}/><View style={s.readyCopy}><Text style={s.readyLabel}>{label}</Text><Text numberOfLines={1} style={s.readyDetail}>{detail}</Text></View><Text style={[s.readyState,ready&&s.readyStateDone]}>{ready?'READY':'WAITING'}</Text></View>}

const s=StyleSheet.create({page:{flex:1,backgroundColor:premium.canvas},state:{flex:1,alignItems:'center',justifyContent:'center',gap:10,backgroundColor:premium.canvas},stateText:{fontSize:13,color:premium.muted},refresh:{width:40,height:40,borderWidth:1,borderColor:premium.border,borderRadius:11,backgroundColor:premium.surface,alignItems:'center',justifyContent:'center'},content:{padding:20,paddingBottom:40,gap:16},alert:{padding:14,borderWidth:1,borderColor:'#FFD6DD',borderRadius:14,backgroundColor:'#FFF7F8'},alertTitle:{fontSize:13,fontWeight:'900',color:premium.red},alertCopy:{fontSize:10.5,color:premium.muted,marginTop:4},heroGrid:{flexDirection:'row',gap:14},brandCard:{flex:1,minHeight:292,padding:18},readiness:{width:390,minHeight:292,padding:18},cardHead:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},cardEyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:premium.muted2},cardTitle:{fontSize:20,fontWeight:'900',color:premium.ink,marginTop:4},brandBody:{flex:1,flexDirection:'row',alignItems:'center',gap:22},logo:{width:100,height:100},logoFallback:{width:100,height:100,borderRadius:28,backgroundColor:premium.blueSoft,alignItems:'center',justifyContent:'center'},logoText:{fontSize:38,fontWeight:'900',color:premium.blue},brandCopy:{flex:1,gap:8},clubName:{fontSize:24,fontWeight:'900',color:premium.ink,letterSpacing:-.5},clubMeta:{fontSize:11.5,lineHeight:17,color:premium.muted,maxWidth:430},readinessBody:{flex:1,flexDirection:'row',alignItems:'center',gap:16},readyList:{flex:1,gap:13},readyRow:{flexDirection:'row',alignItems:'center',gap:8},readyDot:{width:12,height:12,borderRadius:6,backgroundColor:'#D8DEE8'},readyDotDone:{backgroundColor:premium.green},readyCopy:{flex:1},readyLabel:{fontSize:11,fontWeight:'800',color:premium.ink},readyDetail:{fontSize:9.5,color:premium.muted,marginTop:2},readyState:{fontSize:8.5,fontWeight:'900',color:premium.muted2},readyStateDone:{color:premium.green},metrics:{flexDirection:'row',gap:12},toolGrid:{flexDirection:'row',flexWrap:'wrap',gap:12}})