export type StudioClub={id:string;name:string;logoUrl:string|null;primaryColour:string|null;secondaryColour?:string|null}
export type StudioPlanItem={label?:string;detail:string;owner?:string;timing?:string;priority?:'HIGH'|'MEDIUM'|'LOW'|string}
export type StudioPlanSection={title:string;intro?:string;items?:StudioPlanItem[]}
export type StudioPlan={title:string;subtitle:string;executiveSummary:string;objectives?:string[];assumptions?:string[];sections?:StudioPlanSection[];timeline?:Array<{when:string;action:string;owner?:string}>;runSheet?:Array<{time:string;action:string;owner?:string;notes?:string}>;finalChecks?:string[]}
export type StudioCreative={eyebrow:string;headline:string;subheadline:string;callToAction:string;detailLines?:string[];primaryColour?:string;accentColour?:string;textColour?:string;layout?:string;visualDirection?:string;backgroundPrompt?:string;socialCaption?:string}
export type StudioAiPackage={plan:StudioPlan;creative:StudioCreative;backgroundDataUrl?:string;disclaimer:string;textModel?:string;imageModel?:string|null}

export async function generateStudioAiPackage(args:{clubId:string;token:string;club:StudioClub;kind:'EVENT'|'FUNDRAISING';subtype:string;style:string;answers:Record<string,string>;wantsPlan:boolean;wantsPoster:boolean}){
 const response=await fetch(`/api/club-portal/ai-graphics/clubs/${encodeURIComponent(args.clubId)}/studio-package`,{method:'POST',headers:{authorization:`Bearer ${args.token}`,'content-type':'application/json'},body:JSON.stringify({kind:args.kind,subtype:args.subtype,style:args.style,wantsPlan:args.wantsPlan,wantsPoster:args.wantsPoster,club:{name:args.club.name,primaryColour:args.club.primaryColour,secondaryColour:args.club.secondaryColour},answers:args.answers})})
 const payload=await response.json().catch(()=>({})) as {data?:StudioAiPackage;error?:string}
 if(!response.ok||!payload.data)throw new Error(payload.error||'AI generation unavailable — try again.')
 return payload.data
}

function safeHex(value:string|undefined|null,fallback:string){return /^#[0-9a-f]{6}$/i.test(value||'')?value!:fallback}
function textColourFor(hex:string){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return(r*299+g*587+b*114)/1000>150?'#061019':'#ffffff'}
function loadImage(url:string|null|undefined){if(!url)return Promise.resolve<HTMLImageElement|null>(null);return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url})}
function cover(ctx:CanvasRenderingContext2D,image:HTMLImageElement,w:number,h:number){const scale=Math.max(w/image.width,h/image.height),sw=w/scale,sh=h/scale;ctx.drawImage(image,(image.width-sw)/2,(image.height-sh)/2,sw,sh,0,0,w,h)}
function wrapLines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,maxLines=4){const words=(text||'').trim().split(/\s+/).filter(Boolean),lines:string[]=[];let current='';for(const word of words){const test=current?`${current} ${word}`:word;if(current&&ctx.measureText(test).width>maxWidth){lines.push(current);current=word;if(lines.length>=maxLines)break}else current=test}if(current&&lines.length<maxLines)lines.push(current);return lines}
function drawWrapped(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number,maxLines:number){const lines=wrapLines(ctx,text,maxWidth,maxLines);lines.forEach((line,index)=>ctx.fillText(line,x,y+index*lineHeight));return y+lines.length*lineHeight}

export async function renderAiPoster(canvas:HTMLCanvasElement|null,club:StudioClub,pkg:StudioAiPackage){if(!canvas)throw new Error('Poster canvas unavailable');const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Poster canvas unavailable');const W=1080,H=1350;canvas.width=W;canvas.height=H;const primary=safeHex(pkg.creative.primaryColour,safeHex(club.primaryColour,'#0b73b9')),accent=safeHex(pkg.creative.accentColour,'#42b8ff'),text=safeHex(pkg.creative.textColour,'#ffffff');const[background,logo]=await Promise.all([loadImage(pkg.backgroundDataUrl),loadImage(club.logoUrl)]);if(background)cover(ctx,background,W,H);else{const gradient=ctx.createLinearGradient(0,0,W,H);gradient.addColorStop(0,primary);gradient.addColorStop(1,'#06131d');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H)}
 const shade=ctx.createLinearGradient(0,0,0,H);shade.addColorStop(0,'rgba(3,9,14,.18)');shade.addColorStop(.42,'rgba(3,9,14,.22)');shade.addColorStop(.68,'rgba(3,9,14,.70)');shade.addColorStop(1,'rgba(3,9,14,.96)');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H)
 if(logo){ctx.fillStyle='rgba(255,255,255,.95)';ctx.beginPath();ctx.roundRect(64,58,150,150,24);ctx.fill();const scale=Math.min(116/logo.width,116/logo.height);ctx.drawImage(logo,81+(116-logo.width*scale)/2,75+(116-logo.height*scale)/2,logo.width*scale,logo.height*scale)}
 ctx.textAlign='left';ctx.fillStyle=accent;ctx.font='900 24px Arial';ctx.fillText((pkg.creative.eyebrow||club.name).toUpperCase().slice(0,62),64,278)
 ctx.fillStyle=text;ctx.font='900 78px Arial';let y=365;y=drawWrapped(ctx,(pkg.creative.headline||'CLUB UPDATE').toUpperCase(),64,y,950,82,4)+18
 ctx.fillStyle='rgba(255,255,255,.88)';ctx.font='700 31px Arial';y=drawWrapped(ctx,pkg.creative.subheadline||'',64,y,930,42,3)+28
 const details=(pkg.creative.detailLines||[]).filter(Boolean).slice(0,5);ctx.font='800 27px Arial';for(const detail of details){ctx.fillStyle='rgba(255,255,255,.88)';y=drawWrapped(ctx,detail,64,y,920,36,2)+11}
 const cta=pkg.creative.callToAction||'GET BEHIND THE CLUB';ctx.fillStyle=accent;ctx.beginPath();ctx.roundRect(64,1120,952,120,20);ctx.fill();ctx.fillStyle=textColourFor(accent);ctx.textAlign='center';ctx.font='900 34px Arial';ctx.fillText(cta.toUpperCase().slice(0,52),540,1192)
 ctx.textAlign='left';ctx.fillStyle='rgba(255,255,255,.66)';ctx.font='800 18px Arial';ctx.fillText(club.name.toUpperCase().slice(0,55),64,1296);ctx.textAlign='right';ctx.fillText('PLAYFOOTY STUDIO',1016,1296)
 return canvas.toDataURL('image/png')}

function ascii(value:string){return(value||'').normalize('NFKD').replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[^\x20-\x7E\n]/g,' ')}
function escPdf(value:string){return ascii(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function wrapText(text:string,width=88){const result:string[]=[];for(const paragraph of ascii(text).split(/\n+/)){const words=paragraph.trim().split(/\s+/).filter(Boolean);if(!words.length){result.push('');continue}let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(test.length>width&&line){result.push(line);line=word}else line=test}if(line)result.push(line)}return result}

type PdfLine={text:string;bold?:boolean;size?:number;gap?:number}
function flattenPlan(club:StudioClub,plan:StudioPlan,disclaimer:string){const lines:PdfLine[]=[];const heading=(text:string)=>{lines.push({text,bold:true,size:15,gap:5})};lines.push({text:'PLAYFOOTY STUDIO',bold:true,size:10,gap:3},{text:plan.title||'Club Plan',bold:true,size:22,gap:3},{text:plan.subtitle||club.name,bold:true,size:12,gap:8});heading('EXECUTIVE SUMMARY');wrapText(plan.executiveSummary||'').forEach(text=>lines.push({text,size:10}));if(plan.objectives?.length){heading('OBJECTIVES');plan.objectives.forEach(item=>wrapText(`- ${item}`).forEach(text=>lines.push({text,size:10})))}if(plan.assumptions?.length){heading('ASSUMPTIONS / CHECKS');plan.assumptions.forEach(item=>wrapText(`- ${item}`).forEach(text=>lines.push({text,size:10})))}for(const section of plan.sections||[]){heading(section.title||'PLAN');if(section.intro)wrapText(section.intro).forEach(text=>lines.push({text,size:10}));for(const item of section.items||[]){const meta=[item.priority,item.timing,item.owner].filter(Boolean).join(' | ');const lead=item.label?`${item.label}: `:'';wrapText(`- ${lead}${item.detail}${meta?` [${meta}]`:''}`).forEach(text=>lines.push({text,size:10}))}}
 if(plan.timeline?.length){heading('TIMELINE');for(const item of plan.timeline)wrapText(`${item.when}: ${item.action}${item.owner?` - ${item.owner}`:''}`).forEach(text=>lines.push({text,size:10}))}
 if(plan.runSheet?.length){heading('RUN SHEET');for(const item of plan.runSheet)wrapText(`${item.time}: ${item.action}${item.owner?` - ${item.owner}`:''}${item.notes?` (${item.notes})`:''}`).forEach(text=>lines.push({text,size:10}))}
 if(plan.finalChecks?.length){heading('FINAL CHECKS');plan.finalChecks.forEach(item=>wrapText(`- ${item}`).forEach(text=>lines.push({text,size:10})))}heading('IMPORTANT');wrapText(disclaimer,82).forEach(text=>lines.push({text,size:8}));return lines}

export function createAiPlanPdf(club:StudioClub,plan:StudioPlan,disclaimer:string){const source=flattenPlan(club,plan,disclaimer),pages:PdfLine[][]=[];let page:PdfLine[]=[],used=0;for(const line of source){const height=(line.size||10)+3+(line.gap||0);if(used+height>690&&page.length){pages.push(page);page=[];used=0}page.push(line);used+=height}if(page.length)pages.push(page);const objects:string[]=['',''];const fontRegular=3,fontBold=4;objects[fontRegular]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[fontBold]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';const kids:string[]=[];pages.forEach((lines,index)=>{const pageId=5+index*2,contentId=pageId+1;kids.push(`${pageId} 0 R`);let y=790;const commands=['BT'];for(const line of lines){const size=line.size||10,font=line.bold?'F2':'F1';commands.push(`/${font} ${size} Tf`,`1 0 0 1 48 ${y} Tm`,`(${escPdf(line.text)}) Tj`);y-=size+3+(line.gap||0)}commands.push('ET');const stream=commands.join('\n');objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}\nendstream`});objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;let pdf='%PDF-1.4\n';const offsets:number[]=[0];for(let i=1;i<objects.length;i++){offsets[i]=new TextEncoder().encode(pdf).length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=new TextEncoder().encode(pdf).length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return URL.createObjectURL(new Blob([new TextEncoder().encode(pdf)],{type:'application/pdf'}))}

export function slug(value:string){return(value||'studio-package').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'studio-package'}
